### ISSUE TITLE
Opening Lua Standard Libraries

### ISSUE THREAD

**Issue by JustAPerson** [khvzak/mlua#1]
I mostly care about loading LuaJIT's `ffi` and `jit` libraries, but what are your thoughts about the [`rlua` API for opening specific libraries](https://docs.rs/rlua/0.17.0/rlua/struct.Lua.html#method.new_with)?

**Comment by JustAPerson** [comment]
Also perhaps the `ffi` module of the rust library should be made public.

**Comment by khvzak** [comment]
Done in v0.2.1
Now these libraries are loaded by default (for LuaJIT). I also added [new_with()](https://docs.rs/mlua/0.2.1/mlua/struct.Lua.html#method.new_with) method, similar to the [rlua one](https://docs.rs/rlua/0.17.0/rlua/struct.Lua.html#method.new_with), but Lua 5.1/5.2/5.3/JIT aware.
