### ISSUE TITLE
serde

### ISSUE THREAD

**Issue by reyk** [khvzak/mlua#10]
I know that there‘s `mlua_serde` but is there any plan to add serde support to `mlua` directly? Maybe behind a `serde` feature flag?

The main reason is that it would allow a better integration: `mlua_serde` currently skips a few `Value` variants like `Value::UserData`. Deserializing user data would be a nice feature, especially when it contains some strict types. But in order to do this, I think we’d need the `T: UserData + Serialize + Deserialize` bound for `AnyUserData` internally.

**Comment by khvzak** [comment]
serde support is definitely in the project roadmap. I'm planning to work on this feature soon (in Aug)

**Comment by khvzak** [comment]
I released v0.5.0 with serde (`serialize` feature flag) support. `Value::UserData` is supported for serialization (if created by `create_ser_userdata()`). 
[Example](https://github.com/khvzak/mlua/blob/master/examples/serialize.rs)
