### ISSUE TITLE
userdata is not expected type

### ISSUE THREAD

**Issue by Ilqjx** [khvzak/mlua#100]
Hi, I wrote a demo about mlua, but there is an error here
https://github.com/Ilqjx/module-demo/blob/1900b7bfeb0ea5c00d421d293ed4e38784fb0ec2/src/main.rs#L56,
err: userdata is not expected type.
Can you help me see what caused this?

**Comment by Ilqjx** [comment]
The above address is no longer valid, this is the new address.
https://github.com/Ilqjx/module-demo/blob/ce29f8703180091f8fa2328e9af20a32a676c57e/src/main.rs#L55

**Comment by Ilqjx** [comment]
This is a smaller demo, but it still went wrong, err: UserDataTypeMismatch.
https://github.com/Ilqjx/mlua-min-demo/blob/a3f2e7601c97fc2eb9253f018c3250c19101508c/src/main.rs#L30

**Comment by khvzak** [comment]
As far as I can see you load Rust module with Response object and then return Response defined in the main program.
They are different types and you cannot mix them (since Rust does not provide stable ABI).

To solve this you can move `new_response` to the main program.

**Comment by Ilqjx** [comment]
I move `new_response` to the main program, but this has no effect.
https://github.com/Ilqjx/module-demo/blob/02b2108dafcfa96d62de7d8647d2c846b026ed4a/src/main.rs#L54

**Comment by Ilqjx** [comment]
Hello, can you please help me take a look, I have moved `new_response` to the main program, but this error still exists, `userdata is not expected type`.
https://github.com/Ilqjx/module-demo/blob/633581bb175746b50c064c815d072e8c0a3e180f/src/lib.rs#L4

**Comment by khvzak** [comment]
Is it intentional to load module into the main program?
You have defined `Response` objects in the module and in the program. It's a logic error to mix them. They are not the same types after crossing binary boundary. Your module can be compiled by any rustc version with differenct optimization options and since Rust does not provide ABI it's UB (unsafe) to mix them.

In your code:
```lua
local response = require("response")
local resp = response.new_response("")
```

`resp` - is a module's `Response` class and you return it as the program `Response` class. 
You need to move everything to one place: all to the module or all to the main program.

**Comment by Ilqjx** [comment]
Does this mean that I cannot use `userdata` in the module in the main program?

**Comment by Ilqjx** [comment]
Yes, I need to interact with the module in the main program.
Is it necessary to create a new crate to create a Lua module? Is there any other way?
Or, What should I do to move everything to the main program?
Thanks

**Comment by Ilqjx** [comment]
When I move everything to the main program, the Lua module will not be generated.

**Comment by Ilqjx** [comment]
src/main.rs
mod response;

use std::future::Future;
use std::net::SocketAddr;
use std::pin::Pin;
use std::rc::Rc;
use std::task::{Context, Poll};

use hyper::server::conn::AddrStream;
use hyper::service::Service;
use hyper::{Body, Request, Response, Server};

use mlua::{
    chunk, Error as LuaError, Function, Lua, UserData,
};

use response::LuaResponse;

struct LuaRequest(SocketAddr, Request<Body>);

impl UserData for LuaRequest {}

pub struct Svc(Rc<Lua>, SocketAddr);

impl Service<Request<Body>> for Svc {
    type Response = Response<Body>;
    type Error = LuaError;
    type Future = Pin<Box<dyn Future<Output=Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: Request<Body>) -> Self::Future {
        let lua = self.0.clone();
        let lua_req = LuaRequest(self.1, req);
        Box::pin(async move {
            let resp;
            let handler: Function = lua.named_registry_value("http_handler")?;
            match handler.call_async::<_, LuaResponse>(lua_req).await {
                Ok(lua_resp) => {
                    let mut builder = Response::builder().status(lua_resp.status);
                    for (key, val) in lua_resp.headers {
                        builder = builder.header(key, val);
                    }
                    resp = builder.body(Body::from(lua_resp.body)).unwrap();
                },
                Err(err) => {
                    println!("err: {}", err);
                    resp = Response::builder().status(500).body(Body::from("Internal Server Error")).unwrap();
                }
            }

            Ok(resp)
        })
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let lua = unsafe { Rc::new(Lua::unsafe_new()) };

    let handler: Function = lua.load(chunk! {
        function(req)
            local response = require("response")
            local resp = response.new_response("")
            resp:set_status(200)
            resp:set_body("hello world")
            return resp
        end
    }).eval().unwrap();

    lua.set_named_registry_value("http_handler", handler).unwrap();

    let addr = ([127, 0, 0, 1], 9981).into();
    let server = Server::bind(&addr).executor(LocalExec).serve(MakeSvc(lua));

    println!("Listening on http://{}", addr);

    let local = tokio::task::LocalSet::new();
    local.run_until(server).await.expect("cannot run server")
}

struct MakeSvc(Rc<Lua>);

impl Service<&AddrStream> for MakeSvc {
    type Response = Svc;
    type Error = hyper::Error;
    type Future = Pin<Box<dyn Future<Output=Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&mut self, _: &mut Context) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, stream: &AddrStream) -> Self::Future {
        let lua = self.0.clone();
        let remote_addr = stream.remote_addr();
        Box::pin(async move { Ok(Svc(lua, remote_addr)) })
    }
}

#[derive(Clone, Copy, Debug)]
struct LocalExec;

impl<F> hyper::rt::Executor<F> for LocalExec
    where
        F: std::future::Future + 'static,
{
    fn execute(&self, fut: F) {
        tokio::task::spawn_local(fut);
    }
}

src/response.rs
use std::collections::HashMap;
use mlua::prelude::*;

#[mlua::lua_module]
fn response(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table().unwrap();
    exports.set("new_response", lua.create_function(new_response).unwrap()).unwrap();
    Ok(exports)
}

pub fn new_response(_: &Lua, _: String) -> LuaResult<LuaResponse> {
    Ok(LuaResponse::default())
}

#[derive(Clone, Debug)]
pub struct LuaResponse {
    pub status: u16,
    pub headers: HashMap<String, String>,
    pub body: String,
}

impl Default for LuaResponse {
    fn default() -> Self {
        Self {
            status: 200,
            headers: HashMap::new(),
            body: String::new(),
        }
    }
}

impl LuaUserData for LuaResponse {
    fn add_methods<'lua, M: LuaUserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method_mut("set_status", |_, resp, status: u16| {
            resp.status = status;
            Ok(())
        });

        methods.add_method_mut("set_header", |_, resp, (header_name, header_value): (String, String)| {
            resp.headers.insert(header_name, header_value);
            Ok(())
        });

        methods.add_method_mut("set_body", |_, resp, body: String| {
            resp.body = body;
            Ok(())
        });
    }
}

Cargo.toml
[package]
name = "module-demo"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full", "net"] }
mlua = { version = "0.6", features = ["luajit", "macros", "async", "module"] }

**Comment by Ilqjx** [comment]
src/main.rs
```Rust
mod response;

use std::future::Future;
use std::net::SocketAddr;
use std::pin::Pin;
use std::rc::Rc;
use std::task::{Context, Poll};

use hyper::server::conn::AddrStream;
use hyper::service::Service;
use hyper::{Body, Request, Response, Server};

use mlua::{
    chunk, Error as LuaError, Function, Lua, UserData,
};

use response::LuaResponse;

struct LuaRequest(SocketAddr, Request<Body>);

impl UserData for LuaRequest {}

pub struct Svc(Rc<Lua>, SocketAddr);

impl Service<Request<Body>> for Svc {
    type Response = Response<Body>;
    type Error = LuaError;
    type Future = Pin<Box<dyn Future<Output=Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: Request<Body>) -> Self::Future {
        let lua = self.0.clone();
        let lua_req = LuaRequest(self.1, req);
        Box::pin(async move {
            let resp;
            let handler: Function = lua.named_registry_value("http_handler")?;
            match handler.call_async::<_, LuaResponse>(lua_req).await {
                Ok(lua_resp) => {
                    let mut builder = Response::builder().status(lua_resp.status);
                    for (key, val) in lua_resp.headers {
                        builder = builder.header(key, val);
                    }
                    resp = builder.body(Body::from(lua_resp.body)).unwrap();
                },
                Err(err) => {
                    println!("err: {}", err);
                    resp = Response::builder().status(500).body(Body::from("Internal Server Error")).unwrap();
                }
            }

            Ok(resp)
        })
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let lua = unsafe { Rc::new(Lua::unsafe_new()) };

    let handler: Function = lua.load(chunk! {
        function(req)
            local response = require("response")
            local resp = response.new_response("")
            resp:set_status(200)
            resp:set_body("hello world")
            return resp
        end
    }).eval().unwrap();

    lua.set_named_registry_value("http_handler", handler).unwrap();

    let addr = ([127, 0, 0, 1], 9981).into();
    let server = Server::bind(&addr).executor(LocalExec).serve(MakeSvc(lua));

    println!("Listening on http://{}", addr);

    let local = tokio::task::LocalSet::new();
    local.run_until(server).await.expect("cannot run server")
}

struct MakeSvc(Rc<Lua>);

impl Service<&AddrStream> for MakeSvc {
    type Response = Svc;
    type Error = hyper::Error;
    type Future = Pin<Box<dyn Future<Output=Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&mut self, _: &mut Context) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, stream: &AddrStream) -> Self::Future {
        let lua = self.0.clone();
        let remote_addr = stream.remote_addr();
        Box::pin(async move { Ok(Svc(lua, remote_addr)) })
    }
}

#[derive(Clone, Copy, Debug)]
struct LocalExec;

impl<F> hyper::rt::Executor<F> for LocalExec
    where
        F: std::future::Future + 'static,
{
    fn execute(&self, fut: F) {
        tokio::task::spawn_local(fut);
    }
}
```

src/response.rs
```Rust
use std::collections::HashMap;
use mlua::prelude::*;

#[mlua::lua_module]
fn response(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table().unwrap();
    exports.set("new_response", lua.create_function(new_response).unwrap()).unwrap();
    Ok(exports)
}

pub fn new_response(_: &Lua, _: String) -> LuaResult<LuaResponse> {
    Ok(LuaResponse::default())
}

#[derive(Clone, Debug)]
pub struct LuaResponse {
    pub status: u16,
    pub headers: HashMap<String, String>,
    pub body: String,
}

impl Default for LuaResponse {
    fn default() -> Self {
        Self {
            status: 200,
            headers: HashMap::new(),
            body: String::new(),
        }
    }
}

impl LuaUserData for LuaResponse {
    fn add_methods<'lua, M: LuaUserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method_mut("set_status", |_, resp, status: u16| {
            resp.status = status;
            Ok(())
        });

        methods.add_method_mut("set_header", |_, resp, (header_name, header_value): (String, String)| {
            resp.headers.insert(header_name, header_value);
            Ok(())
        });

        methods.add_method_mut("set_body", |_, resp, body: String| {
            resp.body = body;
            Ok(())
        });
    }
}
```

Cargo.toml
[package]
name = "module-demo"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full", "net"] }
mlua = { version = "0.6", features = ["luajit", "macros", "async", "module"] }

**Comment by khvzak** [comment]
@Ilqjx 
You could change interface and return Lua Table instead. It's a common data structure that can be shared between any modules.

Also there is an option to register "response" module without having a physical library on disk. 
It can be done using [`load_from_function`](https://docs.rs/mlua/0.6.6/mlua/struct.Lua.html#method.load_from_function).
In this case you can share userdata types between module and the main program and your Lua code will work without changes.

**Comment by Ilqjx** [comment]
Thank you very much for your help. `load_from_function` solved my problem.
