### ISSUE TITLE
Module not found on windows

### ISSUE THREAD

**Issue by chipsenkbeil** [khvzak/mlua#101]
A user of my neovim plugin is trying to use my plugin that loads a lua module from a dll on Windows. This may just be user error on my part regarding how to build the dll on Windows with msvc. Is there a reason why the module with the specified name wouldn't be found within the dll on windows but would be found in the dylib or so of Mac and Linux respectively?

* [distant-lua/lib.rs](https://github.com/chipsenkbeil/distant/blob/master/distant-lua/src/lib.rs)
* [distant.nvim issue #57](https://github.com/chipsenkbeil/distant.nvim/issues/57)

```
error loading module 'distant_lua' from file 'C:\Users\mr_majkel\AppData\Local\Programs\Neovim\bin\distant_lua.dll':
^IThe specified module could not be found.^M
```

**Comment by khvzak** [comment]
I'll try to check on a windows 11 machine. 
There is a difference between Windows and Linux/Mac. On windows you have to link module to a Lua dll, whereas on unix it's not required. Therefore the same lua dll must be exist on windows.

**Comment by khvzak** [comment]
Answered in https://github.com/chipsenkbeil/distant.nvim/issues/57#issuecomment-969256617
