### ISSUE TITLE
__call metamethod shortcut

### ISSUE THREAD

**Issue by zdcthomas** [khvzak/mlua#102]
Hello!
First off, I want to thank you for this amazing library! It's working fantastically well and this is mostly just a question about ergonomics. 

I'm working with tables that have the `__call` metamethod on their metatables and currently I have something like 
```rust
    let call_func = table
        .get_metatable()
        .expect("failed to get metatable for table")
        .get::<_, LuaFunction>("__call")
        .expect("table doesn't have a __call on it's metatable");
    call_func.call(table, arg)
```
everywhere that I want to be able to use that function. (Actually I have it through a function but regardless)
Is there a more ergonomic was to handle this? If not would you be open to a PR focused on the table module to add in some metamethod functions? 

Thanks again!

**Comment by khvzak** [comment]
Thanks!

Actually the internal implementation would be much simpler. No need to get metatable and check for `__call` key.

I added `table.call()` support  to the [`TableExt`](https://docs.rs/mlua/0.6.6/mlua/trait.TableExt.html) trait with commit https://github.com/khvzak/mlua/commit/170818c46959a64201c5c412bb351e7f9229d02c .

**Comment by zdcthomas** [comment]
Oh wow! Thanks for such a fast response! I think that's pretty much an ideal solution honestly. Thanks!

**Comment by zdcthomas** [comment]
Alright I just tried it and it works great! Thanks again!
