### ISSUE TITLE
Can I make the elements of add_async_method variable?

### ISSUE THREAD

**Issue by mrxiaozhuox** [khvzak/mlua#106]
I use `add_async_method`  to create some function(method) for my project, but. when I try to edit some element(data) in this object, it's not work.

```
 methods.add_async_method("select", |_, mut this, name: String| async move {
    this.current = name.clone();
    this.db.lock().await.select_to(&db_name).to_lua_err()
});
```

but when I call other methods from this object, the `current` value was not update.

**Comment by khvzak** [comment]
In `add_async_method` you getting a clone of `this` (see [definition](https://docs.rs/mlua/0.7.0/mlua/trait.UserDataMethods.html#tymethod.add_async_method))
If it's not desirable you can rewrite your code to borrow instead:
```
methods.add_async_function("select", |_, (this, name): (YourType, String)| async move {
    let mut this = this.borrow_mut::<YourType>()?;
    this.current = name.clone();
    this.db.lock().await.select_to(&db_name).to_lua_err()
});
```

**Comment by mrxiaozhuox** [comment]
thanks.
