### ISSUE TITLE
Use c module error

### ISSUE THREAD

**Issue by cc-morning** [khvzak/mlua#107]
"error loading module 'cjson' from file './cjson.so':\n\t./cjson.so: undefined symbol: lua_checkstack\nstack traceback:\n\t[string \"src/strainer.rs:26:22\"]:1: in main chunk"

**Comment by khvzak** [comment]
Same as https://github.com/khvzak/mlua/issues/73

You need to make C symbols visible via
```
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
```

**Comment by cc-morning** [comment]
thx
