### ISSUE TITLE
How do I call_async in future

### ISSUE THREAD

**Issue by cc-morning** [khvzak/mlua#108]
Now is there a way to call call_async in future

**Comment by cc-morning** [comment]
example:
```rust
let (tx, mut rx) = mpsc::channel(128);

while let Some(row) = read_stream.next().await {
    tokio::spawn(async {
        match func.call_async::<Vec<String>, Vec<String>>(row).await {
            Ok(row) => {
                tx.send(row);
            }
            Err(e) => {
                error!("{:#?}", e);
            }
        };
    });
}

while let Some(row) = rx.recv().await {
    yield row;
}
```

**Comment by khvzak** [comment]
I'm not sure that fully understood the question, but
1) You probably should use `spawn_local` instead of `spawn` to run future in the same thread
2) The best way to avoid lifetime issues is storing function in the Lua registry and then get it back inside `spawn_local` by a handler

**Comment by cc-morning** [comment]
thk!
