### ISSUE TITLE
[Q] need to autogenerate Lua module

### ISSUE THREAD

**Issue by ildar** [khvzak/mlua#111]
... from an external crate/module. Any idea how to do that?

BTW, I couldn't find mlua/rlua chat. Where are the developers hang out?

**Comment by khvzak** [comment]
Could you explain please what did you mean under "generate Lua module from an external crate/module"? 
Unfortunately you cannot just take any module and export it to Lua without writing some code. At least "glue" code is required to describe interfaces and map Rust data types to Lua data types. I don't think it's even possible considering how rich Rust typesystem is.

> BTW, I couldn't find mlua/rlua chat. Where are the developers hang out?

Sorry I don't have any chat yet. Not sure about rlua though as it's an independent project.

**Comment by ildar** [comment]
чт, 23 дек. 2021 г., 0:33 Alex Orlenko ***@***.***>:

> Could you explain please what did you mean under "generate Lua module from
> an external crate/module"?
>
Presenting a huge specific create to Lua world.

> Unfortunately you cannot just take any module and export it to Lua without
> writing some code. At least "glue" code is required to describe interfaces
> and map Rust data types to Lua data types.
>
Exactly. This is the point.
One of the introspection mechanisms could fit  here quite well. Maybe
GNOME's is close to ideal.

> I don't think it's even possible considering how rich Rust typesystem is.
>
Dreaming is still not prohibited )))

> BTW, I couldn't find mlua/rlua chat. Where are the developers hang out?
>
> Sorry I don't have any chat yet. Not sure about rlua though as it's an
> independent project.
>
I just though about discussing things if i could find you somewhere in
chats...

Thanks.
