### ISSUE TITLE
building error at lua.unwrap().include_paths[0]

### ISSUE THREAD

**Issue by ildar** [khvzak/mlua#114]
having (ALTLinux) installation with
```
$ pkg-config --libs --cflags "lua" "lua >= 5.3" "lua < 5.4"
-llua -lm -ldl
```
building fails:
```
$ cd /tmp/remote-builds/mlua/ ; strace -fto /tmp/1.stra cargo b --features lua53
   Compiling mlua v0.7.0 (/tmp/remote-builds/mlua)
   Compiling serde v1.0.132
error: failed to run custom build command for `mlua v0.7.0 (/tmp/remote-builds/mlua)`

Caused by:
  process didn't exit successfully: `/tmp/remote-builds/mlua/target/debug/build/mlua-69c0ca88b62928dc/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LUA_INC
...
  --- stderr
  thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', build/find_normal.rs:75:9
```
Plz add the corresponding check. Thank you.

**Comment by khvzak** [comment]
Thanks, I updated error messages in 888b2bbf8db43dfd0df1a39a21bf1581615b8ace

**Comment by ildar** [comment]
This is wrong.
The problem isn't in a message. The problem is that pkg-config is not
obliged to show any `-I` paths in case the headers are available at
standard paths.
I just tested and see the same error, just more verbose:
> thread 'main' panicked at 'cannot find Lua 5.3 include paths using
`pkg-config`', build/find_normal.rs:76:14

**Comment by khvzak** [comment]
> The problem is that pkg-config is not obliged to show any `-I` paths in case the headers are available at standard paths.

Right, I see. It's quite weird case, means that altlinux does not support multiple Lua versions installed in the system?
I'll try to make include paths optional then.

**Comment by ildar** [comment]
On Tue, Dec 28, 2021 at 5:21 PM Alex Orlenko wrote:

> Right, I see. It's quite weird case, means that altlinux does not support
> multiple Lua versions installed in the system?
>
True.

**Comment by khvzak** [comment]
@ildar could you check again?

**Comment by ildar** [comment]
very good, worked fine.
thank you.
