### ISSUE TITLE
maybe add PartialEq to Error

### ISSUE THREAD

**Issue by viktor-ku** [khvzak/mlua#12]
Hi! Currently I am wrapping mlua Error with basically the same fields + `PartialEq` to be able to write tests for my program. Can you add `PartialEq` to the `Error`?

Or if you don't have time maybe I can do it?

Many thanks in advance, loving where your project got from `rlua`, many changes I think are definitely for the better!

**Comment by khvzak** [comment]
Unfortunately the `PartialEq` trait cannot be derived automatically for the enum variant `ExternalError(Arc<dyn StdError + Send + Sync>)`.
Is pattern matching not suitable for your case?
Similar to how it's done mlua tests, eg: https://github.com/khvzak/mlua/blob/0a13a96/tests/tests.rs#L116

**Comment by viktor-ku** [comment]
Yeah, thanks, got it!
