### ISSUE TITLE
mlua::Value is not `Send` with send feature.

### ISSUE THREAD

**Issue by LordMZTE** [khvzak/mlua#120]
I'm looking to store a lua callback to be called by an async event handler. I'm getting some trouble, as it doesn't seem to be possible to do this, as even with the `send` feature, `mlua::Value` isn't `Send`.

**Comment by khvzak** [comment]
`mlua::Value` indeed is not `Send` because holds reference `&Lua` which requires `Sync`.
The best solution would be storing values in the Lua Registry using [`Lua::create_registry_value`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_registry_value) function.
