### ISSUE TITLE
lua_pcall: thread called in wrong state 1

### ISSUE THREAD

**Issue by stevearc** [khvzak/mlua#121]
I'm attempting to create a rust library that I can call into from Neovim, but I'm encountering a hard crash when I attempt to use async functions and methods. I'm relatively new to rust and to the nuts and bolts of async, so it's quite likely that this is user error. If so, I'd appreciate pointers for what I should be doing instead!

This may be the same issue as #104, I'm not sure.

## Repro
On the lua side, I hacked up a function to do async polling
```lua
local function run(async_fn, callback, interval, ...)
  interval = interval or 100
  local t = coroutine.create(async_fn)

  local function poll(...)
    local ok, ret = coroutine.resume(t, ...)
    if coroutine.status(t) == "dead" then
      local err = nil
      if not ok then
        err, ret = ret, err
      end
      vim.schedule_wrap(callback)(err, ret)
      return true
    end
    return false
  end

  if not poll(...) then
    local timer = vim.loop.new_timer()
    timer:start(interval, interval, function()
      if poll() then
        timer:close()
      end
    end)
  end
end
```

This is the code I run to reproduce the crash
```lua
  local mod = require("my_lib")
  run(mod.test_async, function()
    print("Finished call 1")
  end, 100)
  run(mod.test_async, function()
    print("Finished call 2")
  end, 100)
```

And this is what the rust lib looks like
```rust
#[mlua::lua_module]
fn my_lib(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set(
        "test_async",
        lua.create_async_function(|_: &Lua, (): ()| async {
            task::sleep(Duration::from_secs(2)).await;
            Ok("This is the return value".to_string())
        })?,
    )?;
    Ok(exports)
}
```

When I run the lua test code, neovim crashes and prints out `LuaJIT ASSERT lj_api.c:1136: lua_pcall: thread called in wrong state 1`

## Notes
- The crash only happens when I have two async calls going at the same time
- The crash only happens when the async function returns a value (`Ok(())` works fine)

## System information
OS: Ubuntu 20.04
Neovim: v0.6.1
Rust: 1.57.0
mlua: 0.7.1 (features = ["async", "macros", "module", "lua51", "vendored"])

**Comment by khvzak** [comment]
Fixed, thanks!

**Comment by stevearc** [comment]
Fix confirmed. Thanks for the quick turnaround!
