### ISSUE TITLE
Compilation fails on musl target after upgrade to v0.7.2

### ISSUE THREAD

**Issue by afsec** [khvzak/mlua#124]
Hi.
After upgrade to v0.7.2 compilation fails on musl target. I tried all these solutions(https://github.com/khvzak/mlua/issues/85). But does not worked for me on my project.

Using v.0.7.1 works fine.

By the way, mlua project is awesome!

**Comment by khvzak** [comment]
Thanks, should be fixed in 4963cc1.
I'll cut a new release shortly.

**Comment by khvzak** [comment]
v0.7.3 released
