### ISSUE TITLE
Failed to cross-compilation

### ISSUE THREAD

**Issue by rise0chen** [khvzak/mlua#125]
![image](https://user-images.githubusercontent.com/12853908/150722743-d9ca8b51-65fc-47f5-9045-9a7d5f747c2f.png)
It is failed in `0.7.2` and `0.7.3`.
And, It is work in `0.7.0` and `0.7.1`.

**Comment by rise0chen** [comment]
`0.7.2` miss `../build/aarch64-unknown-linux-gnu/release/build/mlua-ffc458ffe4bfc29f/out/lua-build`

**Comment by rise0chen** [comment]
I can't recurrent it, in a new project.
Where are path `/out/lua-build` defined? I want to print it.

**Comment by rise0chen** [comment]
The problem may be caused by the cache.
It work after clean `mlua` and `lua-src`.
```bash
rm -rf ../build/aarch64-unknown-linux-gnu/release/deps/*lua*
rm -rf ../build/aarch64-unknown-linux-gnu/release/build/*lua*
```

**Comment by khvzak** [comment]
Please reopen if the issue is still present
