### ISSUE TITLE
Contain table in struct

### ISSUE THREAD

**Issue by KamilM1205** [khvzak/mlua#128]
How I can contain table in my struct? I have a struct that implements UserData. I'm getting a table as a method parameter and want to store it in a struct but I'm getting a lifetime error.
`cannot infer an appropriate lifetime for lifetime parameter 'lua due to conflicting requirements`

**Comment by khvzak** [comment]
The best way to store any Lua type in a `'static` container is by using `RegistryKey` via [`Lua::create_registry_value`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_registry_value).

**Comment by KamilM1205** [comment]
Thank you for answer. This worked for me.
