### ISSUE TITLE
is there a way to create rust-owned data and modify it with userdata from lua side?

### ISSUE THREAD

**Issue by viktor-ku** [khvzak/mlua#13]
Is it possible to create rust-owned state on rust side which is not passed to lua; and change this state from the userdata methods defined and passed to lua?

My goal is to create tables on lua side and somehow register these tables in the order that they are created. And the order is very important.

So for example on lua side I will have this:

```lua
function main(v)
  v:addRow({ _type.= "row", pos: 1 })
end
```

```rust
#[derive(Debug, Clone)]
struct V {
  n: u32,
  extern_val: Option<String>,
}

impl UserData for V {
  fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
    methods.add_method_mut("foo", |_, it, val: String| {
      println!("setting {} to self.extern_val", val);
      it.extern_val = Some(val);
     // somehow get a state and save val to it?
      Ok(())
    });
  }
}
```

`v` is an instance of the userdata. And so the next step would be to somehow get whatever was passed into the `addRow` method of that userdata and save it somewhere in the rust side.

Can I somehow do that?

Thanks in advance

**Comment by khvzak** [comment]
If I correctly understand, you want something like this?

```rust
lazy_static::lazy_static! {
    static ref ROWS: Mutex<Vec<HashMap<String, String>>> = Mutex::new(Vec::new());
}

pub struct V;

impl UserData for V {
    fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method("addRow", |_, _, t: HashMap<String, String>| {
            ROWS.lock().unwrap().push(t);
            Ok(())
        });
    }
}

fn main() -> Result<()> {
    let lua = Lua::new();

    lua.globals().set("v", V)?;
    lua.load(r#"
        v:addRow({ _type = "row", pos = 1 })
        v:addRow({ _type = "row", pos = 2 })
    "#).exec()?;

    println!("added rows: {:?}", ROWS.lock().unwrap());

    Ok(())
}
```

**Comment by viktor-ku** [comment]
Yeah, global state is not the best solution. 

You mean, I can pass custom state to `add_method` that I can then wrap into `Arc`?

**Comment by khvzak** [comment]
The first option:
https://gist.github.com/48ccbfb1a30ffa08bc7c69650ab5fefb
I modified the struct `V` to explicitly include state.

The second option:
https://gist.github.com/rust-play/f73e7607726d9651d3d36a7560824510
without modifying the struct `V` and passing `State` as an associated value.

**Comment by viktor-ku** [comment]
Thank you a lot for helping, really appreciate your time!
