### ISSUE TITLE
Async index metamethod

### ISSUE THREAD

**Issue by Tarik02** [khvzak/mlua#134]
Look at the following code:
```
use std::sync::Arc;

use mlua::{Lua, UserData, UserDataMethods, MetaMethod, chunk, Result};

#[derive(Clone)]
struct TestUserData {
    //
}

impl UserData for TestUserData {
    fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_async_method("test_method", |_lua, data, ()| async move {
            tokio::time::sleep(
                tokio::time::Duration::from_millis(20)
            ).await;
            Ok(1)
        });

        methods.add_async_meta_method(MetaMethod::Index, |_lua, data, index: String| async move {
            tokio::time::sleep(
                tokio::time::Duration::from_millis(20)
            ).await;
            Ok(index)
        });
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let lua = Arc::new(Lua::new());

    lua.globals().set("test_user_data", lua.create_userdata(TestUserData {})?)?;

    lua.load(chunk! {
        test_user_data:test_method()
        print(test_user_data.test)
    }).exec_async().await?;

    println!("Hello, world!");

    Ok(())
}
```

It causes and error "attempt to yield across a C-call boundary". From my investigation, I found out that in this case, index metamethod is actually handled by this function which is causes the problem: https://github.com/khvzak/mlua/blob/master/src/util.rs#L365

**Comment by khvzak** [comment]
Thanks for the report!
Indeed `__index` and `__newindex` cannot be async. 
Seems I should mention this in the documentation in a short term.
It will be very tricky to fix. I need to think about possible solutions (don't have ideas yet).

**Comment by Tarik02** [comment]
> Thanks for the report!
> Indeed `__index` and `__newindex` cannot be async.
> Seems I should mention this in the documentation in a short term.
> It will be very tricky to fix. I need to think about possible solutions (don't have ideas yet).

What do you think about #135?

**Comment by Tarik02** [comment]
As part of this, it is reasonable to add async variants for getters/setters (however, setter can't actually receive mutable instance of user data).
