### ISSUE TITLE
Advice on how to setup event listener

### ISSUE THREAD

**Issue by noib3** [khvzak/mlua#143]
First of all I'd like to thank you for the work on `mlua`, I've been using in to build an [autocompletion framework](https://github.com/noib3/nvim-compleet) for Neovim and I'm more than happy to sponsor this project.

The plugin is structured in the following way: on every keystroke a message is sent to an async runtime (e.g. tokio) along with some context (e.g. the cursor position), and the runtime starts fetching the completion results.

Every source runs in a separate task, and when it's done running it sends a vector of completion results back to the main thread via a [channel](https://docs.rs/tokio/0.1.15/tokio/sync/mpsc/fn.channel.html), where the UI can then be updated with the new results.

This is the part I'm having trouble with: how can I create a non-blocking event listener that runs on the main thread? I saw a few similar issues and the answer seems to be to wrap the callback in a `vim.schedule`, rescheduling the callback over and over until a messagge is received, possibly with some timeout to avoid using 100% of the CPU.

Is this really the only approach? Using something like a `Waker` would be a lot cleaner and would allow executing the callback right when the message is received.

Just to give an example, how can I make the following code print either `Hello John`  or `Hello Mary` without blocking the main thread?

```rust
#[mlua::lua_module]
fn hello(lua: &Lua) -> LuaResult<Table> {
    let (mut tx, mut rx) = std::sync::mpsc::channel::<String>();

    let mut i = 0;
    let _ = std::thread::spawn(move ||
        // Every once in a while a new message will be sent.
        loop {
            let name = if i % 2 == 0 { "John" } else { "Mary" };
            tx.send(name.into()).unwrap();
            i += 1;
            std::thread::sleep(std::time::Duration::from_secs(1));
        }
    );

    let hello = lua.create_function(move |lua, name: String| {
        let print = lua.globals().get::<_, mlua::Function>("print")?;
        print.call::<_, ()>(format!("Hello {name}!"))
    })?;

    // Something like this, expect being polled somehow and not blocking the
    // thread.
    loop {
        if let Ok(name) = rx.recv() {
            hello.call(name)?;
        } else {
            break;
        }
    }

    lua.create_table_from([("hello", hello)])
}
```

Would using `create_async_function` help? I believe that's just a wrapper around a lua coroutine, so it'd still have to be handled by Neovim's event loop by using `vim.schedule`.

Any ideas?

**Comment by khvzak** [comment]
Thanks for the support!

> how can I create a non-blocking event listener that runs on the main thread? I saw a few similar issues and the answer seems to be to wrap the callback in a vim.schedule, rescheduling the callback over and over until a messagge is received, possibly with some timeout to avoid using 100% of the CPU.

> Is this really the only approach? Using something like a Waker would be a lot cleaner and would allow executing the callback right when the message is received.

As I see, neovim uses libuv that has quite rich api.
I would try the following options:
- Run blocking code in libuv threadpool (using `vim.loop.new_work`). This maybe be not suitable if LuaVM recreated every time in a thread.
- Create a file descriptor and use libuv poll() handler to poll it for read/write readines. So on rust side you need to write data to the descriptor.
- Use  a signal handler (eg for `SIGUSR2`) as an indicator of readiness. 
- Use pipes

Generic idea is to send a singal in the thread recognizable to libuv as an indicator or readiness:
```rust
    let _ = std::thread::spawn(move ||
        // Every once in a while a new message will be sent.
        loop {
            let name = if i % 2 == 0 { "John" } else { "Mary" };
            tx.send(name.into()).unwrap();
            // -------
            send_signal(); /// <--- send singal to libuv
            // -------
            i += 1;
            std::thread::sleep(std::time::Duration::from_secs(1));
        }
    );
```
Using of coroutines is not coroutines in this case I think.

**Comment by noib3** [comment]
I wanted to use tokio as a threadpool instead of using libuv's `vim.loop.new_york` as it handles concurrency as well as parallelism. Using signals might be a viable solutions, even though using `SIGUSR1/2` would mean my plugin wouldn't work on Windows.

Btw, are signals potentially slow because they involve a syscall? Also, is there a way to handle the signal code in Rust, say with something like
```rust
let signal = lua
    .globals()
    .get::<_, Table>("vim")?
    .get::<_, Table>("loop")?
    .get::<_, Function>("new_signal")?
    .call::<_, AnyUserData>(())?;

let callback = lua.create_function(|_lua, ()| Ok(()))?;

// Somehow doing
signal.start("sigusr2", callback);

**Comment by khvzak** [comment]
Actually I would recommend you to try pipes instead of signals. Signals are slow and not the best choice because they interrupts all syscalls (caller would get `EINTR`). 

This is a full example of module that uses a pipe and when loaded to neovim will print "John"/"Mary".

```rust
#[mlua::lua_module]
fn my_module(lua: &Lua) -> Result<Value> {
    let (tx, rx) = std::sync::mpsc::channel::<String>();
    let (pipe_r, mut pipe_w) = os_pipe::pipe()?;

    let mut i = 0;
    std::thread::spawn(move ||
        // Every once in a while a new message will be sent.
        loop {
            let name = if i % 2 == 0 { "John" } else { "Mary" };
            tx.send(name.into()).unwrap();
            pipe_w.write_all(&[b'1']).unwrap(); // send signal to neovim
            i += 1;
            std::thread::sleep(std::time::Duration::from_secs(1));
        });

    let recv = lua.create_function(move |lua, ()| {
        if let Ok(name) = rx.try_recv() {
            lua.globals().get::<_, Function>("print")?.call(name)?;
        }
        Ok(())
    })?;

    let read_fd = pipe_r.into_raw_fd();
    lua.load(chunk! {
        local read_pipe = vim.loop.new_pipe()
        read_pipe:open($read_fd)
        read_pipe:read_start(function(err, chunk)
            assert(not err, err)
            $recv()
        end)
    })
    .exec()?;

    Ok(Value::Boolean(true))
}
```

**Comment by noib3** [comment]
Thanks a lot, works great!
