### ISSUE TITLE
feature request: `create_function_once`

### ISSUE THREAD

**Issue by noib3** [khvzak/mlua#146]
We already have `Lua::create_function` and `Lua::create_function_mut` for `Fn` and `FnMut` closures respectively. Would it be possible to add a `Lua::create_function_once` for `FnOnce` closures that returns a runtime error if called more than once?

**Comment by khvzak** [comment]
I'm not really sure about possible use cases and how popular such functionality would be.
It sounds quite exotic.
For a single usecase/project this can be simply emulated with few lines of code.

**Comment by noib3** [comment]
> For a single usecase/project this can be simply emulated with few lines of code

Can you write an example?

**Comment by khvzak** [comment]
```rust
let lua = Lua::new();

fn create_function_once(lua: &Lua, f: impl FnOnce() + 'static) -> LuaResult<LuaFunction> {
    let mut f = Some(f);
    lua.create_function_mut(move |_, ()| match f.take() {
        Some(f) => Ok(f()),
        None => Err(LuaError::RuntimeError(
            "function cannot be called more than once".into(),
        )),
    })
}

let once = create_function_once(&lua, || println!("hello"))?;
once.call::<_, ()>(()).unwrap();
once.call::<_, ()>(()).unwrap(); // Error
```

**Comment by noib3** [comment]
ah, nice workaround
