### ISSUE TITLE
How about `impl ToLua for dyn Serialize` and `impl FromLua for dyn Deserialize`?

### ISSUE THREAD

**Issue by rise0chen** [khvzak/mlua#152]

**Comment by khvzak** [comment]
`serde::Serialize` and `serde::Deserialize` cannot be `dyn`.

**Comment by rise0chen** [comment]
yes, `serde::Serialize` and `serde::Deserialize` is not [Object Safety](https://doc.rust-lang.org/reference/items/traits.html#object-safety)

**Comment by rise0chen** [comment]
```rust
pub struct CompatSerialize<T: Serialize>(T);
impl<'lua, T: Serialize> ToLua<'lua> for CompatSerialize<T> {
    fn to_lua(self, lua: &'lua Lua) -> Result<Value<'lua>> {
        let serializer = Serializer::new(lua);
        self.0.serialize(serializer).map_err(|_|Error::ToLuaConversionError{from:"",to:"", message:None})
    }
}
```

**Comment by khvzak** [comment]
I'm not sure that I got your request.
You're free to implement `ToLua`/`FromLua` for your types.

**Comment by rise0chen** [comment]
```rust
fn fun<'lua>(lua: &'lua Lua, arg: StructB) -> LuaResult<StructA> {
    ...
}
lua.create_function(fun)
```
`StructA` and `StructB` had impl `Serialize` and `Deserialize`. I think it can auto impl `ToLua` and `FromLua`.

**Comment by khvzak** [comment]
I’m afraid they cannot. Blanket implementation is already taken by `T where T: UserData`

**Comment by rise0chen** [comment]
I hope convert Struct to `LuaTable` rather than `UserData`
