### ISSUE TITLE
Any way to pass a function pointer over to Lua?

### ISSUE THREAD

**Issue by Calandiel** [khvzak/mlua#157]
There's "create_function" but if I'm not mistaken that works by creating a callback through Lua's push API, which has significant overhead on LuaJIT compared to FFI function pointers. One could, of course, load them from a DLL but that's problematic when function pointers we're trying to load are in the executable that is hosting Lua.

**Comment by khvzak** [comment]
You can always use [`create_c_function`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_c_function) that has zero overhead.

**Comment by Calandiel** [comment]
Oh, interesting. I haven't seen this method before. It appears to be calling Lua's lua_pushcfunction and as such communicates with Lua's push API, like any other lua_CFunction (as per https://www.lua.org/manual/5.1/manual.html#lua_pushcfunction and https://www.lua.org/manual/5.1/manual.html#lua_CFunction ). Is that correct? In that case, *this* is the significant overhead I was talking about. In LuaJIT's case the jitter produces much faster code for FFI function pointers than for calls to C code through lua_CFunction.

<Sorry for a late reaction on my end, I wanted to read the source code of create_c_function before replying and I only just now found the time to pull mlua's>

**Comment by khvzak** [comment]
Then, I'm not really understood that this issue about.
The ffi module is available inside mlua and you free to use it to create function pointers, etc.

**Comment by Calandiel** [comment]
I'm going to close the issue, in retrospect, it was more suited for LuaJITs repo than this one. Apologies for polluting the board
