### ISSUE TITLE
meet a core dumped

### ISSUE THREAD

**Issue by Twinkle1087** [khvzak/mlua#16]
hello, I have met a coredump as following. Maybe it is because I have created to much userdatas. Do you have some idea? Thank you!

thread '<unnamed>' panicked at 'mlua internal error: cannot create a Lua reference, out of auxiliary stack space (this is a bug, please file an issue)', component/luaext/src/lua.rs:2104:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'mlua internal error: extra is poisoned (this is a bug, please file an issue): "PoisonError { inner: .. }"', component/luaext/src/lua.rs:1454:29
stack backtrace:
   0:     0x7f07ed6d14a5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f07ed6d14a5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f07ed6d14a5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f07ed6d14a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f07ed6f871c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f07ed6cb682 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x7f07ed6d3950 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f07ed6d3950 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f07ed6d3950 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x7f07ed6d369c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x7f07ed6d3f93 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x7f07ed6d3b8b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x7f07ed6f63a1 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  13:     0x7f07ed6f61c3 - core::option::expect_none_failed::h188f17af6c9f404b
                               at src/libcore/option.rs:1269
  14:     0x7f07ecaf7f51 - core::result::Result<T,E>::expect::h4cf2418c3e8bd2c0
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:963
  15:     0x7f07ecafeaee - ace_lua::lua::Lua::drop_ref::hd935e4db600d09c0
                               at component/luaext/src/lua.rs:1454
  16:     0x7f07ecb1571e - <ace_lua::types::LuaRef as core::ops::drop::Drop>::drop::h619b39f8a232d124
                               at component/luaext/src/types.rs:110
  17:     0x7f07ecb136de - core::ptr::drop_in_place::h9df41a43ab662568
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  18:     0x7f07ecb13aae - core::ptr::drop_in_place::ha5397b537a1a39c1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  19:     0x7f07ecb132a2 - core::ptr::drop_in_place::h785258ef8faacc0c
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  20:     0x7f07ecb1309b - core::ptr::drop_in_place::h6236c5a9aa1ef764
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  21:     0x7f07ecb144e2 - <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop::h4191162f6adbc1ab
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs:2423
  22:     0x7f07ecb14252 - core::ptr::drop_in_place::hf4ff8d7e5417ce91
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  23:     0x7f07ecb12a7e - core::ptr::drop_in_place::h2bfa4746821c31f8
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  24:     0x7f07ecacac79 - ace_lua::lua::Lua::create_callback::call_callback::{{closure}}::h2edc225d6e372c02
                               at component/luaext/src/lua.rs:1575
  25:     0x7f07ecab8675 - ace_lua::util::callback_error::{{closure}}::hd1b215439405bd26
                               at component/luaext/src/util.rs:416
  26:     0x7f07ecabac1b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::had2cbfd8f971a3a1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  27:     0x7f07ecb0d62d - std::panicking::try::do_call::h2d88971dae4041f1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  28:     0x7f07ecb0e6bd - __rust_try
  29:     0x7f07ecb0c4f5 - std::panicking::try::h8461a0ed33833dbb
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  30:     0x7f07ecabae2a - std::panic::catch_unwind::h1d0cc861e6836fc8
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  31:     0x7f07ecab4317 - ace_lua::util::callback_error::h0eaea63ccc78c9c4
                               at component/luaext/src/util.rs:416
  32:     0x7f07ecaff082 - ace_lua::lua::Lua::create_callback::call_callback::ha5ae2a32af06bace
                               at component/luaext/src/lua.rs:1545
  33:           0x41b736 - <unknown>
  34:     0x7f07ecae1375 - ace_lua::util::init_userdata_metatable::meta_index_impl::ha996786ee8aac20a
                               at component/luaext/src/util.rs:327
  35:           0x41b736 - <unknown>
  36:           0x40b100 - lua_pcall
  37:     0x7f07ecb206f8 - ace_lua::function::Function::call::h38687ef803d6db9b
                               at component/luaext/src/function.rs:76
  38:     0x7f07eca88891 - ace_lua::luabind::object_wrapper::set_create_addr_func::{{closure}}::h3d35f1e41b2f3e18
                               at component/luaext/src/luabind/object_wrapper.rs:132
  39:     0x7f07ecd2f9c4 - libobjserv::txn::coordinator::Coordinator::create_object::h28d5f32055b9a30b
                               at objserv/src/txn/coordinator.rs:588
  40:     0x7f07ecc4e7c1 - libobjserv::proxy::txn_global_proxy::TxnGlobalProxy::create_object::hc0116bdfc27d4c69
                               at objserv/src/proxy/txn_global_proxy.rs:19
  41:     0x7f07ecaf2125 - ace_lua::luabind::object_proxy_wrapper::global_create_object::h73b3e65abbed5b40
                               at component/luaext/src/luabind/object_proxy_wrapper.rs:114
  42:     0x7f07ecb0fd39 - core::ops::function::Fn::call::h9fc8867d178fbb90
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:72
  43:     0x7f07ecabe992 - ace_lua::lua::Lua::create_function::{{closure}}::hbd7101109b94417e
                               at component/luaext/src/lua.rs:852
  44:     0x7f07eca94744 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h42685aeb59d5cd73
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1095
  45:     0x7f07ecaca5cb - ace_lua::lua::Lua::create_callback::call_callback::{{closure}}::h2edc225d6e372c02
                               at component/luaext/src/lua.rs:1566
  46:     0x7f07ecab8675 - ace_lua::util::callback_error::{{closure}}::hd1b215439405bd26
                               at component/luaext/src/util.rs:416
  47:     0x7f07ecabac1b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::had2cbfd8f971a3a1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  48:     0x7f07ecb0d62d - std::panicking::try::do_call::h2d88971dae4041f1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  49:     0x7f07ecb0e6bd - __rust_try
  50:     0x7f07ecb0c4f5 - std::panicking::try::h8461a0ed33833dbb
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  51:     0x7f07ecabae2a - std::panic::catch_unwind::h1d0cc861e6836fc8
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  52:     0x7f07ecab4317 - ace_lua::util::callback_error::h0eaea63ccc78c9c4
                               at component/luaext/src/util.rs:416
  53:     0x7f07ecaff082 - ace_lua::lua::Lua::create_callback::call_callback::ha5ae2a32af06bace
                               at component/luaext/src/lua.rs:1545
  54:           0x41b736 - <unknown>
  55:           0x40b100 - lua_pcall
  56:     0x7f07ecb228e9 - ace_lua::function::Function::call::hcc55091a5af7731a
                               at component/luaext/src/function.rs:76
  57:     0x7f07ecafb4ff - ace_lua::luabind::global_wrapper::global_register_root_transaction::{{closure}}::h429bae576c621b10
                               at component/luaext/src/luabind/global_wrapper.rs:29
  58:     0x7f07ecb6175f - libobjserv::txn::transaction_manager::TransactionManager::start_root_transaction::{{closure}}::hd876b3012dca3fb7
                               at objserv/src/txn/transaction_manager.rs:159
  59:     0x7f07ecb3e958 - libobjserv::txn::transaction::Transaction::run::h298c91517bcb4b40
                               at objserv/src/txn/transaction.rs:289
  60:     0x7f07ecdfa1a3 - libobjserv::txn::txn_execute::start_transaction::{{closure}}::hebe34dd80880b353
                               at objserv/src/txn/txn_execute.rs:72
  61:     0x7f07ecc87649 - core::ops::function::FnOnce::call_once::h22d2bb6a6dcabe5c
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:233
  62:     0x7f07ecc867be - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc77f51f7dbda7d96
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:233
  63:     0x7f07ed54f9e8 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7752ffb74ed63146
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  64:     0x7f07ed07f074 - ace_execute::timer::ExecuteManager::process::hf06db2fe966532c5
                               at component/execute/src/timer.rs:79
  65:     0x7f07ecb60c2f - libobjserv::txn::txn_execute::TxnExecuteManager::update::h5e215d161b9ace28
                               at objserv/src/txn/txn_execute.rs:41
  66:     0x7f07ecb603f1 - libobjserv::server::server::Server::update::h49e556cbfd3b888f
                               at objserv/src/server/server.rs:88
  67:     0x7f07ecaf366a - ace_lua::luabind::global_wrapper::global_update::hac6823f7c43e7aab
                               at component/luaext/src/luabind/global_wrapper.rs:67
  68:     0x7f07ecb0feaf - core::ops::function::Fn::call::he9f51a367db42a32
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:72
  69:     0x7f07ecabe07a - ace_lua::lua::Lua::create_function::{{closure}}::ha068ef3854d4b54f
                               at component/luaext/src/lua.rs:852
  70:     0x7f07eca94744 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h42685aeb59d5cd73
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1095
  71:     0x7f07ecaca5cb - ace_lua::lua::Lua::create_callback::call_callback::{{closure}}::h2edc225d6e372c02
                               at component/luaext/src/lua.rs:1566
  72:     0x7f07ecab8675 - ace_lua::util::callback_error::{{closure}}::hd1b215439405bd26
                               at component/luaext/src/util.rs:416
  73:     0x7f07ecabac1b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::had2cbfd8f971a3a1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  74:     0x7f07ecb0d62d - std::panicking::try::do_call::h2d88971dae4041f1
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  75:     0x7f07ecb0e6bd - __rust_try
  76:     0x7f07ecb0c4f5 - std::panicking::try::h8461a0ed33833dbb
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  77:     0x7f07ecabae2a - std::panic::catch_unwind::h1d0cc861e6836fc8
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  78:     0x7f07ecab4317 - ace_lua::util::callback_error::h0eaea63ccc78c9c4
                               at component/luaext/src/util.rs:416
  79:     0x7f07ecaff082 - ace_lua::lua::Lua::create_callback::call_callback::ha5ae2a32af06bace
                               at component/luaext/src/lua.rs:1545
  80:           0x41b736 - <unknown>
  81:           0x40b100 - lua_pcall
  82:           0x403ccc - <unknown>
  83:           0x404abe - <unknown>
  84:           0x41b736 - <unknown>
  85:           0x40b17a - lua_cpcall
  86:           0x403804 - main
  87:     0x7f07edd10830 - __libc_start_main
  88:           0x403879 - _start
  89:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)

**Comment by khvzak** [comment]
Thanks for the bug report!
The error message `cannot create a Lua reference, out of auxiliary stack space` is a result of unsuccessful [`lua_checkstack`](https://www.lua.org/manual/5.3/manual.html#lua_checkstack) call and means that Lua was unable to double the stack size for the auxiliary thread to store references.
The max stack size is defined in [`luaconf.h`](https://www.lua.org/source/5.3/luaconf.h.html#LUAI_MAXSTACK) and by default is 1,000,000.

Probably if you need to store lots of references,  you can compile a custom Lua version with increased stack size.
Additionally, I think the default behaviour to always double the stack size could be changed to increase, let's say to +50% after some threshold.

**Comment by Twinkle1087** [comment]
thanks for your help!
The problem was fixed. I created too many userdatas, and each userdata contains a LuaTable(the code is just like this
pub(crate) struct ObjectProxyWrapper<'a> {
    pub object_proxy: *mut TxnObjectProxy,
    pub lua_table: LuaTable<'a>,
}
)
So the ref stack was exhausted.
Instead, I stored the ref of the table, and fix the problem.
