### ISSUE TITLE
lua how to requre dll

### ISSUE THREAD

**Issue by leiguoqiang** [khvzak/mlua#160]
I want to integrate idea debugging tools in Lua, but MLUa does not seem to support loading external DLLS for use, here is the sample code:
`package.cpath = package.cpath .. ';C:/Users/UserData/AppData/Roaming/JetBrains/IntelliJIdea2021.2/plugins/EmmyLua/classes/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966)//emmy_core crash
`

**Comment by khvzak** [comment]
From the [`doc`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.unsafe_new) you need to use `Lua::new_unsafe` to load DLLs

**Comment by leiguoqiang** [comment]
> From the [`doc`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.unsafe_new) you need to use `Lua::new_unsafe` to load DLLs

Even though use Lua::new_unsafe, it's still not possible to use loaded DLLS in Lua. Integrating Lua debugging tools (such as EmmyLua) is what most projects need to do.It would be nice to provide a working example.Here is my simple sample code

[TestLua.zip](https://github.com/khvzak/mlua/files/8660328/TestLua.zip)
[LuaTestFiles.zip](https://github.com/khvzak/mlua/files/8660338/LuaTestFiles.zip)

**Comment by lenscas** [comment]
What is the error that you receive? Are you sure that the c library you load is compatible with the version of lua that you let mlua run? Did you enable the debug module on mlua's side? (At least, I would imagine a debugger needs access to that)

There are also debuggers written entirely in lua, do those work?
