### ISSUE TITLE
expose some way to detect cycles when traversing tables

### ISSUE THREAD

**Issue by wez** [khvzak/mlua#165]
In wezterm, there is a lua repl that can be used to print values.
If someone tries to `print(_G)` then a simplistic recursive Value wrapper/printer will overflow its stack, because `_G._G = _G`.

Can we have some way to expose the index from the internal `LuaRef` inside the `Table` type so that a recursive printer can defend against this by eg: using a `HashSet<c_int>` to track visited tables?

**Comment by khvzak** [comment]
> Can we have some way to expose the index from the internal LuaRef inside the Table type so that a recursive printer can defend against this by eg: using a HashSet<c_int> to track visited tables?

The index inside LuaRef is not a constant, same table can have multiple indexes. Best way would be using `lua_topointer` as it uniq per table.

Also, this method is used in Lua deserializer to support detection of recursive table.

I can add `to_pointer` method just seems would be better to add it to `Value` than only `Table`, to cover more use cases.

**Comment by wez** [comment]
Thanks!
