### ISSUE TITLE
How to pass a raw `LuaRef::index` to a C function

### ISSUE THREAD

**Issue by noib3** [khvzak/mlua#167]
I'm [working on a crate](https://github.com/noib3/nvim-oxi) that provides Rust bindings to the Neovim C api via ffi. Many functions, like for example [`nvim_buf_call`](https://github.com/neovim/neovim/blob/4b4643be07e4e9259b3cb05e511e5047778733c1/src/nvim/api/buffer.c#L1358)

```C
Object nvim_buf_call(Buffer buffer, LuaRef fun, Error *err) {..}
```
take a `LuaRef` as parameter to accept a Lua function. Neovim's `LuaRef` [is just a type alias](https://github.com/neovim/neovim/blob/4b4643be07e4e9259b3cb05e511e5047778733c1/src/nvim/types.h#L23) for an `int`, and I believe should be the same as the `index` field of [mlua::LuaRef](https://github.com/khvzak/mlua/blob/bcf2cbea3798504471d88345327671bf2da7e8e1/src/types.rs#L151).

What I'd like to do is accept Rust closures in the public api and convert them to `LuaRef`s internally, a lot like `Lua::create_function` and `Lua::create_function_mut` do, i.e.

```rust
pub fn nvim_buf_call<A: From<Object>, F: FnMut() -> A + 'static>(buffer: Buffer, fun: F) -> Result<A> {
    let luaref = closures_to_luarefs(fun);
    // rest..
}
```

My question is: is it possible to reuse the code in this crate to implement something like that `closures_to_luarefs` function? My first guess would be something like (ignoring closure parameters and return values for now):

```rust
fn closures_to_luarefs<F: FnMut() + 'static>(fun: F) -> libc::c_int {
    let lua = mlua::Lua::new();
    let func = lua.create_function_mut(|lua, ()| Ok(fun())).unwrap();
    func.0.index // not possible, members are private
}
```

**Comment by khvzak** [comment]
More important question is where object under this `index` stored.
mlua uses internal `LuaRef` type where an integer `index` refers to a position inside a special "reference thread" (created and managed by mlua).
This index is only valid when used within this thread and invalid everywhere else.
So I'm afraid it's a impossible solution. Also it's not clear to which thread the nvim's LuaRef belongs to.

In Lua each thread has own execution stack and index is a position inside a stack, like an index inside array. And two differents arrays can store different elements under index "0".

**Comment by khvzak** [comment]
As I see nvim uses [`nlua_call_ref`](https://github.com/neovim/neovim/blob/b96037e42de42b504dd6f02d03de608d1b2a32c5/src/nvim/lua/executor.c#L1352) to call Lua functions by index. And they use [`global_lstate`](https://github.com/neovim/neovim/blob/b96037e42de42b504dd6f02d03de608d1b2a32c5/src/nvim/lua/executor.c#L47) to store functions.

**Comment by noib3** [comment]
> So I'm afraid it's a impossible solution. Also it's not clear to which thread the nvim's LuaRef belongs to.

Neovim is single threaded, so that LuaRef is probably an index to the Lua stack in the main UI thread.

I believe it should be possible because that function gets exported as a Lua function in `vim.api.nvim_buf_call`, and this code works just fine
```rust
let nvim_buf_call: mlua::Function = todo!(); // not important
let fun = lua.create_function(|_lua, ()| Ok(println!("hi"))).unwrap();
nvim_buf_call.call::<_, ()>((0, fun)).unwrap();
```

> you need to get access to internal nvim Lua state

Yep, although I'm not sure if/how it's possible.

**Comment by khvzak** [comment]
> Neovim is single threaded, so that LuaRef is probably an index to the Lua stack in the main UI thread.

Do you mean OS thread? It's true, but neovim should use many Lua threads (coroutines, that are not the same as OS threads) as it provides intergration with libuv.
Also each Lua function call gets a fresh stack and independent index space. Ie. index=1 inside function `a()` and index=1 inside `b()` refers to different objects despite belonging to the same (main) Lua thread.

The code above works fine because mlua takes care of it. Under the hood when you call
```rust
nvim_buf_call.call::<_, ()>((0, fun)).unwrap();
```
mlua translates internal LuaRef indexes to indexes required for call via [`lua_xmove`](https://www.lua.org/manual/5.1/manual.html#lua_xmove) function. This is important because Lua APIs are context-dependant. `lua_State*` argument can belong to a different lua threads inside single VM instance. You can create as many states as you want via [`lua_newthread`](https://www.lua.org/manual/5.1/manual.html#lua_newthread) and change environment variables or even replace globals table inside them. 

> Yep, although I'm not sure if/how it's possible.

It's declared as `static lua_State *global_lstate = NULL;` so it's private and you cannot link to :( 


Does nvim provide APIs to create functions and getting LuaRef?

**Comment by noib3** [comment]
Forgive my ignorance, but if the `lua_State*` that Neovim uses is private why does using `lua_xmove` work? It takes two `lua_State*`s as arguments, but I imagine neither of those are Neovim's `lua_State*`?

> Does nvim provide APIs to create functions and getting LuaRef?

I've been looking in [`executor.c`](https://github.com/neovim/neovim/blob/4b4643be07e4e9259b3cb05e511e5047778733c1/src/nvim/lua/executor.c) for such a function, but I believe it doesn't exist :(

**Comment by khvzak** [comment]
> Forgive my ignorance, but if the lua_State* that Neovim uses is private why does using lua_xmove work? It takes two lua_State*s as arguments, but I imagine neither of those are Neovim's lua_State*?

Only matters that they are childs to the same Lua VM instance created via [`lua_newstate`](https://www.lua.org/manual/5.1/manual.html#lua_newstate). And this is what neovim keeps internal from C API.

Also from the perspective of Lua that state is part public interface. When you execute Lua code like:
```lua
require("mlua_module")
```
Lua loads this module and calls function `luaopen_mlua_module` with `lua_State*` argument that hidden by neovim in C API. 
So when you load mlua module inside neovim it perfectly sees the main Lua VM instance and manipulate it to register additional internal threads/states to track own LuaRef system.

Unfortunately neovim provide  only `nvim_exec_lua` public call that be used only to load a separate dynamic library (mlua or plain C)

**Comment by noib3** [comment]
> You can get access to neovim lua_State* from Lua module loaded by neovim as it's part of public C/Lua interface

Ahhh, that's interesting. I wonder if I could use that to store a handle as `*mut lua_State` in Rust.

I'd like to avoid using `#[mlua::lua_module]` since that's going to give me a `&Lua`, and I'd have to deal with lifetime issues.

**Comment by khvzak** [comment]
> Ahhh, that's interesting. I wonder if I could use that to store a handle as *mut lua_State in Rust.

You can get raw `*mut lua_State` in mlua too:
```
    unsafe extern "C" fn get_raw_state(state: *mut mlua::lua_State) -> std::os::raw::c_int {
        println!("raw lua state: {:p}", state);
        0
    }

    unsafe {
        lua.create_c_function(get_raw_state)?.call(())?;
    }
```

> I'd have to deal with lifetime issues

Is this the only trouble? I work on experimental mlua version without `'lua` lifetime, but not sure how it's relevant.

**Comment by noib3** [comment]
Following your advice on how to get access to Neovim's `lua_State` I got a basic version of this to work.

Neovim uses [`nlua_call_ref`](https://github.com/neovim/neovim/blob/e5490b38b720d04a3361fd83f50099f3a71dd6c1/src/nvim/lua/executor.c#L1352) to handle `LuaRef`s, which in turn calls [`nlua_pushref`](https://github.com/neovim/neovim/blob/e5490b38b720d04a3361fd83f50099f3a71dd6c1/src/nvim/lua/executor.c#L1110), which finally just calls `lua_rawgeti` with `LUA_REGISTRYINDEX` and the original `LuaRef` as arguments. So I just needed to push a C function on the stack and call `lua_rawseti` to get a basic version to work, which is what I did [here](https://github.com/noib3/nvim-oxi/blob/ecaa89931665e1de09466f2b5dca14624791a18e/nvim-oxi/src/api/buffer/buffer.rs#L48):

I'm still not sure what index I should use when calling `lua_rawseti` (just using the arbitrary value of 1000 for now) or how to handle Rust closures instead of simple `extern "C"` function pointers, but I think I can close this. Thanks for the help :)

**Comment by khvzak** [comment]
Glad you solved it!
You can store Box'ed Rust callback as upvalue for a C closure using `lua_pushcclosure `.

You just need to be extra cautious when working with raw Lua state and handling exceptions. If Lua does longjmp (generate an exception) across Rust stack frames, this would not trigger stack unwinding and executing Drops. Also Rust panics should not cross ffi boundary.
