### ISSUE TITLE
Types and functions is inaccessible (lua53)

### ISSUE THREAD

**Issue by Zymlex** [khvzak/mlua#17]
`mlua::ffi::lauxlib::luaL_Reg` is inaccessible.  

![изображение](https://user-images.githubusercontent.com/25817412/94785956-b7d4d300-0413-11eb-8f79-360ac9ada123.png)

**Comment by Zymlex** [comment]
`mlua::ffi::luaL_Reg` is same.
![изображение](https://user-images.githubusercontent.com/25817412/94789313-1c922c80-0418-11eb-95ca-d6202fae917d.png)

**Comment by Zymlex** [comment]
lua_createtable and many others are also unavailable.
![изображение](https://user-images.githubusercontent.com/25817412/94794968-06886a00-0420-11eb-914e-ae9dd1e063cd.png)

**Comment by khvzak** [comment]
`mlua` goal is to provide a high-level (safe) api, wheres functions from the private `ffi` module are low-level and very unsafe.

Could you please provide an example how you wanted to use the `luaL_Reg`  struct?

**Comment by Zymlex** [comment]
> `mlua` goal is to provide a high-level (safe) api, wheres functions from the private `ffi` module are low-level and very unsafe.

Would like to have and regular access, like `winapi` crate.
> Could you please provide an example how you wanted to use the `luaL_Reg` struct?
I need an analog:
```C++
static struct luaL_reg ls_lib[] =
{
        { "TestFunc", forLua_TestFunc },
        { NULL, NULL }
};
```

**Comment by Zymlex** [comment]
No longer required, you can close.
