### ISSUE TITLE
[Question] How to package a userdata lib for mlua?

### ISSUE THREAD

**Issue by benwilber** [khvzak/mlua#172]
I have a small lib for mlua that encodes/decodes JSON

https://github.com/benwilber/mlua-userdata-json

I would like to know how to package this lib so that it doesn't require a specific mlua Lua version (feature)?

Ideally someone could just add to their dependencies:

```
mlua  = "whatever"
mlua-userdata-json = "1.5.5"
```

I'm still just experimenting with it so open to suggestions!

**Comment by khvzak** [comment]
You could add something like: `mlua = "*"` OR `mlua = ">= 0.7.4, < 1.0.0"`
It should be easier after releasing mlua 1.0 with stable api
