### ISSUE TITLE
[Question] Do UserData MetaTables get cached 

### ISSUE THREAD

**Issue by makspll** [khvzak/mlua#175]
As in title,

I believe that `add_methods` is called via:
[`UserData::to_lua`](https://docs.rs/mlua/latest/src/mlua/conversion.rs.html#141)
[`Lua::create_userdata`](https://github.com/khvzak/mlua/blob/d9ac7abff2d605f8345657b1625eb3e2de02ddd8/src/lua.rs#L1720)
[`Lua::make_userdata`](https://github.com/khvzak/mlua/blob/d9ac7abff2d605f8345657b1625eb3e2de02ddd8/src/lua.rs#L2805)
 [`Lua::push_userdata_meta`](https://github.com/khvzak/mlua/blob/d9ac7abff2d605f8345657b1625eb3e2de02ddd8/src/lua.rs#L2402)

And it seems that this is called every time a UserData is created, Is this correct? Or are there any mechanisms which cache in any way the creation of UserData?

**Comment by makspll** [comment]
Ahh, I am blind..

Yup that's clear!

**Comment by khvzak** [comment]
Currently the fact that metatables are shared among all instances of type`T` is mentioned  in [`AnyUserData::get_metatable`](https://docs.rs/mlua/latest/mlua/struct.AnyUserData.html#method.get_metatable) 

I'll mention this fact in `Lua::create_userdata` too

**Comment by lenscas** [comment]
Awesome. Means I am not relying on an implementation detail. Thanks!

**Comment by khvzak** [comment]
Performance is always top priority for me, so I added many optimizations. Metatables caching is the most obvious, it was inherited from rlua.
However, compared to rlua, mlua is about 30-50% faster (and do much less memory allocations).

**Comment by lenscas** [comment]
In tealr, I added a simple way to add documentation to a method, but to make that api nice to work with it ended up doing quite a bit of allocation.

So, that is why I am happy to know that they are being cached :)
