### ISSUE TITLE
Error: Must use luaL_newstate() for 64 bit target

### ISSUE THREAD

**Issue by zh-jq** [khvzak/mlua#176]
I got this erorr when linking with system default installed luajit.
The feature check for luaL_newstate is removed in commit [Always use Rust allocator for Lua 5.1/u](https://github.com/khvzak/mlua/commit/b065db37c2dd9e9c1d5483509bbd1bcc355f4fef#diff-10f3d95239fccd00ca32dd3cfd6386a0e727c3d30d7a008606e2f8bea731cf16L449)
Can we revert that?

**Comment by zh-jq** [comment]
> What LuaJIT version you have?
2.1.0-beta3

**Comment by khvzak** [comment]
I see, seems it's 5 years old LuaJIT version without latest changes from the [official repo](https://github.com/LuaJIT/LuaJIT).
Then I'll disable custom allocator for non-vendored LuaJIT libs.
