### ISSUE TITLE
Unexpected block of runtime (tokio)

### ISSUE THREAD

**Issue by kkharji** [khvzak/mlua#177]
Dear @khvzak, Thanks again for making mlua, I'm starting to use it more but I ran into an odd issue that I couldn't quite understand what the issue is. I'm using tokio.

At first I got errors regarding yield across C, and I solved that by creating the following helper function

```rust
pub async fn spawn<F: Future>(future: F) -> F::Output {
    tokio::task::LocalSet::new()
        .run_until(async move { RUNTIME.block_on(future) })
        .await
}
```

And so I wrapped all my top level function to run here.

Now, the blocking part, the first part is a function that produces a async stream
```rust
pub async fn stream_logs(log_task: &LoggingTask) -> Result<ProcessStream> {
    let mut lines = linemux::MuxedLines::new()?;
    lines.add_file(&log_task.path).await?;
    Ok(stream! {
        while let Ok(Some(item)) = lines.next_line().await {
            let line = item.line();
            if let Ok(value) = serde_json::from_str::<ProcessItem>(&line){
                if value == ProcessItem::Output("-LOGCLOSED-".into()) {
                    break;
                }
                yield value
            }
        }
    }
    .boxed())

```

However, with the the spawn helper I'm running the following which blocks 
```rust
tokio::task::spawn_local(async {
            let mut state = state(lua).await?;
            state.buffer.extend_tasks(log_tasks);
            for task in state.buffer.tasks_mut().iter_mut() {
                let mut stream = stream_logs(task).await?;
                while let Some(output) = stream.next().await {
                    lua.info(output.to_string())?;
                }
                // });
            }
            Ok::<_, Error>(())
        })
        .await??;
````

I thought maybe my it's blocking on stream.next(), but turned out it tokio::task::spawn_local with empty closure is within it self blocking

So next, I tried doing without, and yes that blocks too. 

the stream takes a long time to run because it reads from a file for a long time. my end goal is to run the stream in non blocking way for a long time in my neovim runtime

Any suggestions or ideas. 

Thanks

**Comment by khvzak** [comment]
Looks like the problem is with the helper.

Probably the following variant should work better:
```rust
pub async fn spawn<F: Future>(future: F) -> F::Output {
    tokio::task::LocalSet::new().run_until(future).await
}
```
But it's hard to say without seeing the codebase. Is your app uses a module mode, or is it standalone?

**Comment by tami5** [comment]
Hey @khvzak , I endup doing a hack you've written is some other issue. https://github.com/xbase-lab/xbase/blob/ref/nvim/move_all_logic_into_editor_crate/client/src/neovim/listener.rs#L53-L71
