### ISSUE TITLE
Lack of abstraction for static methods/data

### ISSUE THREAD

**Issue by makspll** [khvzak/mlua#178]
mlua has abstractions for:

- fields
- methods which work over references to self
- functions which still need an instance of the userdata to be called

There is one thing that doesn't come out of the box for mlua, and that is static methods/fields.

An implementation of this exists in a fork of mlua: https://github.com/sdleffler/hv-lua/blob/2b9cdd86fbd5cc0d6255176a822c1765bb07243c/src/userdata.rs#L683-L702

I often find myself defining entire UserData objects and exposing them as globals to scope static methods nicely. It would be very useful if this could be provided by mlua itself (and probably could be optimized better).

**Comment by lenscas** [comment]
for what it is worth, even in tealr there is currently a macro that could benefit from this as it would pretty severely reduce the amount of code that it needs to generate.

**Comment by khvzak** [comment]
> There is one thing that doesn't come out of the box for mlua, and that is static methods/fields.

Could you please provide an example (in Rust/Lua), how you would like to see it?

**Comment by makspll** [comment]
Of course!

the way it's done in hv_lua, I would love to see something like this added to `UserData`
```rust

impl UserData for Vec2{
  fn add_static_fields<'lua, F: UserDataFields<'lua, Self? >>(fields: &mut F){
          fields.add_field_method_get("my_static_constant", |_, this| Ok(69));
  }

  fn add_static_methods<'lua, F: UserDataMethods<'lua, Self?>>(methods: &mut M){
          methods.add_function("new", |_, (x,y): (f32,f32)| Ok(Vec::new(x,y)) )
  }
}
```
Now, I put question marks behind the Self arguments, since I am not sure about those implementation details. Self is probably not right since the static metatable would not be the same as the UserData's we are implementing. It may not make sense to allow adding methods (but only allow functions) depending on how this is implemented.

Then in lua I would like to be able to do something like:

```lua
local my_vec = Vec2.new(1,2)
print(my_vec) -- (1,2)

local my_constant = Vec2.my_static_constant
print(my_constant) -- 69
```

The way this is possible right now is of course through implementing a new `Vec2Globals` userdata object and setting `Vec2` to an instance of it. Ideally this is done by mlua itself since it's a common pattern to scope modules/functions like this, and since it's natural to have static methods in rust.

**Comment by lenscas** [comment]
> Anything else @lenscas ?

Nope, that is the good stuff :)

If I remember correctly the `Self` that you see back in hv_lua is actually a `Type<Self>` where `Type` is a struct that gets the various UserData implementations needed to get this to work.

**Comment by khvzak** [comment]
I'm not sure is it a good idea to automatically set `Vec2` global, since it can conflict with other global names.
If I correctly understand, you just need a "proxy object" with right metatable to call functions?

A sort of:
```rust
let proxy = lua.create_proxy();
proxy.set_metatable(MyUserData::metatable());
lua.globals.set("MyUserData", proxy);
```

Should be no difference between static functions and non-static function, since you always can create a function that does not take **self**:
```rust
    fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_function("new", |_lua, ()| Ok(Self()))
    }
```

**Comment by khvzak** [comment]
@makspll @lenscas 
please take a look at https://github.com/khvzak/mlua/pull/180

**Comment by makspll** [comment]
name conflict issues are definitely a valid concern, and yeah your approach shown here does seem to address both the need for the feature since it avoids implementing a proxy User Data manually and the said concern.

I've had some concerns but it looks like your implementation in #180 already tackles them, namely preventing access to 'instanced' data which is fantastic!  

My only remaining concern is this allows accessing statics the other way, i.e. via an instance. I don't think it's a problem though really.

So all in all that looks like a good solution, what do you think @lenscas  ?

**Comment by lenscas** [comment]
By the looks of it the API design is a bit different as the idea of having a separate method on the UserData trait to set "static" methods/fields is replaced by just automatically exposing methods/fields that don't need `Self` on the proxy.

I think I like this design more, despite the fact that you can't prevent "statics" from ending up on the instance.

**Comment by lenscas** [comment]
Its not a problem, I can see people wanting that flexibility but personally I like it more this way. The API is cleaner compared to having 2 extra methods just to register the statics.
