### ISSUE TITLE
Is it possible to implement ToLua for Result?

### ISSUE THREAD

**Issue by coderedart** [khvzak/mlua#182]
I have a type `T: UserData` and i was trying to return in a function like this
```rust
return Ok((T, Result<Option<T>, mlua::Error>))
```

`(T, Option<T>)` does work because UserData is impl for Option<T> if T: UserData. 
but `Result<T: UserData, mlua::Error>` doesn't work :(

I don't know if it is left out on purpose due to some limitation, but just wanted to ask it in any case. if this can't be done, is there any way i can use `MultiValue` for this smh?

**Comment by khvzak** [comment]
hm, could you show you code?
It works without any issues:
```rust
fn test<T: UserData + Copy>(_lua: &Lua, t: T) -> mlua::Result<(T, Result<Option<T>, mlua::Error>)> {
    return Ok((t, Ok(Some(t))));
}
```

**Comment by coderedart** [comment]
ah, its my bad. i used the wrong example i created userdata with T and tried to combine them both like 
```rust
let thing = Thing::new(); // Thing: UserData
let data = lua.create_userdata(thing.clone);
let data = data.map( |data|  Some(Value::UserData(data) ) ); // wrap the `AnyUserData` inside an Option<Value> which is not inside Result
Ok((ctx, data)) // won't work because data is Result, but will work if i unwrap() data
```

sorry about the confusion. spent a long time confused about how to deal with the static lifetime limitation of scope method, and after browsing through the issues to find the registry workout, i got really tired and posted the wrong description of my problem..

**Comment by khvzak** [comment]
So, is this still actual?
I tried combining `T` + `AnyUserData`, works fine:
```rust
fn test<T: UserData + Clone + 'static>(
    lua: &Lua,
    t: T,
) -> mlua::Result<(T, Result<Option<Value>, mlua::Error>)> {
    let data = lua.create_userdata(t.clone()).map(Value::UserData).map(Some);
    return Ok((t, data));
}
```

**Comment by coderedart** [comment]
omg, nvm. I'm dumb. the error seems to be from tealr rather than mlua. I just copy pasted the method to `impl mlua::UserData` and it works perfectly. but the same method inside `impl tealr::TealData` gives me error. I will lodge an issue on tealr repo and try to figure out why it happens. 

apologies for wasting your time :(
