### ISSUE TITLE
Add `add_field_method_get_mut` and `add_field_function_get_mut` for completeness

### ISSUE THREAD

**Issue by makspll** [khvzak/mlua#185]
I've found myself requiring this to get mutable pointers to parts of my data,

Without these I am forced to go back to using `Index` and `NewIndex` metamethods directly (unless I use UnsafeCell)

**Comment by khvzak** [comment]
`add_field_function_get_mut` probably does not make sense since it provides a generic `AnyUserData` in an argument.

> I've found myself requiring this to get mutable pointers to parts of my data,

You probably can achieve this by mutably borrowing `AnyUserData`:

```rust
fields.add_field_function_get("val", |_, ud| {
  let mut this = ud.borrow_mut::<Self>();
  ...
});
```

**Comment by makspll** [comment]
Fair enough if you don't think it makes sense,
I just thought it would nicely complete the interface, since you can achieve the same thing with the `Index` meta methods, I assumed fields are syntactic sugar extending these.
