### ISSUE TITLE
A way to uniform functions with tables and userdata with `__call`

### ISSUE THREAD

**Issue by hack3ric** [khvzak/mlua#191]
There are many use cases where you need to treat callable objects as function, especially when writing a library.

Maybe add a `{Table, AnyUserData}::into_function`, since `TableExt::call`'s implementation is just turning the table into function and then call it?

**Comment by khvzak** [comment]
I need to think about it. Not only `into_function` is needed, but apparenly a way to call functions/methods on arbitrary userdata.

**Comment by khvzak** [comment]
This is done, by the `AnyUserDataExt` trait
