### ISSUE TITLE
loading an empty string in luau results in an access violation in `luaL_loadbufferx` compat function

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [khvzak/mlua#200]
In the luau compatibility implementation of `luaL_loadbufferx` passing in an empty slice, as converted from an empty string, results in `Access violation reading location 0x00000001`. Users can circumvent this error by checking if the source being passed in is empty, but if this check is not implemented, end users can crash any application depending upon mlua-using-luau by simply attempting to compile an empty string.

**Comment by khvzak** [comment]
Fixed, thanks
