### ISSUE TITLE
Why is luau always compiled in release mode?

### ISSUE THREAD

**Issue by crwn1337** [khvzak/mlua#201]
Currently it takes me 3 minutes to compile luau from source (even in debug mode), if i remove `.opt_level(2)` from the `luau-src-rs` crate it takes it down to 15 seconds and if i enable the `parallel` feature for `cc`, it takes compile times down to just 5 seconds.
I don't see the need to build always in release mode and make compile times 36x longer.
(also there have been 5 updates to luau since the crate was last updated, it would be nice if it got updated)

**Comment by khvzak** [comment]
Fixed in https://github.com/khvzak/luau-src-rs/commit/62eec25de6e3f7157f9d112d35b49697f2439d84
You can enable `parallel` feature for `cc` in your crate and it should be inherited by luau-src.

**Comment by crwn1337** [comment]
thank you ❤️
