### ISSUE TITLE
Manual implementation of UserData to workaround orphan rules

### ISSUE THREAD

**Issue by coderedart** [khvzak/mlua#206]
I am trying to expose egui to lua plugins so that they can be used to script the gui functionality in my app. 

https://github.com/coderedart/luaegui (technically tealr bindings as i wanted easy docs like https://coderedart.github.io/luaegui/ )

Orphan rules forbid me from implementing the `UserData` trait on egui types. so, i am currently wrapping them all in a wrapper new type with the relevant `UserData` impls to convert between wrapper and original egui types. I need to call `.into()` almost in every single function of the api. hundreds of such calls seem like noise. 

egui dev does not want the lua bindings in the main repo. and it makes even less sense for them to be in mlua/tealr repos. but i cannot implement the `UserData` trait on egui types due to orphan rules. 

There's three ways to solve this issue:
1. maintain a fork of egui and impl lua bindings in the fork. publish it crates.io. update with upstream every now and then.
2. keep using wrapper newtypes by calling `.into` everywhere. 
3. ask `mlua` to expose a more manual registration of types/their functionality to the lua vm instead of the trait. 

I am here to try the third option  as that would also allow me to make bindings for other crates like wgpu easier in future.

1. instead of having a trait, i would like to manually register the types / functions to the VM at the start. 
```rust
let mut registrar = lua.register_type::<TextEdit>();
registrar.add_field();
registrar.add_method();
registrar.add_method_mut(); // and so on. either panic or overwrite when duplicate types / methods are registered.
```
2. weird hacks like [serde remote](https://serde.rs/remote-derive.html). 
3. something else?

**Comment by khvzak** [comment]
> instead of having a trait, i would like to manually register the types / functions to the VM at the start.

Are you referring to `UserData` implementation rather than `ToLua`/`FromLua`? As the last traits just converts to/from `mlua::Value`.
Manually registering a foreign types in VM is quite interesting idea! I need to think about it.
Is this what rhai provides? 

> weird hacks like [serde remote](https://serde.rs/remote-derive.html).

Will check it out too.

**Comment by coderedart** [comment]
> Are you referring to `UserData` implementation rather than `ToLua`/`FromLua`? As the last traits just converts to/from `mlua::Value`.

Ah, yes. i messed up :) I meant the `UserData` trait. 

>  Is this what rhai provides?

yep. https://docs.rs/rhai/latest/rhai/plugin/struct.Engine.html#method.register_type . 

it also has a simple register_fn which i think can also be useful for mlua. for a LOT of functions, we don't use the first `&Lua` argument and just forward to some inner function
example:
```rust
lua.register_type::<String>()
	.register_method_no_lua_no_args("len", String::len);
// the above is ideal. but instead we have to usually wrap with a lua signature compatible function
lua.register_type::<String>()
	.register_method("len", | _ , this, _| { this.len() }); 
```

**Comment by coderedart** [comment]
btw, is there a rough ETA for this issue/0.9? If it will take some time, i will temporarily work with the UserData trait and wrapper types in the meanwhile.

**Comment by khvzak** [comment]
I work on this feature now, but it's quite tricky! The problem is mostly building an organic API that co-exists with `UserData` trait and provides access to type registry.
Also I try to avoid re-inventing the `UserDataFields` and `UserDataMethods` traits used to register fields/methods.

**Comment by khvzak** [comment]
@coderedart  I added support of manually registering userdata types and creating object that do not implement `UserData` trait.

An example:
```rust
lua.register_userdata_type::<StdString>(|reg| {
    reg.add_method("get", |_, this, ()| Ok(this.clone()));
    reg.add_method_mut("concat", |_, this, s: String| {
        this.push_str(&s.to_string_lossy());
        Ok(())
    });
})?;

let ud = lua.create_any_userdata("hello".to_string())?;
assert_eq!(&*ud.borrow::<StdString>()?, "hello");

lua.globals().set("ud", ud)?;
lua.load(
    r#"
    assert(ud:get() == "hello")
    ud:concat(", world")
    assert(ud:get() == "hello, world")
"#,
)
.exec()
.unwrap();

```

Please check out the master branch. I'm open for feedback.

**Comment by coderedart** [comment]
how do i return a manually registered type?
```rust
struct UiMut<'ui> {
    ui: &'ui mut Ui,
}
fn register_ui_with_lua(lua: &Lua) {
    lua.register_userdata_type::<Response>(|reg| {
        reg.add_method("clicked", |_, res, _: ()| {
            Ok(res.clicked())
        });
    }).unwrap();
    lua.register_userdata_type::<UiMut>(|reg| {
        reg.add_method_mut("label", |_, ui, arg: String| {
            Ok(ui.ui.label(arg)) // error because response is 
        });
    })
    .unwrap();
    
}
```
````
error[E0277]: the trait bound `Response: LuaUserData` is not satisfied
   --> src/main.rs:82:13
    |
82  |         reg.add_method_mut("label", |_, ui, arg: String| {
    |             ^^^^^^^^^^^^^^ the trait `LuaUserData` is not implemented for `Response`
    |
    = help: the following other types implement trait `LuaUserData`:
              Arc<std::sync::Mutex<T>>
              Arc<std::sync::RwLock<T>>
              Rc<RefCell<T>>
    = note: required for `Response` to implement `IntoLua<'_>`
    = note: required for `Response` to implement `IntoLuaMulti<'_>`
note: required by a bound in `add_method_mut`
   --> /home/red/.cargo/git/checkouts/mlua-4fd10c345875f70c/47c8300/src/userdata.rs:260:12
    |
260 |         R: IntoLuaMulti<'lua>;
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `add_method_mut`
```

**Comment by khvzak** [comment]
> how do i return a manually registered type?

It's quite tricky. The `IntoLua` trait is implemented for `T: UserData` but Rust would not allow me to implement it for any `T` because of conflicting implementations. Keeping `T: UserData` is important to automatically register types from their trait definition.

> Scope also needs an equivalent of create_any_user_data though. because most of egui is dealing with borrowed types like &mut Ui

There is a big difference between `'static` and non-static types :( `TypeId` is implemented only for `'static`, so any custom types registration would not work for non-static types.
The only way I see how to solve it  - pass registration data together with instance creation.  

> Is there a way to create a &T inside lua when T is a registered type?
> if there was a scope.create_ref_userdata(&mut T) or lua.create_static_ref_userdata(&'static T), that can help a lot in these cases.

It should be possible, I'll take a look.

**Comment by khvzak** [comment]
@coderedart 
I added new experimental methods to scope: `create_userdata_ref` / `create_userdata_ref_mut` / `create_any_userdata_ref` / `create_any_userdata_ref_mut`.

Could you check the dev branch. Is this what you looking for?

**Comment by coderedart** [comment]
nice. this is what i wanted. makes creating an api much easier.
https://coderedart.github.io/egui_glow_glfw_emscripten/

**Comment by coderedart** [comment]
just realized that i register functions/methods, i can't take an argument which is of registered type because they don't impl UserData. is the recommended way to just take a LuaValue and manually match it?

**Comment by khvzak** [comment]
This would not work for `UserData` too, see commit 61c285746c82de927c1aeed1f465b828000a776f

```rust
impl<'lua, T: 'static + UserData + Clone> FromLua<'lua> for T
```
I believe was not the best idea because of `T: Clone`. 

Alternatively, I'm thinking about adding an accossor like:
```rust
reg.add_method_mut("button", |lua, ui, name: TypedUserData<WidgetText>| {
   ...
}
```

**Comment by khvzak** [comment]
@coderedart I added `UserDataRef` and `UserDataRefMut` for easier receiving userdata in functions/etc.

```rust
reg.add_method_mut("button", |lua, ui, name: UserDataRef<WidgetText>| {
    ...
}
```

**Comment by coderedart** [comment]
nice. that works. I will try to see how far i can go with this.
