### ISSUE TITLE
runtime error: attempt to yield from outside a coroutine

### ISSUE THREAD

**Issue by mrxiaozhuox** [khvzak/mlua#212]
When I try to use mlua create a async function for my lua plugin, it's not work:

![image](https://user-images.githubusercontent.com/41265098/195263708-f95030be-fa44-4b21-b970-329e72604532.png)
![image](https://user-images.githubusercontent.com/41265098/195263752-87484372-cfb4-4e9f-8c2f-a6c52667082f.png)
![image](https://user-images.githubusercontent.com/41265098/195263971-8fd67b71-e266-4859-a377-c6f1d5f10696.png)

**Comment by khvzak** [comment]
Would be easier to use synchronous function for this.
Async required runtime (eg: tokio) which is not trivial to use inside plugin (non-rust ecosystem).
