### ISSUE TITLE
Set env after compiling a chunk?

### ISSUE THREAD

**Issue by ColonelPhantom** [khvzak/mlua#218]
I would like to set an env after compiling a chunk, so that I can call a function in an isolated global state.

The use case I envision for this is a persistent server, that loads some state initially and then uses coroutines to service multiple requests. In order to prevent bugs due to global state, I would like to isolate these coroutines (not very strictly, the use case is not untrusted code but rather preventing accidental misuse).

With the C API I believe I would be able to handle this use case with `lua_setupvalue`. Could it also be possible within mlua?

I think I can also work around this by setting the `_ENV` global from within Lua, although IMO setting an upvalue is a lot nicer.

**Comment by khvzak** [comment]
Am I right that you're turning chunk into a function and after that want to attach an env?

Chunk has [`set_environment`](https://docs.rs/mlua/0.8.5/mlua/struct.Chunk.html#method.set_environment) function which allow to attach environment at the creation stage.

**Comment by ColonelPhantom** [comment]
> Am I right that you're turning chunk into a function and after that want to attach an env?

Yes. That way I can do the initial loading only once, and re-use the state it creates. After that, I can then call into some handler that was created by the initial setup and yet isolate these handlers.

I think this should be possible with `setupvalue` or `setfenv` after creating and calling the function already, or am I wrong and is this somehow unsound/not doing what I would expect?
