### ISSUE TITLE
Run lua(u) bytecode pre-compiled

### ISSUE THREAD

**Issue by walksanatora** [khvzak/mlua#223]
Small speed improvements for if you implement a part in Lua so it doesen't have to be reconverted to Lua bytecode everytime the program is ran

**Comment by khvzak** [comment]
Could you explain please?
mlua can compile Luau code to bytecode and then execute it. 
See [`Compiler`](https://docs.rs/mlua/0.8.6/mlua/struct.Compiler.html) and [`Lua::load`](https://docs.rs/mlua/0.8.6/mlua/struct.Lua.html#method.load) with binary [mode](https://docs.rs/mlua/0.8.6/mlua/struct.Chunk.html#method.set_mode).

**Comment by walksanatora** [comment]
sorry i didn't recognise that option when scanning the docs
