### ISSUE TITLE
Accessing the instance of a `UserData` when implementing a meta function?

### ISSUE THREAD

**Issue by grilme99** [khvzak/mlua#234]
Hi,

I'm trying to implement the `Index` metamethod on a `UserData` type to support "dynamic" fields. My use case is that I have a tree of nodes, and each Node has its own instance of a `Node` UserData. In Lua, I want to be able to access Node children via a simple index.

Example:
```lua
-- `script` is this object's Node
print(script.Foo.Name) -- Index `Foo` child and print the `Name` property of that Node.
```

As far as I can tell, the existing `add_meta_function` API does not allow you to access the instance of a `UserData` when handling the metamethod. This is in contrast to an API like `add_field_method_get`, which I've implemented as follows:

```rust
fields.add_field_method_get("Name", |_, instance| Ok(instance.name.to_owned()));
```

How should I achieve what I want, or is this behaviour not currently supported?

**Comment by grilme99** [comment]
I realized that `add_meta_method` should provide the functionality I want. However, I get a `userdata is not expected type` error when using it. For more context, a Node (`Instance`) is typed as follows:

```rust
pub type Instance = Rc<RefCell<InnerInstance>>;

#[derive(Debug, Clone)]
pub struct InnerInstance {
    pub name: String,
    pub instance_class: InstanceClass,
    pub sourcemap_node: SourcemapNode,
    pub parent: Option<Instance>,
}

impl InnerInstance {
    pub fn new(sourcemap_node: SourcemapNode, parent: Option<Instance>) -> Instance {
        // Returns an `InnerInstance` wrapped in an `Rc` and `RefCell`
        ...
    }
}

impl Userdata for InnerInstance {
    fn add_methods<'lua, M: mlua::UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_meta_method(MetaMethod::Index, |_, instance, child_name: AnyUserData| {
            // Unsure what type `child_name` should be?
            println!("{child_name:?}");

            Ok(())
        });
    }
}
...
```

With Luau code:
```lua
local foo = script.Foo
```

Error:
```
Error: callback error
stack traceback:
        [C]: in ?
        [string "__mlua_index"]:20: in ?
        [string "init"]:3: in ?
caused by: userdata is not expected type
```

**Comment by khvzak** [comment]
>  // Unsure what type `child_name` should be?
> println!("{child_name:?}");

`child_name` must be `String` and will be set to `Foo`.

To achieve `script.Foo.Name` for `Foo` you should return another userdata for this key and then Lua will call `Name` for it.

**Comment by grilme99** [comment]
I tried making `child_name` both a `String` and `mlua::Value`, and both produced the same error. I've also tried returning nothing, a string, and a UserData from the method. Is there a way to debug exactly what userdata it's tripping up on?

**Comment by khvzak** [comment]
A quick example:

```rust
use std::cell::RefCell;
use std::rc::Rc;
use std::collections::HashMap;

pub type Instance = Rc<RefCell<InnerInstance>>;

#[derive(Debug, Clone, Default)]
pub struct InnerInstance {
    pub name: String,
    pub childs: HashMap<String, Instance>,
}

impl mlua::UserData for InnerInstance {
    fn add_methods<'lua, M: mlua::UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_meta_method(mlua::MetaMethod::Index, |_, instance, child_name: String| {
            Ok(instance.childs.get(&child_name).cloned())
        });
    }

    fn add_fields<'lua, F: mlua::UserDataFields<'lua, Self>>(fields: &mut F) {
        fields.add_field_method_get("Name", |_, this| Ok(this.name.clone()));
    }
}

fn main() {
    let lua = mlua::Lua::new();

    let bar = InnerInstance { name: "bar".into(), ..Default::default() };
    let foo = Rc::new(RefCell::new(InnerInstance {
        name: "foo".into(),
        childs: HashMap::from_iter([("bar".to_string(), Rc::new(RefCell::new(bar)))]),
    }));

    lua.globals().set("foo", foo).unwrap();
    lua.load("
        print(foo.bar.Name)
    ").exec().unwrap();
}
```

works fine and prints `bar` to the console. 


Could you provide the full source code?

**Comment by grilme99** [comment]
Yeah, I've got no idea what's causing this to break. I stripped away as much as I could from the `Instance` UserData, and it still errored.

The source is available here: https://github.com/grilme99/rbx-cli/blob/main/src/luau/userdata/instance.rs.

**Comment by khvzak** [comment]
Could you provide an instruction how to reproduce the error?

**Comment by grilme99** [comment]
Just running the application linked above with `cargo run` will cause the error to happen. Beyond that, I'm not sure what the reproduction is.

**Comment by khvzak** [comment]
`cargo run` panics with error `Error: Failed to parse sourcemap`

**Comment by grilme99** [comment]
Oops, you also need to run `sh test-projects/generate_sourcemaps.sh`. I've still been unable to debug the issue here and am completely stumped.

**Comment by khvzak** [comment]
In the code

```
impl InnerInstance {
    pub fn new(sourcemap_node: SourcemapNode, parent: Option<Instance>) -> Instance {
        ...
        Rc::new(RefCell::new(Self {
            name,
            instance_class,
            sourcemap_node,
            parent,
        }))
    }
}
```

In method `InnerInstance ::new` you return `Rc<RefCell< InnerInstance >>`.
Later you wrap it again to the same type:
```
        let script_instance = InnerInstance::new(self.sourcemap.clone(), None);
        let script_instance = Rc::new(RefCell::new(script_instance));
```
The type of `script_instance` is `Rc<RefCell<Rc<RefCell< InnerInstance >>>>` which is not recognizable userdata type.
It can be `Rc<RefCell< InnerInstance >>` or just `InnerInstance `.

**Comment by grilme99** [comment]
Yep, I just came here to comment that I found the issue. Silly mistake. Thank you, though!
