### ISSUE TITLE
luaopen_base option

### ISSUE THREAD

**Issue by ProkopRandacek** [khvzak/mlua#235]
I have noticed when transitioning from `rlua` `mlua` that the lua base library can no longer be disabled through the `StdLib` parameter. Why is that?

PS: how did the 'safe' option in StdLib came to be? it exposes the `io` library as well as the bytecode loading functions from base library. I don't think this subset of lua is safe at all.

**Comment by khvzak** [comment]
> I have noticed when transitioning from rlua mlua that the lua base library can no longer be disabled through the StdLib parameter. Why is that?

No particular reason as far as I remember. Is there any reason to disable base lib?

> how did the 'safe' option in StdLib came to be?

In the "safe" mode, mlua disables loading C modules and `debug` library (plus `ffi` for LuaJIT).

>  I don't think this subset of lua is safe at all.

mlua does not guarantee absolute safety. Similar in Rust, you can do unsafe operations using "safe" subset, for example, by reading/writing to `/proc/self/mem`. Does it mean that `std::fs` should be disabled?
If you need the most safe Lua version with sandboxing, probably Luau is the best choice. It does not has `io`/`os`/etc libraries plus any other functions that can access the environment.

**Comment by ProkopRandacek** [comment]
> > I have noticed when transitioning from rlua mlua that the lua base library can no longer be disabled through the StdLib parameter. Why is that?
> 
> No particular reason as far as I remember. Is there any reason to disable base lib?

My problem is the bytecode executing function that it exposes. I can remove the function from the global table when creating the lua state but I was worried that there was some weird lua corner case that can dig the function back.

> > how did the 'safe' option in StdLib came to be?
> 
> In the "safe" mode, mlua disables loading C modules and `debug` library (plus `ffi` for LuaJIT). Nothing else.
> 
> > I don't think this subset of lua is safe at all.
> 
> mlua does not guarantee absolute safety. Similar in Rust, you can do unsafe operations using "safe" subset, for example, by reading/writing to `/proc/self/mem`. Does it mean that `std::fs` should be disabled? If you need the most safe Lua version with sandboxing, probably Luau is the best choice. It does not has `io`/`os`/etc libraries plus any other functions that can access the environment.

Alright I can see that I confused the safe as in rust safe and safe as in safe to execute untrusted code. My bad but perhaps it would be worth putting up a note in the docs.

**Comment by khvzak** [comment]
> My problem is the bytecode executing function that it exposes. I can remove the function from the global table when creating the lua state but I was worried that there was some weird lua corner case that can dig the function back.

[`luaopen_base`](https://github.com/lua/lua/blob/master/lbaselib.c#L537) does not do any magic, just adds few functions to the global table.
You can remove any unneeded, I don't think there is any (known) way to bring them back. If think about "weird lua corner case", I would worry about loading "base"/"io"/"os"/"debug" libraries back too :)

From the perspective of "execute untrusted code" mlua is on the same boat with rlua. 
However I intentionally choose not to patch `load`/`loadfile`/`loadstring`/`dofile` in safe mode, since it's really "hell" to support all Lua versions. Better to wipe the untrasted funcs from the global namespace / replace with your own.
By the way, rlua does the same - just rewrites global table and replaces with patched versions.

**Comment by grilme99** [comment]
> My problem is the bytecode executing function that it exposes. I can remove the function from the global table when creating the lua state but I was worried that there was some weird lua corner case that can dig the function back.

Luau is what you want here. It's designed to execute actively malicious code safely. The standard library it provides gives no access to the underlying operating system, and it has a number of sandboxing features other Lua implementations do not have.

See more here: https://luau-lang.org/sandbox.

**Comment by ProkopRandacek** [comment]
> [`luaopen_base`](https://github.com/lua/lua/blob/master/lbaselib.c#L537) does not do any magic, just adds few functions to the global table.

That is reassuring. Thanks.

> Luau is what you want here. It's designed to execute actively malicious code safely. The standard library it provides gives no access to the underlying operating system, and it has a number of sandboxing features other Lua implementations do not have.

That is actually really interesting read. I will look into luau more. Thanks :D
