### ISSUE TITLE
Allow deserializing `UserData` if it was created with `create_ser_userdata`

### ISSUE THREAD

**Issue by JSH32** [khvzak/mlua#240]
When deserializing into a struct with `from_value` we get an error. This is because deserializing into anything with `UserData` isn't allowed. I'm already able to get around this fact using this hack.
```rs
serde_json::from_str(&serde_json::to_string(&request).to_lua_err()?).to_lua_err()?
```
This only works if it was created with `create_ser_userdata`. Since this is already possible through something like this. Would it be possible to just allow deserialization with `from_value` directly if it was created with `create_ser_userdata`?

**Comment by khvzak** [comment]
Unfortunately it's not possible to deserialize directly from a type that implements `Serialize` trait (userdata).
Your approach is right, to serialize first into an intermediate struct which implements `Deserialize`.

More efficient would be:
```rust
serde_json::from_value(&serde_json::to_value(&request).to_lua_err()?).to_lua_err()?
```
