### ISSUE TITLE
Advice for storing Chunk or Function in a struct?

### ISSUE THREAD

**Issue by samstokes** [khvzak/mlua#241]
This is probably just me not knowing Rust well enough, but I thought other users of this crate might have come across the same issue.

I'm writing a CLI that embeds an `mlua::Lua` to run a single script against multiple input files. I am reusing the same interpreter instance across all files.

I'd like to precompile the script into an `mlua::Function` to check syntax and optimize runtime. However, I'm running into an issue with lifetimes. I'm trying to store the interpreter and the precompiled function in a struct like this:

```rust
struct Processor<'lua> {
    lua: Lua,
    script: Function<'lua>
}
// ...
let lua = Lua::new();
let script = lua.load("print('hello')").into_function().unwrap();
let processor = Processor { lua, script };
// ... elsewhere
for file in files {
  processor.process(&file);
}
```

However, I can't get the struct initialization past the borrow checker, because it complains that `script` may outlive `lua.load()`'s borrow of `lua` - even though I plan to store them in the same struct.

I think this is just a case of self-referential structs being difficult in Rust. But it seems like a common use case - create an interpreter, compile some scripts, and reuse both for the rest of the program - so I'm wondering if there are common patterns to solve it?

As one possibility, I've come across the [`ouroboros` crate](https://docs.rs/ouroboros/latest/ouroboros/attr.self_referencing.html) which solves it via macros and `unsafe`.

**Comment by khvzak** [comment]
You can store any Lua type in the registry (with autogenerated or named key) and then retrieve it back. Registry keys are `'static` and easy to embed.
See [`Lua::create_registry_value`](https://docs.rs/mlua/0.8.7/mlua/struct.Lua.html#method.create_registry_value) / [`Lua::registry_value`](https://docs.rs/mlua/0.8.7/mlua/struct.Lua.html#method.registry_value) and [`RegistryKey`](https://docs.rs/mlua/0.8.7/mlua/struct.RegistryKey.html)

You can find a usage example for instance in [`async_tcp_server.rs`](https://github.com/khvzak/mlua/blob/master/examples/async_tcp_server.rs)

**Comment by samstokes** [comment]
That's perfect, thanks!
