### ISSUE TITLE
thread 'main' panicked at 'cannot find Lua 5.4 using `pkg-config

### ISSUE THREAD

**Issue by trans-bug** [khvzak/mlua#246]
hello, in windows platform, even install pkg-config.exe , err still occur, how can i solve this problem ,thanks

**Comment by trans-bug** [comment]
i try to set environment var , but it doesn't work, still report this err

**Comment by khvzak** [comment]
Have you tried vendored mode? It’s much simpler

**Comment by trans-bug** [comment]
I compile it by make , jump over this problem, thanks for your advice , I will try it later, thank you very much.

**Comment by daniel-brenot** [comment]
@khvzak I thought vendored mode didn't work on windows? Also i am having a similar issue, but i believe i just don't understand what the variables should be pointing to

**Comment by khvzak** [comment]
vendored mode works on windows for any Lua, if it's not a module.

**Comment by IsusRamzy** [comment]
Same error on Linux x86-64!
