### ISSUE TITLE
how do you properly terminate a thread?

### ISSUE THREAD

**Issue by absencelul** [khvzak/mlua#258]
So, I've been looking at mlua for a while now and wanted to implement a scripting engine using it. Appreciate all the hard work being put into this crate! On to the details - The engine would essentially run a script one at a time as the user starts them and it would never return any data - the script could run for infinite time or until the user pauses / stops the script. I am having trouble finding any resources or examples using threads/coroutines.

At first, I thought I could just spawn a thread from rust and then execute the main lua function from the script inside said thread and handle all of the stopping and pausing from the rust side. After doing so I was met with some complications like my client freezing. I then posted a question on StackOverflow and was pointed in the direction of wrapping my main function in a coroutine using create_thread and then just calling reset to stop the current thread. But it seems like the thread isn't ever being stopped..

Do you have any examples of how this could work? StackOverflow link here: https://stackoverflow.com/questions/75612940/whats-the-proper-way-of-terminating-a-lua-script-thread-in-rust/

Some example code of what I tried:

```
pub struct Script {
    lua: Arc<Mutex<Lua>>,
}

impl Script {
    pub fn new() -> Result<Self, ScriptError> {
        let lua = Arc::new(Mutex::new(Lua::new()));

        Ok(Self { lua })
    }

    pub fn load(&mut self) -> Result<(), ScriptError> {
        let lua = self.lua.lock().unwrap();
        lua.load(
            r#"
            function add(a, b)
                return a + b
            end

            function main()
                while true do
                    add(1, 2)
                end
            end
        "#,
        )
        .exec()
        .map_err(ScriptError::FailedToRunScript)?;

        // Check if the script has a main function
        lua.globals()
            .get::<_, mlua::Function>("main")
            .map_err(|e| ScriptError::MissingRequiredFunction("main", e))?;

        Ok(())
    }

    pub fn run(&mut self) -> Result<(), ScriptError> {
        let lua = self.lua.lock().unwrap();
        let main = lua
            .globals()
            .get::<_, mlua::Function>("main")
            .map_err(|e| ScriptError::MissingRequiredFunction("main", e))?;

        // throw main into a lua coroutine
        let thread = lua
            .create_thread(main)
            .map_err(|e| ScriptError::FailedToCreateThread("main", e))?;

        // run the coroutine
        thread
            .resume(())
            .map_err(|e| ScriptError::FailedToRunThread("main", e))?;

        Ok(())
    }

    pub fn stop(&mut self) -> Result<(), ScriptError> {
        let lua = self.lua.lock().unwrap();
        let main = lua
            .globals()
            .get::<_, mlua::Function>("main")
            .map_err(|e| ScriptError::MissingRequiredFunction("main", e))?;

        let thread = lua.current_thread();
        thread
            .reset(main)
            .map_err(|e| ScriptError::FailedToStopThread("main", e))?;

        Ok(())
    }
}

```

**Comment by khvzak** [comment]
You don't need coroutines to do this, the usual way in Lua is use hooks and throw error inside a hook.

An example how to limit execution of any function to 1 sec:
```rust
    let start = std::time::Instant::now();
    lua.set_hook(HookTriggers::on_calls(), move |lua, _| {
        if start.elapsed().as_secs_f64() >= 1.0 {
            lua.remove_hook();
            return Err(Error::RuntimeError("timeout".to_string()));
        }
        Ok(())
    })?;

    lua.globals()
        .get::<_, Function>("main")?
        .call::<_, ()>(())
        .unwrap();
```

If you use Luau, you need to set up interrupt, but it would allow in addition yielding back, giving ability to resume suspended code.

**Comment by absencelul** [comment]
> You don't need coroutines to do this, the usual way in Lua is use hooks and throw error inside a hook.
> 
> An example how to limit execution of any function to 1 sec:
> 
> ```rust
>     let start = std::time::Instant::now();
>     lua.set_hook(HookTriggers::every_nth_instruction(10), move |lua, _| {
>         if start.elapsed().as_secs_f64() >= 1.0 {
>             lua.remove_hook();
>             return Err(Error::RuntimeError("timeout".to_string()));
>         }
>         Ok(())
>     })?;
> 
>     lua.globals()
>         .get::<_, Function>("main")?
>         .call::<_, ()>(())
>         .unwrap();
> ```
> 
> If you use Luau, you need to set up interrupt, but it would allow in addition yielding back, giving ability to resume suspended code.

thanks, this is great. how do you think this effects performance?

**Comment by khvzak** [comment]
> how do you think this effects performance?

Not too much, especially if you set right `HookTriggers`.  Eg. Lua can call hook on function call/return/etc.
For the code above, calling hook every `1000000` or `10000000` insturction is more than enough.

**Comment by absencelul** [comment]
thanks! I appreciate the feedback and solution. closing this as it is resolved.
