### ISSUE TITLE
Allow to create a function with self passed as first argument

### ISSUE THREAD

**Issue by the-ssd** [khvzak/mlua#259]
if this is even possible to create function with self as first argument

```rust
struct example {
    example_data: i32
}

impl example {
    fn rust_function(&self, _: &Lua, _: () ) -> Result<(), LuaError> {
        //stuff with self
    }
}
```
in this case for `rust_function`

**Comment by khvzak** [comment]
You need to use [`UserData`](https://docs.rs/mlua/latest/mlua/trait.UserData.html)

[example](https://github.com/khvzak/mlua/blob/master/examples/userdata.rs)

**Comment by the-ssd** [comment]
thanks this is very useful
