### ISSUE TITLE
Create new LuaString and LuaTables

### ISSUE THREAD

**Issue by the-ssd** [khvzak/mlua#260]
current workaround for string is `lua.load( &format!("\"{}\"", rust_string)).eval().ok()?`
maybe add LuaString::new(lua)

**Comment by khvzak** [comment]
- [`Lua::create_table`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_table)
- [`Lua::create_string`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_string)
and so on
