### ISSUE TITLE
Problem with deserializing enums with variants wrapping unit structs

### ISSUE THREAD

**Issue by eldyer** [khvzak/mlua#264]
I'm trying to deserialize an enum like this:

```rust
#[derive(Deserialize)]
struct Unit;

#[derive(Deserialize)]
enum Enum {
    Tuple(u32, u32),
    Struct { x: u32 },
    UnitLike,
    Wrap(Unit),
}
```

While the first three variants work without problems, I can't find a lua representation for `Wrap(Unit)`:

```rust
    let _enum: Vec<Enum> = lua.from_value(
        lua.load(
            r#"
            {
                { Tuple = { 3, 4 } },
                { Struct = { x = 5 } },
                "UnitLike",
                -- "Wrap", -- doesn't work
                -- { Wrap = "Unit" }, -- doesn't work
            }
            "#,
        )
        .eval()?,
    )?;
```

**Comment by khvzak** [comment]
It's a bug indeed, I'll push a fix soon

**Comment by eldyer** [comment]
Awesome! 

On a side note: To get more consistency in representing variants with and without values, would it make sense to also allow, for example, the representation `{ UnitLike = {} }` for `UnitLike`?

**Comment by khvzak** [comment]
> On a side note: To get more consistency in representing variants with and without values, would it make sense to also allow, for example, the representation `{ UnitLike = {} }` for `UnitLike`?

I'm not sure this is a good idea. I would prefer to stay in line with common expectations, for example used in serde_json library.
It definitely would not allow deserializing `{"UnitLike": {}}` json to `UnitLike`.

**Comment by khvzak** [comment]
I pushed a fix. The `Enum:: Wrap` should be deserializable from `{ Wrap = null }` where `null` is [`Lua::null()`](https://docs.rs/mlua/0.8.8/mlua/struct.Lua.html#method.null)

**Comment by khvzak** [comment]
The patch went to v0.8.9
