### ISSUE TITLE
Reference leak in async function

### ISSUE THREAD

**Issue by mpfaff** [khvzak/mlua#268]
The bug seems to be caused by moving a lua value into the `async move` block, yielding once, then dropping the `Lua` instance.

Reproduces with `lua54,vendored`, `luau` and `luajit52,vendored`.

Requires `futures_micro` for `yield_once`. You can use any other future too, as long as it yields at least once.

This is my minimal reproduction of the bug:

```rust
use mlua::FromLua;

fn main() {
    let vm: mlua::Lua = mlua::Lua::new();

    vm.globals().set("foo", vm.create_async_function(move |vm, msg: mlua::Value| async move {
        futures_micro::yield_once().await;
        drop(msg);
        Ok(())
    }).unwrap()).unwrap();

    vm.load(r#"
        local a = coroutine.create(function()
            foo("we yielded!")
        end)
        coroutine.resume(a)
    "#)
        .call::<_, ()>(())
        .unwrap();
}
```

**Output:**

```
thread 'main' panicked at 'mlua internal error: reference leak detected (this is a bug, please file an issue)'
```

**Comment by khvzak** [comment]
Thanks for the report! Seems it's too strict assertion than a bug. When you do yield, your coroutine become suspended and captures `Value`. So couple of GC cycles are required to release it (and the corresponding reference).

I'll fix it soon, the assertion is useful only for mlua integrational tests than for generic usage.
