### ISSUE TITLE
Empty lua array

### ISSUE THREAD

**Issue by AlexXi19** [khvzak/mlua#272]
I have a rust method that I bind to a global that return a Vector<Struct>. If i return an empty vector like `vec![]`, that gets converted to a lua table instead of an array. I was wondering if this is something on my end, something that's intended or something that's not handled by this create. Thanks in advance for you help!

**Comment by khvzak** [comment]
> that gets converted to a lua table instead of an array

Hm, Lua tables are arrays are the same thing. If you refer to serialization, there is a special metatable [`array_metatable`](https://docs.rs/mlua/0.8.8/mlua/trait.LuaSerdeExt.html#tymethod.array_metatable) that forces endocoding to array.

**Comment by AlexXi19** [comment]
Yeah, I am aware, the behavior that I'm getting is an empty array converted to a table without the array_metatable, so when I do something with it like converting to serde json, it's treated as a struct instead of an array 🤔

**Comment by AlexXi19** [comment]
Ok, thanks for the info
