### ISSUE TITLE
Port `tostring` method from `Lua` for `Value`

### ISSUE THREAD

**Issue by zhiburt** [khvzak/mlua#279]
Hi @khvzak 

I was wondering if adding the corresponding method from Lua itself could be valuable.
Currently [`coerce_string`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.coerce_string) exists but it does cover only basic types; in case of error/coorutine/table/function it will return `None`.

It's true that we could call `load` and then `eval` to obtain the value, or as you've showed here https://docs.rs/mlua/latest/mlua/struct.Function.html#method.call.

But maybe a new method could be created which would use C api directly?

source - https://www.lua.org/source/5.4/lauxlib.c.html#luaL_tolstring

Take care

PS: not an expert in the FFI happening here maybe its already cost effective;

**Comment by khvzak** [comment]
Thanks, adding the method looks reasonable to me.

Sorry, I have to close your PR #280 in favour or alternative implementation.
I feel using `value.to_string()` would be more ergonomic than `lua.to_string(&value)`.
Also the PR looks incomplete:
- It does not try to call `__tostring` metamethod.
- Luau vector is skipped
- No tests
