### ISSUE TITLE
Add Vector4 support in LuaValue

### ISSUE THREAD

**Issue by coderedart** [khvzak/mlua#284]
There are a bunch of places where one might use Vec4 types like 
1. linear rgba colors https://docs.rs/egui/latest/egui/struct.Rgba.html
2. Rectangle (topleft vec2 + bottomright vec2) https://docs.rs/egui/latest/egui/struct.Rect.html
3. Radius of each rounded corner of a rect. https://docs.rs/egui/latest/egui/struct.Rounding.html
4. Quaternions etc..

I found https://github.com/Roblox/luau/pull/214 where Luau introduced support for vec4 with just 5% perf loss. 

I think it could be useful if we could change the `Vector3` in the value enum to `Vector4` support behind a feature flag for Luau.

**Comment by khvzak** [comment]
I'll take a look what I can do.

**Comment by coderedart** [comment]
nice. ty <3
