### ISSUE TITLE
Clone Lua instance

### ISSUE THREAD

**Issue by fabi321** [khvzak/mlua#292]
Is it possible to clone all the state from a `Lua` instance?
From what I've seen, there is [`Lua::init_from_ptr`](https://docs.rs/mlua/0.8.9/mlua/struct.Lua.html#method.init_from_ptr), but I can't seem to find any way to export this state from a `Lua` instance.
My goal is to have 2 instances of lua, that have all the same globals as well as closures, but are independent from each other.

**Comment by khvzak** [comment]
What problem are you trying to solve? 

You can wrap Lua into Rc to get any number of `Rc<Lua>`.

**Comment by fabi321** [comment]
I want to evaluate a function with the same set of variables, without changing them. Kinda like luau's sandbox does.

**Comment by khvzak** [comment]
You could try [`Function::set_environment()`](https://docs.rs/mlua/0.9.0-rc.1/mlua/struct.Function.html#method.set_environment) method in v0.9 version.

If this will not work I doubt that it's possible without creating two independent Lua VMs.
