### ISSUE TITLE
Compilation on Android fails

### ISSUE THREAD

**Issue by sayanarijit** [khvzak/mlua#293]
stderr
  make: *** [Makefile:731: libluajit.a] Error 127
  thread 'main' panicked at '
  Error building LuaJIT:
      Command: cd "/data/data/com.termux/files/usr/tmp/cargo-installf8UIYd/release/build/mlua-1ec94da245a62307/out/luajit-build/build/src" && BUILDMODE="static" CROSS="aarch64-linux-android-" XCFLAGS="-fPIC" "make" "-e"
      Exit status: exit status: 2
      ', /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/luajit-src-210.4.5+resty2cf5186/src/lib.rs:200:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---

~ $ make --version
GNU Make 4.4.1

**Comment by sayanarijit** [comment]
Sorry, duplicate of https://github.com/khvzak/mlua/issues/267

**Comment by khvzak** [comment]
@sayanarijit would you consider switching to Luau or Lua54 instead (if you need binary modules)?
Luau is developed by Roblox and is the fastest Lua version. Roblox also actively work on JIT backend for Luau which is already supported in mlua v0.9 (experimental mode).

Luajit unfortunately has _very_ complex build system. Could you reproduce (or not) the issue when compiling [luajit](https://github.com/openresty/luajit2) itself?

**Comment by sayanarijit** [comment]
Luau seems to be incompatible...

```luau
nix-shell:~/GitHub/xplr]$ luau
> print(os.getenv("SHELL"))
stdin:1: attempt to call a nil value
stack backtrace:
stdin:1
```

Lua54 works fine... Will try it...

**Comment by khvzak** [comment]
Luau has no `os` module (see https://luau-lang.org/compatibility) but it can be easily added. They exclude it because of sandboxing reasons.

**Comment by sayanarijit** [comment]
Luau looks interesting... But with my very limited Lua knowledge, I couldn't find much information on solving for compatibility, other than [this comment](https://github.com/Roblox/luau/discussions/240#discussioncomment-1712805). But it only mentions what needs to be implemented, not how.

On the other hand, Lua54 worked like a charm, but I had to install `binutils` dependency. Although, it'll probably break user config that depends on luarocks dependencies (probably not much though). Lua51 compiled, but didn't work properly.

I wasn't able to compile luajit or luajit2 on android. But the errors I saw were different before and after installing binutils.

**Comment by khvzak** [comment]
> Lua51 compiled, but didn't work properly.

Is it because of async, or other reason?

> I wasn't able to compile luajit or luajit2 on android. But the errors I saw were different before and after installing binutils.

I'll take a look. To confirm, that arch you tried, was it `aarch64-linux-android` ? Do you have cross toolchains installed for that arch?

**Comment by sayanarijit** [comment]
> Is it because of async, or other reason?

No, probably unicode issue. The bash color codes were broken.

> was it aarch64-linux-android ? Do you have cross toolchains installed for that arch?

I directly tried on termux. It'll complain about aarch64-linux-android-ar not being installed, which can be solved by installing binutils (for lua54). Ref: https://github.com/termux/termux-packages/discussions/8214#discussioncomment-1793086

**Comment by khvzak** [comment]
in CI tests mlua sucessfully compiled to aarch64 (including luajit).

This works for android too.
Check the [script](https://github.com/khvzak/mlua/blob/master/.github/workflows/main.yml#L55).

I just tried compiling to android target on ubuntu jammy, it works:
```
$ apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross
$ rustup target add aarch64-linux-android
$ cargo build --target aarch64-linux-android --features luajit,vendored
```

**Comment by khvzak** [comment]
I think I found bug in luajit-src crate, it expects gcc compiler to set CROSS env, but andorid uses llvm
