### ISSUE TITLE
More directly support the `__type` meta field in Luau

### ISSUE THREAD

**Issue by Dekkonot** [khvzak/mlua#295]
Luau allows host programs to set the `__type` field of a userdata's metatable to control the output of the Luau global `typeof` when it's called on a value of that type. However, the `MetaMethod` enum doesn't have a variant for it.

Given that `__type` isn't a metamethod, this isn't surprising. It would be nice if it was supported more directly in the same way metamethods are though. I'm not sure what my ideal API for this would look like, but having only one field in a metatable that's defined with a literal feels bad, so I'd like not that.

**Comment by khvzak** [comment]
In v0.9 I set `__name` metamethod automatically for all userdata. I'll check how `__type` is used in Luau

**Comment by khvzak** [comment]
Also v0.9 has [`new API`](https://docs.rs/mlua/0.9.0-rc.1/mlua/trait.UserDataFields.html#tymethod.add_meta_field) and you can use arbitrary strings for meta methods/fields.
