### ISSUE TITLE
Lua::load_chunk support inherit environment from the caller

### ISSUE THREAD

**Issue by persytry** [khvzak/mlua#296]
Lua::load_chunk support two environment now. 1th is global as default, 2th is specified by user. 
Could you support the 3th, that is inherited from the caller?
```rust
let lua = Lua::new();
lua.load("function dofile(rust_dofile_func, path) return rust_dofile_func(path, _ENV); end").exec()?;
let lua_dofile: LuaFunction = lua.globals().get("dofile")?;
let lua_dofile = lua_dofile.bind(rust_dofile_func)?;
lua.global().set("dofile", lua_dofile)?;
```
The `_ENV` inside lua_dofile is always global table, but I want the `_ENV` is the value as the calller.
Thanks.

**Comment by khvzak** [comment]
In v0.9 you can use [`Function::environment()`] and [`Function::set_environment()`] to get/change functions env.

[`Function::environment()`]: https://docs.rs/mlua/0.9.0-rc.1/mlua/struct.Function.html#method.environment
[`Function::set_environment`]: https://docs.rs/mlua/0.9.0-rc.1/mlua/struct.Function.html#method.set_environment

**Comment by persytry** [comment]
alright, thanks.
