### ISSUE TITLE
mlua v0.9

### ISSUE THREAD

**Issue by khvzak** [khvzak/mlua#298]
The new mlua version is about to be released. 

The release notes can be found [here](https://github.com/khvzak/mlua/blob/master/docs/release_notes/v0.9.md).

If you have any feedback about the upcoming changes, it's not too late to share it :)

**Comment by filiptibell** [comment]
Hi! The `0.9` release is looking great, the any userdata api will definitely be useful. Will it be possible to use it to extend builtin lua values somehow? If I want to add methods such as dot product etc to the luau vector type, will I be able to use this? If not, that would also be very useful

**Comment by filiptibell** [comment]
Another thing - would it be possible to have an `OwnedThread` type? It would make things a lot easier for us as we have a task scheduler in rust that schedules threads and currently have to use registry keys (https://github.com/filiptibell/lune/blob/689994552fef8b4cf816b71fefefb44eddcb38ff/src/lune/lua/task/scheduler.rs#L27)

**Comment by khvzak** [comment]
`OwnedThread` type is added.

Regarding extending builtin Luau vector type, I also added method `Lua::set_vector_metatable()` which should allow to do this (via `__index`).
