### ISSUE TITLE
Error building against luajit

### ISSUE THREAD

**Issue by alerque** [khvzak/mlua#3]
My system (Arch Linux) has luajit-2.0.5 (the latest stable release). The system's Neovim package is also compiled against that, so the building Lua interpreter is luajit.

I'm able to build a module that can be loaded by Lua 5.3, but I'm having a hard time building the same source against luajit so it can be loaded by Neovim.

```
❯ LUA_INC=/usr/include/luajit-2.0 LUA_LIB=/usr/share/luajit-2.0.5 LUA_LIB_NAME=luajit LUA_LINK=static cargo build
   Compiling mlua v0.3.2
error[E0432]: unresolved import `self::lualib::LUA_UTF8LIBNAME`
   --> /home/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/mlua-0.3.2/src/ffi/mod.rs:230:9
    |
230 | pub use self::lualib::LUA_UTF8LIBNAME;
    |         ^^^^^^^^^^^^^^---------------
    |         |             |
    |         |             help: a similar name exists in the module: `LUA_STRLIBNAME`
    |         no `LUA_UTF8LIBNAME` in `ffi::lualib`

error[E0432]: unresolved import `super::glue::LUAL_NUMSIZES`
  --> /home/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/mlua-0.3.2/src/ffi/lauxlib.rs:32:9
   |
32 | pub use super::glue::LUAL_NUMSIZES;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `LUAL_NUMSIZES` in `ffi::glue`

error[E0432]: unresolved import `super::glue::LUAL_NUMSIZES`
  --> /home/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/mlua-0.3.2/src/ffi/luaconf.rs:34:9
   |
34 | pub use super::glue::LUAL_NUMSIZES;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `LUAL_NUMSIZES` in `ffi::glue`

error[E0432]: unresolved import `super::glue::LUA_UTF8LIBNAME`
  --> /home/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/mlua-0.3.2/src/ffi/lualib.rs:36:9
   |
36 | pub use super::glue::LUA_UTF8LIBNAME;
   |         ^^^^^^^^^^^^^---------------
   |         |            |
   |         |            help: a similar name exists in the module: `LUA_STRLIBNAME`
   |         no `LUA_UTF8LIBNAME` in `ffi::glue`

error: aborting due to 4 previous errors
```

Is it possible to build against this version of luajit or is this completely unsupported?

**Comment by khvzak** [comment]
Will take a look. I have even not tried this version of LuaJIT as it's too old.

**Comment by alerque** [comment]
It's too old for my *liking* too, but it's the last release of LuaJIT marked as stable and the defacto default version for lots of things with Lua support compiled in, not the least of which being Neovim on lots of distros. I'd have picked something else myself, but I need to build a module that can be loaded by other people in their distro's bulid of Neovim so I don't really get a choice of versions.

**Comment by alerque** [comment]
This isn't just LuaJIT. I get the same error building against Lua 5.1 or 5.2. Only 5.3 works.

**Comment by alerque** [comment]
Um...take that back. This is largely a documentation issue. Lua 5.1 and 5.2 do work, but you have to **BOTH** set the include paths manually **AND** the matching feature flag. I assumed from the README that just the paths were enough for it to detect the right Lua version as it was doing by default for 5.3.

By the way a mechanism to just ask `pkg-config` about a specific version of Lua would make that whole thing simpler.

**Comment by alerque** [comment]
Same goes for LuaJIT (2.0.5). I _can_ build against it using the system libraries although the paths are a bit funky.

Sorry for the initial confusion. This issue has now become:

1. A single ENV var to define what to query `pkg-config` with to get all the right variables would be far more useful that trying to piece them together manually.

2. Documentation that notes the feature flag needs to be set in addition to setting matching ENV vars would be helpful.

**Comment by khvzak** [comment]
Specifying `feature = "lua51/lua52/lua53/etc"` it enough to work in `pkg-config` mode. `mlua` will call `pkg-config` with proper version boundaries, according the selected feature.

Custom `LUA_INC/LUA_LIB/etc` mode is a BIG hack which completely disables `pkg-config` and used for very exotic cases.

You must specify required feature flags in _any_ case, `lua53` is just enabled by default. ENV variables cannot be used to control feature flags.

**Comment by alerque** [comment]
> Specifying `feature = "lua51/lua52/lua53/etc"` it enough to work in `pkg-config` mode. `mlua` will call `pkg-config` with proper version boundaries, according the selected feature.

That's what I might have expected, but it doesn't work. At least not for LuaJIT 5.0, which my system has. The `pkg-config` data is correct, but I have to plug it into the variables manually before I can build. That might have to do with the hard coded check fore 2.1 in there somewhere. Remove that and it might work out of the box with no ENV var hacks.

**Comment by khvzak** [comment]
> Remove that and it might work out of the box with no ENV var hacks.
`mlua` was tested using `LuaJIT >=2.1.0`. This is why it's a strict requirement. I assume some work is required to make `mlua` suitable for LuaJIT 2.0.5.

ENV variables are definitely can be used to bypass `pkg-config` and version boundaries check.
And this is one of the exotic cases  I was saying above.
If LuaJIT guarantee compatibility with Lua 5.1 you should be able to build `mlua` with `feature = "lua51"` and custom LUA_INC/LIB referring to luajit-2.0.5.

**Comment by khvzak** [comment]
I can confirm that `mlua v0.3` works with `LuaJIT v2.0.5` __at least__ on Linux target. 
But it does not work in the upcoming `v0.4` release I'm working on. Likely I'll make necessary changes to bring v2.0.5 support.

**Comment by khvzak** [comment]
LuaJIT 2.0.5 is now supported on the latest v0.4

**Comment by alerque** [comment]
Hurrah! Thanks for that. Neovim plugins here I come.
