### ISSUE TITLE
Using Owned* with OnceCell

### ISSUE THREAD

**Issue by j-hui** [khvzak/mlua#301]
I'm implementing some Rust objects that have reference-y semantics, so something like `p == q` needs to work where `p` and `q` are both `userdata` constructed from the same Rust object.

My intended solution is to cache an `OnceCell<OwnedAnyUserData>`, and `.set()` it the first time I construct an `AnyUserData` out of my object. However, the life time of the `&AnyUserData` I get out of the cache is tied to the `OnceCell`, so I can't do something like this:

```rust
fn get_userdata<'lua>(lua: &'lua Lua, cache: OnceCell<OwnedAnyUserData>) -> AnyUserData<'lua> {
    if let Some(ud) = cache.get() {
        return ud.to_ref();
        // ^ cannot return value referencing function parameter `cache`
        //   returns a value referencing data owned by the current function [E0515]
    }
    let ud = lua.create_any_userdata(()).unwrap();
    cache.set(ud.clone().into_owned()).unwrap();
    ud
}
```

Is there some way to make this work/achieve what I would like to do, without resorting to attaching a `'lua` lifetime to my object or an unsafe `mem::transmute()`?

Thanks!

**Comment by khvzak** [comment]
You can re-attach `'lua` lifetime to owned objects using the next trick:
```rust
let Ok(Value::UserData(ud)) = lua.pack(ud) else { unreachable!() };
return ud;
```

or something like:
```rust
if let Ok(Value::UserData(ud)) = lua.pack(cache.get()) {
    return ud;
}
```

Also maybe in your case storing userdata in Lua registry can be easier (`lua.create_registry_value()` and `lua.registry_value()`)
