### ISSUE TITLE
Deterministic / sorted mode for serde integration

### ISSUE THREAD

**Issue by filiptibell** [khvzak/mlua#303]
I have serde exposed in lua and do something more or less like this:

```lua
writeFile("file.json", encodeJson({
    -- generated data from a web api or similar, the structure is
    -- unknown so it is difficult to manually compose the json in
    -- plain lua especially while maintaining good performance...
    foo = "bar",
    baz = "qux",
}))
```

This file `file.json` is then meant to be committed to source control, but the generation of this file is currently not deterministic and leads to a lot of git diff noise since either `foo` or `baz` keys may come first and order is unspecified.

It would be nice to have options in mlua to use deterministic / sorted serialization for this use case.

**Comment by khvzak** [comment]
This is a good idea actually, I'll make it.

Btw, what do you use for serializaition, `Lua::from_value()` or `impl  Serialize for Value` ?

**Comment by filiptibell** [comment]
> Btw, what do you use for serializaition, `Lua::from_value()` or `impl Serialize for Value` ?

We use the serialize trait impl, source here: https://github.com/filiptibell/lune/blob/689994552fef8b4cf816b71fefefb44eddcb38ff/src/lune/lua/serde/encode_decode.rs#L51-L72
I guess I would need to change the above code a bit if sorted serialization is a new optional behavior? Or would it be default behavior?
