### ISSUE TITLE
cannot find Lua 5.1 using `pkg-config` on Windows

### ISSUE THREAD

**Issue by Camble** [khvzak/mlua#304]
I'm able to build the example from the repo just fine, but get the following error when building my own simple module:
I've tried "vendored" mode, but this only seems to work if I omit "module". I have Lua 5.1 installed locally and my PATH variable points to the folder. I've tried downloading `lua5.1.dll` as suggested in another issue, but can't see how to specify its location.

```
error: failed to run custom build command for 'mlua v0.8.9'

Caused by:
  process didn't exit successfully: 'build-script-main' (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LUA_INC
  ..etc
  --- stderr
  thread 'main' panicked at 'cannot find Lua 5.1 using 'pkg-config'', .cargo\registry\src\index.crates.io-6f17d22bba15001f\mlua-0.8.9\build\find_normal.rs:75:32 note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace
```

My Cargo.toml looks like this:
```
[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.8.9", features = ["lua51", "module"] }
```

**Comment by khvzak** [comment]
Could you try v0.9 please. The windows building system was complitely changed, if does not require pkg-config or anything else on Windows.
You only need `lua51.dll` having on your app where you load module.

**Comment by Camble** [comment]
That did it! Thank you!
