### ISSUE TITLE
Lifetime specifier for FromLua trait?

### ISSUE THREAD

**Issue by KaitlynEthylia** [khvzak/mlua#305]
I have a function that needs to create a new Lua VM and get a value from it. Id like this function to be generic over types that implement FromLua, but the trait requires a lifetime specifier and I don't seem understand how to use this properly.

When not using a generic, and using, for example, a String, the function has no errors, but when trying to use the generic, it fails because, as far as i understand it, it wants the Lua VM to have the same lifetime as the type.

In this example I've reduced it to be bare minimum to see my issue, hence trying to get a value from a brand new Lua.

Using a string:
```rust
fn foo() {
	let lua = Lua::new();
	let fun: String = lua.globals().get("bar").unwrap();
}
```

Using a generic:
```rust
fn foo<'a, T: Clone + FromLua<'a> + 'static>() {
	let lua = Lua::new();
	let fun: T = lua.globals().get("bar").unwrap();
}
```

Some clarity on what's going on here and/or some ideas as to how to make this work correctly would be greatly appreciated.

**Comment by khvzak** [comment]
You can try:
```
fn foo<T: Clone + for<'a> FromLua<'a> + 'static>() -> T {
	let lua = Lua::new();
	let fun: T = lua.globals().get("bar").unwrap();
    fun
}
```

**Comment by KaitlynEthylia** [comment]
Thank you! This solved the issue perfectly

**Comment by KaitlynEthylia** [comment]
forgot to close
