### ISSUE TITLE
Loading DLLs that are mlua modules ("vendored", "module")?

### ISSUE THREAD

**Issue by tobii-dev** [khvzak/mlua#313]
I've been playing around with this crate on linux, where loading and running .so libraries built with the module feature worked very well. The reason this worked is probably because I had the lua5.1-dev libs installed on my system. Trying to get my tests working on windows, I'm now questioning my sanity:

On windows, I can create a module with the _module_ feature flag, compiling a DLL that is a loadable Lua module:
```rust
use mlua::prelude::*;

#[mlua::lua_module]
fn my_rust_lib(lua: &Lua) -> LuaResult<LuaTable> {
    println!("Hi from inside DLL: my_rust_lib(...)!");
    let exports = lua.create_table()?;
    exports.set("name", "HELLO!")?;
    Ok(exports)
}
```
I can compile this with `cargo build --target x86_64-pc-windows-msvc`, and copy my DLL:
`cp target\x86_64-pc-windows-msvc\debug\my_rust_lib.dll lib-my_rust_lib.dll`

I can load this 64 bit DLL from a 64 bit lua5.1.exe: [lua-5.1.5_Win64_bin.zip](https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/lua-5.1.5_Win64_bin.zip/download)

```
$ .\bin\64\lua5.1.exe -e print(require("lib-my_rust_lib").name)
Hi from inside DLL: my_rust_lib(...)!
HELLO!
```

If I do all of this for a 32 bit DLL:
`cargo build --target x86_64-pc-windows-msvc`
`cp target\i686-pc-windows-msvc\debug\my_rust_lib.dll lib-my_rust_lib.dll`
`.\bin\32\lua5.1.exe -e print(require("lib-my_rust_lib").name)`

It works exactly the same.

So far so good.

Now if load this from another mlua executable, it works:
```rust
//examples\minimal.rs
fn main() {
    let lua_vm = unsafe { mlua::Lua::unsafe_new() };
    let code = mlua::chunk! {
        print(">> Hi")
        print(require("lib-my_rust_lib").name)
    };
    lua_vm.load(code).exec().unwrap();
}
```
```
cargo run --example minimal
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target\debug\examples\minimal.exe`
>> Hi
Hi from inside DLL: my_rust_lib(...)!
HELLO!
```

I don't understand how it compiled the example `examples\minimal.rs`, **without** the _vendored_ feature flag.

This is my Cargo.toml:
```toml
[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9.1", features = ["lua51", "macros", "module"] }
```

Also, after that, if I replace the _module_ flag with _vendored_
```toml
[dependencies]
# mlua = { version = "0.9.1", features = ["lua51", "module", "macros"] }
mlua = { version = "0.9.1", features = ["lua51", "vendored", "macros"] }
```

and run the example again, I get a segfault:
```
cargo run --example minimal
     Running `target\debug\examples\minimal.exe`
>> Hi
error: process didn't exit successfully: `target\debug\examples\minimal.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

The docs I read on https://lib.rs/crates/mlua, at the Modules section, say:
> On Windows the target module will be linked with lua5x.dll library (depending on your feature flags). Your main application should provide this library.
> 
> Module builds don't require Lua lib or headers to be installed on the system.

I guess my main question is: How do these feature flags (_vendored_ vs _module_) on windows really work?
Am I misunderstanding how the DLL loading works? Why does it crash?

I'm glad it all compiles and "just runs" with only the _module_ flag, but I fear I'm misunderstanding something, and that something might cause me problems later.

Output of `cargo --version --verbose`:
```
cargo 1.74.0-nightly (d14c85f4e 2023-09-05)
release: 1.74.0-nightly
commit-hash: d14c85f4e6e7671673b1a1bc87231ff7164761e1
commit-date: 2023-09-05
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 Professional) [64-bit]
```

**Comment by khvzak** [comment]
> The reason this worked is probably because I had the lua5.1-dev libs installed on my system

mlua does not require Lua libs or includes to be installed in module mode. It just works as has definitions for Lua symbols internally.

> if I replace the module flag with vendored

You should not be able to compile module without `module` feature flag. Especially in `vendored` mode. Could you check please? The `mlua::lua_module` macro is not exported without `module` feature being enabled.

Also your app to load modules (on Windows only) should be built in non-vedored mode and be linked with lua51.dll.
Could be the reason why it works because you have 3rd party `lua51.dll` in your system?

> How do these feature flags (vendored vs module) on windows really work?

In `vendored` mode (on Windows) you app will be statically linked with Lua interpreter. In this mode ideally you should not be able load external Lua modules as of missing `lua51.dll` library.

In `module` mode modules (in any OS) linked with runtime symbols resolution. On unix symbols are taken from the main app that loads module. On windows symbols are taken from `lua51.dll`. Your app should be linked with this dll too.

**Comment by tobii-dev** [comment]
> You should not be able to compile module without `module` feature flag. Especially in `vendored` mode. Could you check please? The `mlua::lua_module` macro is not exported without `module` feature being enabled.

I get build error when compiling the module: `src/lib.rs` WITHOUT the `module` flag (I understand why). Here is the output:
```
cargo build --release --target x86_64-pc-windows-msvc
   ...
error: failed to run custom build command for `mlua-sys v0.3.2`

Caused by:
  process didn't exit successfully: `C:\Users\tobii\Desktop\DEV\rust\my_rust_lib\target\release\build\mlua-sys-97f0b30af2c4b9e0\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build
  {...}

  --- stderr
  thread 'main' panicked at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\mlua-sys-0.3.2\build\find_normal.rs:51:30:
  cannot find Lua5.1 using `pkg-config`: Could not run `"pkg-config" "--libs" "--cflags" "lua5.1"`
  The pkg-config command could not be found.

  Most likely, you need to install a pkg-config package for your OS.

  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.

  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the mlua-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
`Cargo.toml`:
```toml
mlua = { version = "0.9.1", features = ["lua51", "macros"] }
```

This all makes sense to me. What I don't understand is how it was able to compile and run the example, WITHOUT the `vendored` flag.

> Could be the reason why it works because you have 3rd party lua51.dll in your system?

I think this is probably the case, but I don't know where the hell it's finding `lua51.dll` on my system... I tried looking for it on windows search but windows search is useless -.- Is there an easy way to find out where it loads it from?

I checked if maybe it was using some files in the target directory, but no:
`Cargo.toml`:
```toml
[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9.1", features = ["lua51", "macros", "module"] }
```

`src/lib.rs`:
```rust
use mlua::prelude::*;

#[mlua::lua_module]
fn my_rust_lib(lua: &Lua) -> LuaResult<LuaTable> {
    println!("Hi from inside DLL: my_rust_lib(...)!");
    let exports = lua.create_table()?;
    exports.set("name", "HELLO!")?;
    Ok(exports)
}
```

`examples/minimal.rs`:
```rust
fn main() {
    let lua_vm = unsafe { mlua::Lua::unsafe_new() };
    let code = mlua::chunk! {
        print(">> Hi")
        print(require("lib-my_rust_lib").name)
    };
    lua_vm.load(code).exec().unwrap();
}
```

```shell
$ cargo clean # just in case
$ rm lib-my_rust_lib.dll minimal.exe # just in case

$ cargo build --release --target x86_64-pc-windows-msvc --example minimal 
   ...
   Compiling my_rust_lib v0.1.0 (C:\Users\tobii\Desktop\DEV\rust\my_rust_lib)
    Finished release [optimized] target(s) in 11.26s
$ cp target\x86_64-pc-windows-msvc\release\examples\minimal.exe minimal.exe # save .exe somewhere else

$ cargo clean # just in case: can't accidentally link to something that doesn't exist...
$ cargo build --release --target x86_64-pc-windows-msvc
  ...
  Compiling my_rust_lib v0.1.0 (C:\Users\tobii\Desktop\DEV\rust\my_rust_lib)
    Finished release [optimized] target(s) in 11.85s
$ cp target\x86_64-pc-windows-msvc\release\my_rust_lib.dll lib-my_rust_lib.dll # save module somewhere else

$ cargo clean # just in case

$ .\minimal.exe # WTF How?
>> Hi
Hi from inside DLL: my_rust_lib(...)!
HELLO!
```

> In `module` mode modules (in any OS) linked with runtime symbols resolution. On unix symbols are taken from the main app that loads module. On windows symbols are taken from `lua51.dll`. Your app should be linked with this dll too.

I understand how it should work now, thanks for taking the time! Do you know if, on windows, there is a way to make modules loadable from vendored? I think I want to use this the unix way, but on windows. I'm using this in an odd way (game modding/hooking), and would like to avoid distributing the extra `lua51.dll`.

I will dig around a bit more to see if it's actually loading `lua51.dll` from somewhere I'm not aware of.
In any case, thanks for clarifying!

**Comment by tobii-dev** [comment]
OKAY SANITY RESTORED! The culprit was having Neovim on my **PATH** env var! It ships with lua5.1
![image](https://github.com/khvzak/mlua/assets/77458451/6e61e9a8-d13e-4063-ab00-99300cf4df84)


I opened the `minimal.exe` in [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) and there it was: `lua51.dll`. Removing that from my **PATH** made things work the way I expected (just crash):
![image](https://github.com/khvzak/mlua/assets/77458451/b3fb69b2-6c10-49c6-be6e-3c008cde4dab)


Sorry for the confusing issue. I'll mark as closed. If I figure out a way to run on windows the unix way (symbols are taken from the main app that loads module), I'll add it here.

**Comment by khvzak** [comment]
> Do you know if, on windows, there is a way to make modules loadable from vendored? I think I want to use this the unix way, but on windows.

Unfortunately this is a Windows platform limitation. Otherwise I would already add this feature to mlua. 
I believe pyo3 works on the same way (when making python modules in Rust).

**Comment by tobii-dev** [comment]
> Unfortunately this is a Windows platform limitation. Otherwise I would already add this feature to mlua. I believe pyo3 works on the same way (when making python modules in Rust).

Ah that is a shame. I'll just pass on the lua51.dll then.
Thanks for the quick help!
