### ISSUE TITLE
Use of Arc<Mutex<...>> for non-send builds?

### ISSUE THREAD

**Issue by j-hui** [khvzak/mlua#315]
I'm hacking around the implementation to see if I can get mlua working on embedded (core+alloc) platforms (related: #90).

I noticed that mlua uses `Arc<Mutex<...>>` for a few internal data structures, in particular the `registry_unref_list`. This is problematic for embedded platforms, which don't have an `std` implementation of `Mutex`.

At least for embedded builds, I'm planning on downgrading these to `Rc<RefCell<...>>` (essentially reverting 7b0e4b4).

But I was wondering why these were made `Arc<Mutex<...>>` in the first place, when built without the `send` feature? Is there any particular situation during single-threaded execution where blocking is actually needed for this list? (If so, I might use locks from the [`spin`](https://docs.rs/spin/0.5.2/spin/index.html) crate instead.)

**Comment by khvzak** [comment]
> why these were made `Arc<Mutex<...>>` in the first place

`registry_unref_list` is used inside [`RegistryKey`](https://docs.rs/mlua/latest/mlua/struct.RegistryKey.html) struct which itself represents an integer key generated by Lua. The unref list is used to return back to Lua dropped keys. The `RegistryKey` is `Send+Sync` and can be moved/dropped in any thread without restictions. (regardless of `send` feature flag).
You can change it to `Rc<RefRefCell>` (and lose ability to send keys to other threads).
