### ISSUE TITLE
Error loading mlua module from mlua runtime

### ISSUE THREAD

**Issue by iovis** [khvzak/mlua#323]
Hi! I'm probably doing something dumb, but I can't figure out what I'm doing wrong.

I was playing around with the crate in this repo: https://github.com/iovis/rust_lua

The last step I was trying out was creating a lua module ([string_utils](https://github.com/iovis/rust_lua/tree/master/string_utils) in the repo) and using it in the lua runtime ([main.rs](https://github.com/iovis/rust_lua/blob/master/src/main.rs) and [init.lua](https://github.com/iovis/rust_lua/blob/master/lua/init.lua#L84-L100)). Running `just` will compile and run.

When I call it from rust, I get this error when doing `require("string_utils")`:
```
Error: runtime error: error loading module 'string_utils' from file './lua/string_utils.so':
        ./lua/string_utils.so:1: '=' expected
stack traceback:
        [C]: in ?
        [C]: in ?
        [C]: in function 'require'
        [string "src/main.rs:173:9"]:88: in main chunk
```

But if I do `luajit -e 'print(require("string_utils").is_empty("nonempty"))`, it works beautifully.

I haven't been able to find any similar errors in the issues, so I'm not sure what I'm doing wrong

**Comment by khvzak** [comment]
Did you create Lua instance with [`unsafe_new()`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.unsafe_new)?

Also you need Lua symbols to be exported, see [FAQ](https://github.com/khvzak/mlua/blob/master/FAQ.md#loading-a-c-module-fails-with-error-undefined-symbol-lua_xxx-how-to-fix)

**Comment by iovis** [comment]
> Did you create Lua instance with [`unsafe_new()`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.unsafe_new)?

Yup! 
https://github.com/iovis/rust_lua/blob/master/src/main.rs#L52

> Also you need Lua symbols to be exported, see [FAQ](https://github.com/khvzak/mlua/blob/master/FAQ.md#loading-a-c-module-fails-with-error-undefined-symbol-lua_xxx-how-to-fix)

I did see that and tried with those flags (not currently shown in the repo), but it failed with the same message.

The module seems to work perfectly fine using `luajit` directly, so I’m guessing it’s something I’m missing on main

**Comment by khvzak** [comment]
I noticed you change only `package.path` but for C modules you need to set [`package.cpath`](https://www.lua.org/manual/5.4/manual.html#pdf-package.cpath)

**Comment by iovis** [comment]
> I noticed you change only `package.path` but for C modules you need to set [`package.cpath`](https://www.lua.org/manual/5.4/manual.html#pdf-package.cpath)

I knew I was doing something dumb, changing the `package.cpath` was the key. Thank you for your time and patience and kudos on an awesome crate!
