### ISSUE TITLE
Really strange lifetime error

### ISSUE THREAD

**Issue by K4rakara** [khvzak/mlua#33]
The following code produces a really strange lifetime error:

```rust
extern crate mlua;

use mlua::prelude::{ * };

pub struct MyStruct<'lua> ( &'lua () );

impl<'lua> LuaUserData for MyStruct<'lua> {}

pub fn init<'lua>(lua: &'lua Lua) -> LuaResult<()> {
    lua.globals().set::<_, MyStruct<'lua>>(
        "my_instance",
        MyStruct ( &() ),
    )?;
    Ok(())
}
```

```
error[E0477]: the type `MyStruct<'lua>` does not fulfill the required lifetime
  --> err_repo.rs:10:19
   |
10 |     lua.globals().set::<_, MyStruct<'lua>>(
   |                   ^^^
   |
   = note: type must satisfy the static lifetime
```

I have no clue why its saying that `MyStruct` isn't a `'static` type. Shouldn't an error like this only occur if `MyStruct` was defined inside of `init`?

**Comment by khvzak** [comment]
The `MyStruct` indeed has non-static lifetime because it's bound to `'lua`.

Let's consider the following examples:
```rust
    pub fn init<'lua>(lua: &'lua Lua) -> Result<()> {
        lua.globals().set::<_, MyStruct>(
            "my_instance",
            MyStruct ( &() ),
        )?;
        Ok(())
    }
```
In this example we remove the bound and compiler explicitly derive `'static` lifetime for `MyStruct`.

In the next example:
```rust
    pub fn init<'lua: 'static>(lua: &'lua Lua) -> Result<()> {
        lua.globals().set::<_, MyStruct>(
            "my_instance",
            MyStruct ( &() ),
        )?;
        Ok(())
    }
```
We're giving a hint to compiler that `'lua` has `'static` lifetime and this also works...

The `'static` requirement for UserData in this example defined  in `ToLua` for an arbitrary `T`:
```rust
impl<'lua, T: 'static + MaybeSend + UserData> ToLua<'lua> for T {
    fn to_lua(self, lua: &'lua Lua) -> Result<Value<'lua>> {
        Ok(Value::UserData(lua.create_userdata(self)?))
    }
}
```

I suppose you're willing to store Lua objects in `MyStruct`? Unfortunately there is not easy way to achieve this :(
One of the possible solutions could be storing Lua object inside a `UserData` using `set_user_value()` and `get_user_value()`.
Or use `named_registry_value`, although it's less faster than using user values.

**Comment by K4rakara** [comment]
So, if I'm understanding correctly, I could manually implement `ToLua` (as long as the struct doesn't implement `UserData`, as that would presumably clash with the existing impl) or use `set_user_value()`/`get_user_value()`?

**Comment by K4rakara** [comment]
I was trying to store lua values in rust in order to avoid having to use user values, as I wanted to use those for metatable extensions, since the `LuaMetaMethod` enum doesn't support custom keys...

**Comment by khvzak** [comment]
> So, if I'm understanding correctly, I could manually implement `ToLua` (as long as the struct doesn't implement `UserData`, as that would presumably clash with the existing impl) or use `set_user_value()`/`get_user_value()`?

That's correct, yes.

The generic requirement for UserData to be `'static` comes from [`TypeId::of::<T: 'static + ?Sized>()`](https://doc.rust-lang.org/std/any/struct.TypeId.html) requirement. It's used to get a **shared** metatable for all UserData of the same type `T`. 
In other words, if you create 1000 UserData::<T> objects, they will have a single metatable. Any modifications made to the metatable will be seen by all these objects.

An alternative approach is to create a new metatable for each UserData object, which is less efficient. For example, this is used in `Scope` UserData variant, where `T` not required to be static.

**Comment by K4rakara** [comment]
Is there any reason why users cannot modify the metatable directly in `UserData::add_methods`? I mean, sure, you need to protect the `__gc` key, but that would be fairly easy to do.

**Comment by khvzak** [comment]
Allowing to add custom keys to metatable at the init stage is ok but probably not enough? I mean also a method to get metatable back is need?

**Comment by K4rakara** [comment]
I'd be down to implement something for that!

Maybe like this:
```rust
impl LuaUserData for MyStruct {
    // Renamed from add_methods
    // Naming it add_methods doesn't make much sense if it also has fields
    // Naming it add_metatable doesn't make much sense if it has any normal methods
    // Probably makes sense to give the user access to Lua and return a result
    fn add_ext<'lua, M>(lua: &'lua Lua, ext: &mut M) -> LuaResult<()>
    where
        M: UserDataExt<'lua, MyStruct>, // Renamed from UserDataMethods
    {
        ext.add_method<_, LuaFunction<'lua>>(
            "some_method",
            |lua: &'lua Lua, self_: &MyStruct, (): ()| -> LuaResult<()> {
                println!("Hello world!");
                Ok(())
            },
        );
        ext.add_field<_, LuaValue<'lua>>(
            "__my_custom_field",
            lua.create_table()?,
        );
        Ok(())
    }
}
```

Although, that would require bumping to the next major release, as that would be an extremely breaking change. It would also make it more difficult to come from rlua to mlua.

As for getting the metatable later, there already appears to be a function that does it `userdata.rs`, its just private.

**Comment by khvzak** [comment]
Could you provide please more information, what  `add_field` is expected to do?

Now it's possible to get or set custom fields in a UserData using the standard `__index` and `__newindex` metamethods:
```rust
    struct MyUserData;

    impl MyUserData {
        fn get_extra_data<'lua>(lua: &'lua Lua, data: AnyUserData<'lua>) -> Result<Table<'lua>> {
            match data.get_user_value::<Option<Table>>()? {
                Some(t) => Ok(t),
                None => {
                    let t = lua.create_table()?;
                    data.set_user_value(t.clone())?;
                    Ok(t)
                }
            }
        }
    }

    impl UserData for MyUserData {
        fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
            methods.add_meta_function(MetaMethod::Index, |lua, (data, index): (AnyUserData, mlua::String)| {
                Self::get_extra_data(lua, data)?.raw_get::<_, Value>(index)
            });

            methods.add_meta_function(MetaMethod::NewIndex, |lua, (data, index, val): (AnyUserData, mlua::String, Value)| {
                Self::get_extra_data(lua, data)?.raw_set(index, val)
            });
        }
    }

    let lua = Lua::new();
    let globals = lua.globals();
    globals.set("ud", lua.create_userdata(MyUserData)?)?;
    lua.load(
        r#"
        ud.my_custom_field = 123
        assert(ud.my_custom_field == 123)
    "#,
    )
    .exec()?;
```

Or do you want to store custom fields in a metatable? Could you provide more use cases please?

**Comment by K4rakara** [comment]
`add_field` would add a new field to the metatable, rather than adding a field on the userdata itself using `__index`.

Why do this? Some Lua programs add custom meta methods, such as `__next`, by overriding the lua built in functions. Some users (particularly ones that are making modules) may wish to provide these in the case that an override is in use. In my case, I'm making a library to add additional syntax sugar to lua through things it already has, such as single argument function calls (think `print "hello world"`).

Heres a more appropriate example:

```rust
pub struct MyStruct;

impl UserData for MyStruct {
    fn add_ext<'lua, E>(ext: &mut E) -> Result<()>
    where
        E: UserDataExt<'lua, MyStruct>
    {
        ext.add_field("__type_name", "my_struct")?;
        Ok(())
    }
}

let lua = Lua::new();
let globals = lua.globals();

let type_fallback = globals.get::<_, Function>("type");

fn type_<'lua>(lua: &'lua Lua, value: Value<'lua>) -> Result<String<'lua>> {
    match value {
        Value::UserData(value) => {
            let metatable = value.get_metatable()?;
            if let Some(type_name) = metatable.get::<_, Option<String<'lua>>>("__type_name")? {
                Ok(type_name)
            } else {
                Ok(lua.create_string("userdata")?)
            }
        },
        _ => type_fallback.call(value),
    }
}

globals.set("type", lua.create_function(type_)?)?;

globals.set("my_struct", lua.create_userdata(MyStruct)?)?;

lua
    .load(r#"
        assert(type(my_struct) == "my_struct")
    "#)
    .exec()?;

```

**Comment by khvzak** [comment]
This is a good point. I think I'll include this new functionality to the next release (likely keeping API backward compatibility, which is a high priority and keeps me moving towards stabilising api and 1.0 release).
I'm currently working on (proc) macros to make user experience more easy and reduce boilerplate code (eg. `#derive(UserData)`, and much more).

**Comment by khvzak** [comment]
I pushed a change to the `dev` branch with new functionality:
https://github.com/khvzak/mlua/blob/dev/tests/userdata.rs#L352
```rust
    struct MyUserData(i64);

    impl UserData for MyUserData {
        fn add_fields<'lua, F: UserDataFields<'lua, Self>>(fields: &mut F) {
            fields.add_field_method_get("val", |_, data| Ok(data.0));
            fields.add_field_method_set("val", |_, data, val| {
                data.0 = val;
                Ok(())
            });

            fields.add_meta_field_with("__type_name", |_lua| Ok("MyUserData"));
        }
    }
```
Basically a new `UserDataFields` is added together with `UserDataMethods`. It allows to manipulate fields (a wrapper around `__index` and `__newindex` metamethods), plus custom metamethods and a safe way to get a UserData metatable via `data.get_metatable()`

**Comment by K4rakara** [comment]
Awesome! I'll give this a shot tomorrow!
