### ISSUE TITLE
Add a custom variant to the Value enum

### ISSUE THREAD

**Issue by coderedart** [khvzak/mlua#330]
the `Value` enum is actually pretty large in size.  It will be *atleast* 16 bytes in size, because `Number` or `LightUserData` variant's payload is already 8 bytes.  So, that gives us atleast `15` bytes of free space that can be used for passing around custom data inaccessible to lua scripts. I know i can use `LightUserData` variant too, but its just 8 bytes pointer, which will waste the remaining 7 bytes. 

When `vector4` feature is enabled, it will take *atleast* 24 bytes as 16 bytes will be taken up by 4 floats, which will allow `23` bytes for usage. 

### Example usecase
1. passing short strings
2. passing array bytes
3. something else that you don't want lua scripts to access, but still can be passed to host functions.

### Error variant's size
Now, in reality, due to `Error` variant, `Value` enum takes up `76` :scream: bytes. So, that's `75` bytes of wasted space. That is larger than the common 64 bytes cache line size. so, if possible, `Error` variant should either be boxed or reduced in size somehow. but that is not the main focus of the issue though. Whatever the size of `Value` enum, having a custom variant like

```rust
enum Value {
	Number(f64),
	//.. rest of the variants
	Custom( [u8; 15] ) // assuming the ideal size of 16 bytes value enum
}
```

**Comment by khvzak** [comment]
Thanks, I'll think about it. The only problem is passing `Custom` variant Into/From Lua will always go through userdata creatio, so in practice there will be no difference between UserData and Custom (rather more complicated to track an additional type tag (see how Error work))

PS I agree that it's a good idea to reduce `Value` side.

**Comment by coderedart** [comment]
ah, i didn't think about the backend lua not supporting a custom variant in Value type. Making it UserData would be pointless as i wanted to avoid GC or metatables overhead and provide simple `Copy` value semantics to temporary data. eg: UUIDs or 16 byte keys from generation arena crates or fat pointers (`&mut [T]`) etc..
