### ISSUE TITLE
Question about saving and accessing data on chunk

### ISSUE THREAD

**Issue by InZan123** [khvzak/mlua#332]
Hello!

So for context, I wanted to be able to load other lua files from a lua file itself and I'm having a bit of trouble doing that. 

I made a global function to do that given a path. Only problem with this is that it doesnt know where the lua file that called the function is located and so you cant type in stuff like "./other.lua" and have it find it in the same directory. I named the chunk to be the location of the file and I tried to access the chunks name in the function but I couldn't find a way to do that.

Is there any way to save data that is specific for a chunk and then access it in a global function? Or should I approach this differently?

**Comment by khvzak** [comment]
> I wanted to be able to load other lua files from a lua file itself

Hmm, there is a [`require`](https://www.lua.org/manual/5.4/manual.html#pdf-require) function exactly for this. It uses configurable loaders and by default can load files using [`package.path`](https://www.lua.org/manual/5.4/manual.html#pdf-package.path)

> Is there any way to save data that is specific for a chunk and then access it in a global function?

You could try setting chunk [envrinment](https://docs.rs/mlua/latest/mlua/struct.Chunk.html#method.set_environment) with a specific variable to refer to a path. It always will be chunk-local (uniq).

**Comment by InZan123** [comment]
Chunk environment might've been what I was looking for. Thank you for your answer!
