### ISSUE TITLE
[Module Mode] undefined symbol: luaopen_librust_module

### ISSUE THREAD

**Issue by flea1lt** [khvzak/mlua#333]
When attempting to run the module mode example in the [mlua repository](https://github.com/khvzak/mlua/tree/master/examples/module), it was observed that the dynamic symbol name is incorrect on Linux, leading to an error.

## Steps to Reproduce
1. Build the shared library `rust_module`
```
cargo build --features="luajit" 
```
This will generate a .so file named `librust_module.so`

2. Load the .so file in LuaJIT:
```
LUA_CPATH=~/mlua/examples/module/target/debug/?.so luajit -e 'print(require("librust_module").sum(1,2))'
```
This results in the following error:
```
luajit: error loading module 'librust_module' from file '/home/flea/mlua/examples/module/target/debug/librust_module.so':
        /home/flea/mlua/examples/module/target/debug/librust_module.so: undefined symbol: luaopen_librust_module
stack traceback:
        [C]: at 0x7f99fdf2a850
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x55da59080cd0

```
3. Use `nm` command to check the dynamic symbols
```
nm -D target/debug/librust_module.so
```
Output looks like:
```
...
000000000000f620 T luaopen_rust_module
                 U lua_pcall
                 U lua_pushboolean
                 U lua_pushcclosure
                 U lua_pushfstring
                 U lua_pushinteger
...
```
The output reveals that the symbol name is luaopen_rust_module, whereas LuaJIT expects luaopen_librust_module.

## Possible solutions
Not sure which is the best way, but each works.
- Rename the .so file directly
```
mv target/debug/librust_module.so target/debug/rust_module.so
```
OR 
- Try to add lib prefix at the rust code, change the name rust_module to librust_module at https://github.com/khvzak/mlua/blob/master/examples/module/src/lib.rs#L12C4-L12C4

OR
- Add lib prefix at [lua_module macro](https://github.com/khvzak/mlua/blob/master/mlua_derive/src/lib.rs#L53)
```
- let ext_entrypoint_name = Ident::new(&format!("luaopen_{module_name}"), Span::call_site());
+ let ext_entrypoint_name = Ident::new(&format!("luaopen_lib{module_name}"), Span::call_site());
```

## Related Issue
#88

**Comment by khvzak** [comment]
Lua modules usually named without `lib` prefix (when distributed) so changing mlua code/macros potentially will have bad impact than good.
The best strategy is
1) As you mentioned, rename module and strip `lib` prefix
2) Update `CPATH` to incorporate `lib` prefix:
```
LUA_CPATH=~/mlua/examples/module/target/debug/lib?.so luajit -e 'print(require("rust_module").sum(1,2))'
```

**Comment by flea1lt** [comment]
Thanks a lot for your advice!
