### ISSUE TITLE
[Question] Mass-registration of functions / equivalent of luaL_register?

### ISSUE THREAD

**Issue by mcclure** [khvzak/mlua#34]
(This is a support request more than an "issue". If there is a better place to ask mlua questions I'd be happy to go there. I am new to both mlua and Rust. Thanks.)

In the Lua C library there is a function [luaL_register](https://pgl.yoyo.org/luai/i/luaL_register) that allows you to load many functions into a table at once, usually package.preload. This is useful for loading an entire C API into Lua all at once. Example:

<img width="509" alt="Screen Shot 2021-02-20 at 2 58 32 PM" src="https://user-images.githubusercontent.com/277318/108607086-23501a80-738c-11eb-959f-f869595aff6a.png">

What would be the closest mlua equivalent to this? I am looking over the docs and don't see anything specific.

My intuition is "oh, I will just make an array, and iterate over the array calling create_function". But then I run into interesting difficulties with the fact I cannot really store a heterogenous array of functions with different signatures into a single variable to iterate over, and it also seems I cannot easily create an array of mlua:;Function objects (at least, not in its own module) because of Rust rules about storing unsafe/thread-global mutable data into a static.

I'm sure I will figure something out, but I wonder, is there a "best practices" mlua pattern for this?

**Comment by khvzak** [comment]
Your intuition is completely right :) 
As in the [example](https://github.com/khvzak/mlua/blob/master/examples/module/src/lib.rs#L13), you could just return a table of functions, that Lua will cache into `package.loaded[modname]` when loading your module using [`require`](https://www.lua.org/manual/5.3/manual.html#pdf-require)
```rust
fn func1(_: &Lua, _: ()) -> LuaResult<()> {
    Ok(())
}

fn func2(_: &Lua, _: ()) -> LuaResult<()> {
    Ok(())
}

#[mlua::lua_module]
fn rust_module(lua: &Lua) -> LuaResult<LuaTable> {
    lua.create_table_from(vec![
        ("func1", lua.create_function(func1)?),
        ("func2", lua.create_function(func2)?),
    ])
}
```
Inside init function in your module you also have access to globals and can additionally register your data.

**Comment by mcclure** [comment]
Thanks for the sample code— maybe I will attempt to write a macro, if I do this maybe I will check back about whether you would like it upstream as a PR.

**Comment by mcclure** [comment]
Thanks. As a piece of feedback, I am looking at the [mlua docs](https://docs.rs/mlua/0.5.1/mlua/) and I don't see any docs for lua_module, nor do I see docs for the "module" or "mlua_derive" features. Is there a doc somewhere I am missing? Could docs for the correct usage of lua_module be added?

**Comment by mcclure** [comment]
Oh, sorry, I see there are some docs in the README. Though it still doesn't seem to explain exactly what #lua_module does.

**Comment by mcclure** [comment]
Okay, I think I've figured out that "standalone mode" is building a normal exe with mlua and "module mode" is building a shared object to be loaded by Lua.

I think the README would be clearer if you added a sentence under "Module mode" such as

"Use this mode to create a compiled Lua module that can be loaded from Lua code using `require`."

**Comment by khvzak** [comment]
Thanks for the feedback!
I agree that documentation need to be updated. In future I'll publish a detailed manual to cover usage / options / examples.

**Comment by khvzak** [comment]
I updated README
