### ISSUE TITLE
Link fails on windows in module mode

### ISSUE THREAD

**Issue by estokes** [khvzak/mlua#343]
I'm trying to build a loadable dll to expose functionality to lua embedded in another program (DCS). I'm using module mode,

`crate-type = ["cdylib"]`
...
`mlua = { version = "0.9.1", features = ["lua51", "module", "serialize"] }`

I've set my environment up as such,

```
$env:LUA_LIB="C:\\Program Files\\Eagle Dynamics\\DCS World\\bin"
$env:LUA_LIB_NAME="lua"
$env:LUA_LINK="dylib"
```

When I try to build, LINK.EXE fails. I'll spare you the entire link.exe line, but the salient error is,

```
= note: LINK : fatal error LNK1181: cannot open input file 'lua.lib'
```

I don't know why it's trying to link to the static lua library, which indeed doesn't exist, If I understand the environment variables I've set correctly I've told it to link to the dynamic library.

Further, I can build a working DLL using msys2 and the mingw64 rustc with the exact same environment configuration (just translated to bash obviously). I'm far from a windows guru, so maybe I'm missing something obvious here.

**Comment by estokes** [comment]
I've tried a few more things after reading the build.rs. If I don't specify `LUA_LIB_NAME` then the link does not fail, and the resulting dll is linked to lua51.dll according to ldd. I guess 99% of the time this is fine, but Eagle Dynamics, in their infinite wisdom, decided to call their build of lua51.dll "lua.dll", so obviously my dll fails to load at runtime.

However, if I make a symbolic link from their lua.dll -> lua51.dll then it works as expected (and exactly the same as the mingw64 version).  So it's something about the library rename functionality that has gone wrong and told link.exe to link to a static library instead of the dll.

**Comment by khvzak** [comment]
> I don't know why it's trying to link to the static lua library, which indeed doesn't exist, If I understand the environment variables I've set correctly I've told it to link to the dynamic library.

You cannot link directly to dll in windows. You need to have `lua.lib` file with exported symbols from lua.dll. This is what the environment variables about. They configure mlua to use a custom lib file to link with.

See also https://stackoverflow.com/questions/9946322/how-to-generate-an-import-library-lib-file-from-a-dll

>  if I make a symbolic link from their lua.dll -> lua51.dll then it works as expected

Yeah, this is a good workaround actually. Alternatively If you want to link with lua.dll, you can try to export symbols and create .lib file (see SO link)

**Comment by estokes** [comment]
Thanks a lot, sorry to waste your time.
