### ISSUE TITLE
Turning a reference to a `Lua` struct into `*mut ffi::lua_State`

### ISSUE THREAD

**Issue by Delta-official** [khvzak/mlua#349]
I've been looking at the code and docs for half an hour at this point and I can't seem to find a way to turn a reference to a `Lua` struct into a `ffi::lua_State` pointer. Is there anything I'm missing?

**Comment by khvzak** [comment]
The best way to obtain and operate on `*mut ffi::lua_State` pointer is to [create a C function](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_c_function) to use the `ffi` low level interface.
