### ISSUE TITLE
[Question] Storing a Lua value of unknown type into a variable?

### ISSUE THREAD

**Issue by mcclure** [khvzak/mlua#35]
(This is a support request more than an "issue". If there is a better place to ask mlua questions I'd be happy to go there. I am new to both mlua and Rust. Thanks.)

So I am looking over the docs and example code and I see I can pull a value out of a Lua table or out of `globals` by calling get() and typing it:

`let package:LuaTable = globals.get("package")?;`

But I can't do this without typing the variable. If I just say:

`let package = globals.get("package")?;`

…that is a compile error. I haven't tested but I assume (?) the type is checked when I get() and if I say something incorrect, like `let package:String = globals.get("package")?;` where `package` turns out to be a table at runtime, this will be a runtime error.

Let's say I want to store a Lua value in a variable _without caring what the type is_. Like say I want to say

```
let abcd = globals.get("abcd")?;
globals.set("efgh", abcd)?;
```

In this case I do not actually "look inside" the abcd value, I just want to copy it from one Lua name to another. Is there a type I can use in that case?

(I think `any` will work, but my understanding— I am new to this— is that `any` is literally _any_ type, including Rust types, but I am wanting to stay within the bounds of types that mlua can bind to Lua values.)

**Comment by khvzak** [comment]
You could use [`mlua::Value`](https://docs.rs/mlua/0.5.1/mlua/enum.Value.html) for this, eg:
```rust
use mlua::Value;

let package: Value = globals.get("package")?;
```

**Comment by mcclure** [comment]
This answers my question thank you
