### ISSUE TITLE
Using borrowed values in multi function argument

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [khvzak/mlua#353]
Assume the following struct, which can be cloned, but it might be expensive to do so:
```
pub struct Foo {
    bar: String,
    baz: u32,
}
```
`Foo` implements `UserData`, so it can be passed to a lua function without converting it into a lua table first.

Now assume the following two functions: `PreQuery`, which takes a single object of type `Foo` and returns a `bool` and `Query`,  which takes an object of type `Foo` and a vector of `String`. I want to do the following:

```Rust
// Get "PreQuery" and "Query" from globals() here
let foo_lua = foo.into_lua(&lua).unwrap();

let do_query: bool = pre_query_func.call(&foo_lua ).unwrap();

// Do some other stuff
if do_query {
    let selector = vec!["bar", "baz"];
    let query_result: (String, bool) = query_func.call((&foo_lua, selector));

    dbg!(query_result);
}
```

However, now I get "the trait `LuaUserData` is not implemented for `&Foo`" for the call to `pre_query_func` and "the trait `IntoLuaMulti<'_>` is not implemented for `(&Book, Vec<&str>)`" for the call to `query_func`.

The documentation is not entirely clear on this, but I suspect this has something to do with the lifetimes issue mentioned in: https://github.com/khvzak/mlua/blob/bf79d6c212662b4cb9ade599383e8419ba01213c/examples/guided_tour.rs#L190

Is this correct? How would I use borrowed values in lua functions? As I said, cloning `Foo` is possible, but usually expensive.

**Comment by khvzak** [comment]
There are few options available how to borrow userdata value without clonning it.

1) Use [`UserDataRef<T>`](https://docs.rs/mlua/latest/mlua/struct.UserDataRef.html) or [`UserDataRefMut<T>`](https://docs.rs/mlua/latest/mlua/struct.UserDataRefMut.html) helpers to receive parameters (where `T` is your userdata struct). They implement `Deref<Target = T>` and `DerefMut<Target = T>`.

2) Use [`AnyUserData`](https://docs.rs/mlua/latest/mlua/struct.AnyUserData.html) handle and then borrow `T` using [`AnyUserData::borrow`](https://docs.rs/mlua/latest/mlua/struct.AnyUserData.html#method.borrow) or [`AnyUserData::borrow_mut`](https://docs.rs/mlua/latest/mlua/struct.AnyUserData.html#method.borrow_mut)

The 1st method is preferrable as can generate a nice error message in case of messing up with functions passed arguments.

**Comment by Ruhrpottpatriot** [comment]
How would I wrap a custom type that implements `UserData` into a `LuaUserDataRef<T>` (I assume that's what you mean because my 0.9.1 doesn't have `UserDataRef<T>`

**Comment by khvzak** [comment]
> How would I wrap a custom type that implements `UserData` into a `LuaUserDataRef<T>` (I assume that's what you mean because my 0.9.1 doesn't have `UserDataRef<T>`

Full example:

```rust
use mlua::{Lua, Result as LuaResult, UserData, UserDataRef};

pub struct Foo {
    bar: String,
}

impl UserData for Foo {}

fn main() -> LuaResult<()> {
    let lua = Lua::new();

    let func = lua.create_function(|_, foo: UserDataRef<Foo>| {
        println!("foo.bar = {}", foo.bar);
        Ok(())
    })?;

    lua.globals().set("func", func)?;
    lua.globals().set("foo", Foo { bar: "bar123".into() })?;

    lua.load("func(foo)").exec()
}
```

**Comment by Ruhrpottpatriot** [comment]
I assume this doesn't work with lua function that are not defined in rust? E.g.

```
pub struct Foo {
    bar: String,
}

impl UserData for Foo {}

fn main() {
    let lua = Lua::new();
    lua.load("./path/to/script.lua").exec().unwrap();
    
    // This function is defined in the script.lua file as:
    // function QueryMetadata(foo)
    let query_func: LuaFunction = self.lua.globals().get("QueryMetadata").unwrap(); 

    let foo = Foo { bar: "bar123".into() }).unwrap();
    let foo_ud = book.into_lua(&self.lua).unwrap(); // Can this be converted into UserDataRef<Foo>?

    let result: Metadata = query_func.call(foo_ud).unwrap();
    dbg!(result);
```

**Comment by khvzak** [comment]
It should work for any case. Lifetimes are guaranteed by Lua garbage collector.
You can convert `AnyUserData` into `UserDataRef`:
```rust
let foo = Foo { bar: "bar123".into() }.into_lua(&lua)?; // AnyUserData
let foo_ref = UserDataRef::<Foo>::from_lua(foo, &lua)?; // UserDataRef
```

You can also clone `AnyUserData` and pass it to Lua function. Cloning it will only increase a number of reference for GC without deep cloning underlying data.

**Comment by Ruhrpottpatriot** [comment]
Not that it really matters: But there's no way to do this except the additional indirection via `AnyUserData`?

**Comment by khvzak** [comment]
> Not that it really matters: But there's no way to do this except the additional indirection via `AnyUserData`?

I'm not sure what do you mean? If you have a direct refence to your object in Rust, you don't need `AnyUserData`. If you cross Lua boundary and move object into lua, then Lua is responsible for maintaining object lifetimes, running destructions, etc. In this case `AnyUserData` is a handle to your object inside Lua with `'lua` lifetime.

**Comment by Ruhrpottpatriot** [comment]
Sorry, had a little brainfart. I totally forgot that I need to convert an object into lua anyway. I was just thinking if I could directyl create a `UserDataRef` from a PORO.

**Comment by Ruhrpottpatriot** [comment]
@khvzak Sorry to dig this out again, but I tried to get the above to work in the last few days to no avail. Here's the current code:

```
struct Book {
    title: String,
    author: String,
    // Other fields
}

fn query(&self, book: &Book, field_names: Vec<String>) -> Result<(Option<Metadata>, Option<Vec<String>)> {
    let book_ud = book.clone().into_lua(&self.lua)?;
    let fields_ud = field_names.clone().into_lua(&self.lua)?;

    let pre_query_func: Option<LuaFunction> = self.lua.globals().get("PreQueryMetadata")?;
    let query_book = match pre_query_func {
        Some(func) => func.call((book_ud.clone(), fields_ud.clone()))?,
        None => true,
    };

    if !query_book {
        return Ok((None, Some(field_names)));
    }

    let query_func: LuaFunction = self.lua.globals().get("QueryMetadata")?;
    let result: HashMap<String, String> = query_func.call((book_ud.clone(), fields_ud.clone(), data))?;

    let post_query_func: Option<LuaFunction> = self.lua.globals().get("PostQueryMetadata")?;
    let Some(post_query_func) = post_query_func else {
        return Ok((Some(result), None));
    };
    
    let (keep, dirty_fields): (bool, Vec<String>) = post_query_func.call((book_ud.clone(), result.clone()))?;

    // Do some non lua related stuff to decide which fields to keep and which to discard
    Ok((Some(result), None)
}
```
The problem I have with this code is that the `query` function borrows a book, which I then convert into a userdata struct by first _cloning_ it and then calling `into_lua`. The same is done for the field_names parameter. Then I pass the two userdata variables to the lua functions, again by _cloning_ both values. This means the entire function clones the relevant objects _eight_ times.
If I leave out the `clone()`s in the lua method calls I get
>use of moved value: `book_ud`

and 
> use of moved value: `fields_ud`

for each of the three lua-method calls. If I do 
```
let book_ud = book.clone().into_lua(&self.lua)?;
let book_ref = LuaUserDataRef::<Book>::from_lua(book_ud, &self.lua)?;

let fields_ud = field_names.clone().into_lua(&self.lua)?;
let fields_ref = LuaUserDataRef::<Vec<String>>::from_lua(fields_ud, &self.lua)?;
```
I get 
> the trait bound `(UserDataRef<'_, Book>, UserDataRef<'_, Vec<std::string::String>>): IntoLuaMulti<'_>` is not satisfied

at each of the three lua-function calls.



Is there any possibility to avoid cloning the parameters and just borrow?

**Comment by khvzak** [comment]
You need to use [Lua::scope](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.scope) helper to pass references to Lua without any cloning.

A very simplified example how to create userdata from `&Book` reference:

```rust
struct Book {
    title: String,
    author: String,
}

impl mlua::UserData for Book {
    fn add_fields<'lua, F: mlua::UserDataFields<'lua, Self>>(fields: &mut F) {
        fields.add_field_method_get("title", |lua, book| lua.create_string(&book.title));
        fields.add_field_method_get("author", |lua, book| lua.create_string(&book.author));
    }
}

fn query(lua: &mlua::Lua, book: &Book) -> mlua::Result<()> {
    lua.scope(|scope| {
        let book = scope.create_userdata_ref(book)?;
        lua.load(
            r#"
            local book = ...
            print(book.title, book.author)
        "#,
        )
        .call(book)
    })
}

fn main() -> mlua::Result<()> {
    let lua = mlua::Lua::new();
    let book = Book {
        title: "The Hobbit".to_string(),
        author: "J.R.R. Tolkien".to_string(),
    };
    query(&lua, &book)
}
```

**Comment by khvzak** [comment]
Actually the upcoming mlua version will take `&ud` (reference to `AnyUserData`/etc) as function argument even without clonning.

**Comment by Ruhrpottpatriot** [comment]
Using a scope works. Thanks! 
Last question: Since `Vec<T>` doesn't implement `UserData` I can't use `scope.create_userdata_ref`. Is there any way to the same I did with `Book` with `Vec<String>`?
