### ISSUE TITLE
Using async without automatic stream behavior

### ISSUE THREAD

**Issue by filiptibell** [khvzak/mlua#360]
Hi, I am currently doing some experiments with integrating the `smol` async runtime, `async` mlua feature, and letting users spawn and manage threads in user code. After some fiddling with lifetimes the following code now runs great and very fast:

```lua
for i = 1, 5 do
	print("iteration " .. tostring(i) .. " of 5")

	local counter = 0
	for j = 1, 10_000 do
		spawn(function()
			wait(0.5)
			counter += 1
			if counter == 10_000 then
				print("completed iteration " .. tostring(i) .. " of 5")
			end
		end)
	end

	wait(0.25)
end
```

In this case `spawn` accepts a function arg, adds it to smol executor as an mlua `AsyncThread`, and it will keep running in the background and we can spawn an arbitrary amount of threads up until stack limits. `wait` is a basic `sleep(duration).await` in an mlua async function. This works great.

However, this type of user code does not work, because mlua will automatically resume at `coroutine.yield` when using the `async` feature:

```lua
for i = 1, 5 do
	print("iteration " .. tostring(i) .. " of 5")
	local thread = coroutine.running()

	local counter = 0
	for j = 1, 10_000 do
		spawn(function()
			wait(0.1 * math.random())
			counter += 1
			if counter == 10_000 then
				print("completed iteration " .. tostring(i) .. " of 5")
				spawn(thread)
			end
		end)
	end

	coroutine.yield()
end
```

I have looked at the docs and also mlua source code but could not figure out how to make this work, without getting rid of native `async` feature or having to change user code somehow. Is there currently any way to disable this "automatic resume" behavior? If not, can that be added?

For reference, [lune](https://github.com/lune-org/lune) implements its own async scheduler and can not use mlua `async` feature for this one and only reason. It currently leads to very bad performance, having to leak `Lua` to be `'static`, and difficult to solve race conditions/bugs.

For the full repo and runnable example it is here: https://github.com/filiptibell/luau-scheduler-experiments

**Comment by khvzak** [comment]
What would be your expected behavior at the `coroutine.yield()` point?

Actually the [`AsyncThread`](https://docs.rs/mlua/latest/mlua/struct.AsyncThread.html#) implements `Feature` and `Stream` traits.
You can use `Stream` interface to suspend execution at `coroutine.yelp` point untill calling `poll_next` again.

Also you can convert `AsyncThread` into oneshot future using the [`StreamExt::into_future`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.into_future) helper to stop at Lua yield point.

**Comment by filiptibell** [comment]
I think the current behavior is expected since it is designed this way and the documentation is clear.
But I would like to be able to do something like:

1. From rust, await on an async thread
2. Now mlua will start running until it encounters a yield
- 2a. If the yield is from a `create_async_function`, mlua will manage it, and resume lua when that future result is ready, and keep doing it if multiple async functions are called
- 2b. If the yield is from lua (user code manually calling `coroutine.yield()`), mlua will do nothing, it is the lua codes responsibility to resume it
3. Back in rust, now the thread ran all the way to the end (including mlua async functions), or, it yielded manually from user code

Right now there is a bit of a conflict, I can choose to have behavior 2a **or** 2b but not both. I don't care if the user manually calls `coroutine.yield` or to inspect those values from rust. If the user yields without ever resuming, this would be like a `std::future::pending()` and just never poll ready. But I would like mlua to automatically run mlua async functions and resume their respective lua thread(s).

**Comment by khvzak** [comment]
> is the lua codes responsibility to resume it

How exactly lua should resume this, if coroutines and async function are complitely transparent? 

Also, to make it more clear, could you explain desired behaviour from the end users (lune users) perspective and what exact problem are you trying to solve (not technical problem, rather business problem).

**Comment by filiptibell** [comment]
Sorry, I'll try and make it more clear. Here is an example of how the scheduler works in the Roblox engine and what we are replicating for users in lune also.

```lua
local httpService = game:GetService("HttpService")

local mainThread = coroutine.running()
print("1 - inside a main thread")

local spawnedThread = task.spawn(function()
    print("2 - inside new scheduler spawned thread")
    local someResult = httpService:RequestAsync("https://google.com")
    print("4 - request completed")
    coroutine.resume(mainThread, someResult)
end)

print(coroutine.status(spawnedThread)) -- suspended

print("3 - task.spawn ran until yield and will resume on its own when async fn is done")
local someResult = coroutine.yield()
print("5 - main thread was resumed from other thread which ran async fns")

print(coroutine.status(spawnedThread)) -- dead
```

this spawning pattern is useful because it gives users the power to control resumption and yielding even when using async fns that take control:

```lua
-- main thread starts
task.spawn(function()
    someMaybeAsyncFnWeDontKnow()
end)
-- main thread keeps running and user can be sure of this,
-- even if it spawned some async in the background, or maybe
-- what we spawned wasn't even async, main thread doesn't care
```

large user libraries such as [Lua Promise](https://github.com/evaera/roblox-lua-promise) depend on this behavior and task spawning library. For the first piece of code you can do exactly the same in lune but there is `require("@lune/net")` instead of `httpService`, only difference.

**Comment by filiptibell** [comment]
I think I managed to make a hacky solution for this by extracting the `PENDING` constant and using streams: https://github.com/filiptibell/luau-scheduler-experiments/commit/cd090d877f3082ce5f13721462e2cd50dc95afc3 I wonder if this is correct. When I tried streams but did not compare against the pending value I got strange panics about stack being full but this seems to work.

**Comment by khvzak** [comment]
You should never receive internal mlua pending constant when using `Stream` interface:
The [code](https://github.com/khvzak/mlua/blob/master/src/thread.rs#L471):
```rust
            if nresults == 1 && is_poll_pending(thread_state) {
                return Poll::Pending;
            }
```
prevents this.

So you don't really need the hack to get the constant.

**Comment by khvzak** [comment]
> When I tried streams but did not compare against the pending value I got strange panics about stack being full but this seems to work.

Do you have an example?

**Comment by filiptibell** [comment]
> > When I tried streams but did not compare against the pending value I got strange panics about stack being full but this seems to work.
> 
> Do you have an example?

Yeah - it's just the repo I linked and `cargo run` in debug or release. If you remove the unreachable arm it should happen. As you saw in the `main.luau` it is spawning 50k threads per iteration which should be below the 99k stack slots limit, but I still get:

```
thread 'main' panicked at /Users/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/mlua-0.9.4/src/lua.rs:3592:13:
cannot create a Lua reference, out of auxiliary stack space (used 99999 slots)
```

I also double check and the `PENDING` constant never reaches that match arm, you're right. I was probably imagining this was the solution but in reality there is some other thing happening. This is happening on macOS aarch64 if that matters.

**Comment by khvzak** [comment]
Just tried the code in repo in release and debug mode, no panic (macOS x64 and linux x64).

Do you need to spawn 50k threads? The stack size (100k) is just an arbitrary number, set in [mlua-sys](https://github.com/khvzak/luau-src-rs/blob/main/src/lib.rs#L33). I can make 1M (this is what Lua 5.2+ has).

**Comment by filiptibell** [comment]
> Just tried the code in repo in release and debug mode, no panic (macOS x64 and linux x64).

Yeah was just my fault, edited the comment above.

> Do you need to spawn 50k threads? The stack size (100k) is just an arbitrary number, set in [mlua-sys](https://github.com/khvzak/luau-src-rs/blob/main/src/lib.rs#L33). I can make it 1M (this is what Lua 5.2+ has).

I think a bigger stack size limit would be good, since this is for a general purpose runtime and lune users may have a full http server that spawns long running tasks per request.

For context, all of my testing so far has been in Roblox Studio and the benchmark is to run total 1M threads with sleep/yield as fast as possible. With mlua I needed to split into several iterations (20 * 50k) and in Roblox I did not. So I think they also have the same limit as Lua 5.2+ or even higher.

**Comment by filiptibell** [comment]
It turns out I need to use the pending value after all so I will reopen this and ask if it can be exposed without a hack. Consider the following:

```lua
print(1)
defer(function()
	print(5)
end)
spawn(function()
	print(2)
	coroutine.yield()
	print("unreachable")
end)
spawn(function()
	print(3)
	wait(1)
	print(6)
end)
print(4)
```

To get the correct order `1, 2, 3, 4, 5, 6` I need to call `resume` on thread right away, and if it yields with pending constant, add it to async scheduler to auto resume later. Solved using a similar hack in https://github.com/filiptibell/luau-scheduler-experiments/commit/d3e0d5f8c2ae95f885f62936bbc5630fcdd2808d, would be nice to have access to this constant directly

**Comment by khvzak** [comment]
What you do is quite an interesting trick actually.
I exposed the internal `ASYNC_POLL_PENDING` constant under `Lua::poll_pending()`. It's hidden in doc but feel free to use it.
I'll do a release next week.
