### ISSUE TITLE
linux compile fail... window mac pass

### ISSUE THREAD

**Issue by rhettli** [khvzak/mlua#38]
![屏幕截图 2021-03-13 222644](https://user-images.githubusercontent.com/26317003/111033251-35811e00-844b-11eb-818c-7b1096dab2cc.png)

depin compile fail then i try to compile in docker centos fail too

**Comment by khvzak** [comment]
I fixed it in the `luajit-src-rs` crate. Could you run `cargo update` and try again?

**Comment by rhettli** [comment]
solved,thx
