### ISSUE TITLE
A few questions I have related to including external libraries

### ISSUE THREAD

**Issue by TimUntersberger** [khvzak/mlua#41]
Hello!

First of all I want to really thank you for this awesome library!

How would you go about including `libuv` inside the executable? 
How would you go about including custom lua scripts (something like the neovim runtime) inside the executable?

**Comment by khvzak** [comment]
Hello,
Thanks for the feedback! Sorry for the late response.

> How would you go about including libuv inside the executable?

Could you please provide more details please? Why it could be needed? `libuv` is an async IO library from the C world, whereas in Rust we have awesome [`mio`](https://github.com/tokio-rs/mio).

I also not really sure about custom lua scripts and `mlua`. I mean this a good task for other libraries that depends on `mlua`. `mlua` is designed to provide a generic interface to Lua language/runtime rather than specific applications.

**Comment by TimUntersberger** [comment]
> Why it could be needed?

I am using `mlua` to have lua as my scripting language for an application. `libuv` provides various utility ranging from threads to filesystem functions. I want to include this library so I don't have to implement all of this myself. 

After researching this some more I found out that `neovim` just has a copy of the `libuv.dll` in the production build which then gets included in the `package.cpath`. I probably will also have to do it like this.

**Comment by khvzak** [comment]
> libuv provides various utility ranging from threads to filesystem functions. I want to include this library so I don't have to implement all of this myself.

> After researching this some more I found out that neovim just has a copy of the libuv.dll in the production build which then gets included in the package.cpath. I probably will also have to do it like this.

I'm afraid if `libuv.dll` is not a Lua module, you will need to use FFI and tons of unsafe code to integrate with a C library.
If `neovim` has a runtime (ev loop), you could try to integrate using `mlua` async functionality. 

In a simple way, if `neovim` allows to execute `coroutine.yield()` to switch context, you just can create async functions that uses [`async-std`](https://crates.io/crates/async-std) and they should work.

> This was more meant as a "questions issue". I don't want this to be added to mlua, but I wanted to know how you would go about implementing my usecases.

Ah, sorry, I misunderstood the question :) 
Probably on the of common ways is to a to create lua files and then include them to a binary using [`include_str!`](https://doc.rust-lang.org/std/macro.include_str.html) macro. Lua code can be executed in `mlua` using [`Lua::load`](https://docs.rs/mlua/0.5.4/mlua/struct.Lua.html#method.load)

**Comment by TimUntersberger** [comment]
In the end i just decided to release a zip folder instead of a single executable similiar to neovim which contains lua files and dlls. Instead of libuv I used luv which already has some nice bindings for libuv. Thank you for your time!
