### ISSUE TITLE
How to convert Vec<u8> to Lua string?

### ISSUE THREAD

**Issue by MudcrabDev** [khvzak/mlua#42]
I don't know if this is possible and nothing I've tried works, so I'm asking here.
I'm working on a module that loads binary data as `Vec<u8>`, and I need this data to be available in Lua as a string. (I am working with Love2D which uses binary image data as strings.) I cannot convert it to a Rust String because it would not be valid UTF-8. The closest I can get is `data.to_lua(&lua)` (where data is `Vec<u8>`), but this gives a table.
Is there a way to do this?

**Comment by khvzak** [comment]
Have you tried to use [`lua.create_string`](https://docs.rs/mlua/0.5.4/mlua/struct.Lua.html#method.create_string) method?
It can create a Lua string from any type that implements `AsRef<[u8]>`.

**Comment by MudcrabDev** [comment]
Yes that appears to work with my test code, thank you. If I have further trouble I'll reopen this issue.
