### ISSUE TITLE
Stacktraces are missing (at least on lua 5.2) for LuaErrors

### ISSUE THREAD

**Issue by horazont** [khvzak/mlua#44]
**Description**

When a rust function invoked from Lua returns a `LuaResult` with `Error` variant, no traceback is available on the lua side. This is especially unfortunate when used with the `"module"` feature, because within a larger application making use of the module, it may be hard to pinpoint the source of an error without a traceback.

**How to reproduce**

1. Compile the reproducer code.
2. Enter the `target/debug` directory
3. Run `lua -e 'require "libmlua_error_tb".fun()'` (Note: If you don’t have lua52 as default lua, you may need to change the features in the Cargo.toml accordingly)

**What happens?**

```
$ lua -e 'require "libmlua_error_tb".fun()'
lua: runtime error: fancy error
```

**What should happen instead?**

A proper traceback should be visible, as is the case in the following to other situations:

* When invoking `error` from lua directly:

    ```
    $ lua -e 'error("foo")'
    lua: (command line):1: foo
    stack traceback:
            [C]: in function 'error'
            (command line):1: in main chunk
            [C]: in ?
    ```

* When calling `lua_error` in a C module with a `lua_pushstring` error message. This is using a modified version of https://github.com/norman/hello-lua (lua 5.1 though).

    <details>
    <summary>hello.c</summary>

    ```c
    #include "lua.h"
    #include "lauxlib.h"

    #define MESSAGE "hello world!"

    int say_hello(lua_State *L) {
        lua_pushstring(L, MESSAGE);
        return lua_error(L);
    }

    static const struct luaL_Reg functions [] = {
        {"say_hello", say_hello},
        {NULL, NULL}
    };

    int luaopen_hello(lua_State *L) {
        luaL_register(L, "hello", functions);
        return 1;
    }
    ```

    </details>

    ```
    $ lua5.1 -e 'require"hello"; hello.say_hello(); print("foo")'
    lua5.1: hello world!
    stack traceback:
            [C]: in function 'say_hello'
            (command line):1: in main chunk
            [C]: ?
    ```

**Minimal reproducer**

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "mlua-error-tb"
version = "0.1.0"
authors = ["Jonas Schäfer <j.wielicki@sotecware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.5", features = ["lua52", "module"] }
```
</details>

<details>
<summary>lib.rs (Variant 1: with LuaError::RuntimeError)</summary>

```rust
use mlua::prelude::*;

fn lua_fun<'l>(_: &'l Lua, _: ()) -> LuaResult<String> {
	Err(LuaError::RuntimeError(format!("fancy error")))
}

#[mlua::lua_module]
fn libmlua_error_tb(lua: &Lua) -> LuaResult<LuaTable> {
	let exports = lua.create_table()?;

	exports.set("fun", lua.create_function(lua_fun)?)?;

	Ok(exports)
}
```

</details>

<details>
<summary>lib.rs (Variant 2: with LuaError::ExternalError)</summary>

```rust
use mlua::prelude::*;
use std::fmt;
use std::sync::Arc;
use std::error::Error;

#[derive(Debug)]
struct FancyError();

impl fmt::Display for FancyError {
	fn fmt<'a>(&self, f: &'a mut fmt::Formatter) -> fmt::Result {
		f.write_str("fancy error")
	}
}

impl Error for FancyError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        None
    }
}

fn lua_fun<'l>(_: &'l Lua, _: ()) -> LuaResult<String> {
	Err(LuaError::ExternalError(Arc::new(FancyError{})))
}

#[mlua::lua_module]
fn libmlua_error_tb(lua: &Lua) -> LuaResult<LuaTable> {
	let exports = lua.create_table()?;

	exports.set("fun", lua.create_function(lua_fun)?)?;

	Ok(exports)
}
```

</details>

**Additional thoughts**

I looked into the code and I think this is because mlua pushes a userdata instead of a string as error. I guess the sanest way to fix it would be to capture a traceback when returning the error from `callback_error` in `util.rs` and attach it to the `WrappedError` struct. Then implement `__tostring` in a way which concatenates the traceback with the error message.

To do this, `luaL_traceback` can probably *not* be used because it assembles the traceback using the Lua VM, and may probably call longjmp. So a custom implementation based on a loop of `lua_getstack` and `lua_getinfo` would be required.

I’m gonna experiment with that because I cannot proceed with my module without this, I have no idea where errors are coming from (I’m making a drop-in replacement for a part of [Prosody](https://prosody.im) written in lua, and somewhere I haven’t gotten the API subtleties right yet :)).

**Comment by horazont** [comment]
@khvzak Hey, thanks for your reply. I experimented somewhat in #45. This seems to work fine in my implementation, but I’m just coming back to Rust after a ... seven year break (time flies!).

**Comment by khvzak** [comment]
I found a better way without attaching `Option<String>` to a `WrapperError` and seems it works better
https://github.com/khvzak/mlua/commit/fe39ae09bfe59788934e5d86bc44caa18c62e581
