### ISSUE TITLE
FromLuaConversionError

### ISSUE THREAD

**Issue by sayanarijit** [khvzak/mlua#47]
Hi, I might be doing something wrong, but [following the doc](https://docs.rs/mlua/0.5.4/mlua/trait.UserData.html) when I call `config.version()`[in this experiment](https://github.com/sayanarijit/xplr/commit/df169eb04095e3313098414196d3007cf9aa5375), I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CallbackError { traceback: "stack traceback:\n\tok: in ?\n\tok: in function \'version\'\n\tok:1: in main chunk", cause: FromLuaConversionError { from: "missing argument", to: "userdata", message: None } }', src/app.rs:1461:14
```

<details>
  <summary>Full stack trace</summary>
  <pre>
➜  xplr git:(experiment/lua-integration) RUST_BACKTRACE=full cargo run
warning: unused import: `mlua::prelude::*`
 --> src/app.rs:8:5
  |
8 | use mlua::prelude::*;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::io`
  --> src/app.rs:15:5
   |
15 | use std::io;
   |     ^^^^^^^

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/xplr`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CallbackError { traceback: "stack traceback:\n\tok: in ?\n\tok: in function \'version\'\n\tok:1: in main chunk", cause: FromLuaConversionError { from: "missing argument", to: "userdata", message: None } }', src/app.rs:1461:14
stack backtrace:
   0:     0x55a8348f95e0 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a8348f95e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a8348f95e0 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a8348f95e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a83491cf1c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x55a8348f54e2 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x55a8348fbc55 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a8348fbc55 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a8348fbc55 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x55a8348fb7aa - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x55a8348fc3f1 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x55a8348fbf37 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x55a8348f9a9c - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a8348fbe99 - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x55a83491b621 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x55a83491b443 - core::option::expect_none_failed::h096fa60f757b7204
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
  16:     0x55a83435f94b - core::result::Result<T,E>::unwrap::h470b858911450ecf
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/result.rs:973:23
  17:     0x55a8342e2ba7 - xplr::app::App::create::hef2831627c5aee36
                               at /home/sayanarijit/Documents/GitHub/xplr/src/app.rs:1457:9
  18:     0x55a8342d3bf1 - xplr::main::ha46570f13f262232
                               at /home/sayanarijit/Documents/GitHub/xplr/src/main.rs:24:15
  19:     0x55a8342d284b - core::ops::function::FnOnce::call_once::hb9b31fc0ac524b5a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  20:     0x55a8342d37fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h5310161e1d1c5292
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x55a8342d2c21 - std::rt::lang_start::{{closure}}::h5955f30554ec2377
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:66:18
  22:     0x55a8348fc907 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h78040f802d89ccdc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
  23:     0x55a8348fc907 - std::panicking::try::do_call::h6853cad536dd09a1
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  24:     0x55a8348fc907 - std::panicking::try::h827495f03a9fbb9a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  25:     0x55a8348fc907 - std::panic::catch_unwind::h4bdf17571090eb17
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  26:     0x55a8348fc907 - std::rt::lang_start_internal::h2f319c33bb013f29
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  27:     0x55a8342d2bf7 - std::rt::lang_start::h80802054679dc29e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:65:5
  28:     0x55a8342d417a - main
  29:     0x7fcb76d59b25 - __libc_start_main
  30:     0x55a8342d25ee - _start
  31:                0x0 - <unknown>
  </pre>
</details>

**Comment by khvzak** [comment]
in the code:
```
        lua.load(r#"config.version()"#)
```
you have a bug (not passing any args). you need to change this to:
```
        lua.load(r#"config:version()"#)
```
or
```
        lua.load(r#"config.version(config)"#)
```
https://www.lua.org/manual/5.1/manual.html#2.5.8

**Comment by sayanarijit** [comment]
Ah thanks 👍 fields will make things simpler.
