### ISSUE TITLE
Multiple modules in the same build cannot use each others UserData

### ISSUE THREAD

**Issue by horazont** [khvzak/mlua#49]
**Description**

When having multiple `#[mlua::lua_module]` entrypoints in the same binary, UserData objects created by one entrypoint are not recognized by the other entrypoint, even though they are the same Rust type.

**How to reproduce**

1. Compile the reproducer code.
2. Run `ln -s target/debug/libmlua_multimod.so libmod1.so && ln -s target/debug/libmlua_multimod.so libmod2.so`
3. Run the following lua snippet:

    ```lua
    local m1 = require "libmod1";
    local m2 = require "libmod2";
    local o1 = m1.construct("foo");
    local o2 = m2.construct("bar");
    print(m1.check(o1));
    print(m1.check(o2));
    print(m2.check(o1));
    print(m2.check(o2));
    ```

**What happens?**

The entrypoint for libmod1.so does not recognize the data from libmod2.so and vice-versa, despite both resolving to the very same shared library file and being loaded only once into process memory:

```
foo
nil     check failed: userdata is not expected type
nil     check failed: userdata is not expected type
bar
```

**What should happen instead?**

```
foo
bar
foo
bar
```

**Minimal reproducer**

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "mlua-multimod"
version = "0.1.0"
authors = ["Jonas Schäfer <j.wielicki@sotecware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.6.0-beta.2", features = ["lua52", "module"] }
```

</details>

<details>
<summary>src/lib.rs</summary>

```rust
use mlua::prelude::*;

#[derive(Clone)]
struct CustomData{
	data: String,
}

impl LuaUserData for CustomData {
	fn add_methods<'lua, M: LuaUserDataMethods<'lua, Self>>(methods: &mut M) {

	}
}

fn check<'l>(lua: &'l Lua, v: LuaValue) -> LuaResult<Result<String, String>> {
	match CustomData::from_lua(v, lua) {
		Ok(v) => Ok(Ok(v.data)),
		Err(e) => Ok(Err(format!("check failed: {}", e))),
	}
}

fn construct<'l>(lua: &'l Lua, s: String) -> LuaResult<CustomData> {
	Ok(CustomData{
		data: s,
	})
}

#[mlua::lua_module]
fn libmod1(lua: &Lua) -> LuaResult<LuaTable> {
	let exports = lua.create_table()?;

	exports.set("check", lua.create_function(check)?)?;
	exports.set("construct", lua.create_function(construct)?)?;

	Ok(exports)
}


#[mlua::lua_module]
fn libmod2(lua: &Lua) -> LuaResult<LuaTable> {
	let exports = lua.create_table()?;

	exports.set("check", lua.create_function(check)?)?;
	exports.set("construct", lua.create_function(construct)?)?;

	Ok(exports)
}
```

</details>

<details>
<summary>test.lua</summary>

```lua
local m1 = require "libmod1";
local m2 = require "libmod2";
local o1 = m1.construct("foo");
local o2 = m2.construct("bar");
print(m1.check(o1));
print(m1.check(o2));
print(m2.check(o1));
print(m2.check(o2));
```

</details>

**Additonal information**

The context of this is that I am rewriting parts of a larger lua application in Rust. I want to create drop-in replacements for the various components step-by-step. For that, it is required that one component can work with the data from another component. I currently use different entrypoints for the individual components with the same shared library object.

I can probably work around this by using a single shared library and shim lua wrappers which expose different parts of that shared library under the expected names.

**Comment by khvzak** [comment]
I pushed a fix to the master branch (+ tests). Could check please?

**Comment by horazont** [comment]
That was fast, thanks a lot! Works like a charm.
