### ISSUE TITLE
Can't Link Against anything but lua53

### ISSUE THREAD

**Issue by snsvrno** [khvzak/mlua#5]
### Using Vendored & luajit-src

At least that is what I'm assuming is happening. I want to build a module and load it into Love2D. Love2D uses LuaJIT.

I'm building the `my_module` code from the readme.md (unmodified) and it builds, but then when I load it in either Love2D or LuaJIT it just crashes. (Windows x64, used luapower for luajit).
This is my toml.

```
[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.3", features = [ "vendored" ] }
mlua_derive = "0.3"
luajit-src = "210"
```

### Without Vendored, Lua 5.1

When I don't put vendored it complains about the header files (which makes sense since I don't have them) but no matter what I do it always complains about lua53 files. I attempt to force it to do lua51 for testing and it gives me this message.

```
--- stderr
thread 'main' panicked at 'You can enable only one of the features: lua53, lua52, lua51, luajit'
```
with this toml file

```
[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.3", features = [ "lua51" ] }
mlua_derive = "0.3"
```

### Thoughts

perhaps I'm missing where to actually define what lua to use? My thoughts is that its building it for lua 5.3 when i used vendored but I want to build it for luajit. This is my first time using rust to talk to anything other than rust so I'm not very experienced with this process.

Thanks

> all of this is on Windows 10 x64 with rust 1.41, 2018 edition.

**Comment by khvzak** [comment]
Feature `lua53` is enabled by default (maybe I should disable it in the next release?)

If you change the line:
```
mlua = { version = "0.3", features = [ "lua51" ] }
``` 
to
```
mlua = { version = "0.3", default-features = false, features = [ "luajit", "vendored" ] }
```
It should compile.
Also, you don't really need to add `luajit-src` to dependencies. This is internal crate designed to use within `build.rs

**Comment by khvzak** [comment]
Building a proper module is quite tricky, especially in windows.
If you'll get some crashes (similar to #4) I'm working to fix it in the next release (and add CI to test modules on all major OS)

**Comment by snsvrno** [comment]
Thanks for the help. I didn't know you had to 'disable default' for features.

I did try it on Linux and it worked without any issues (once i disabled the default). I can get the Windows one to compile but it doesn't load in luajit or love (assuming its #4's issue). 

I'd say that the main issue is resolved, I'll keep trying on the Windows side and do it without `vendored`
