### ISSUE TITLE
Undefined symbol with crate's name uppon loading a module

### ISSUE THREAD

**Issue by big-lip-bob** [khvzak/mlua#54]
I was making a module but i couldn't get it to load in Lua.
I made a new test project using the minimal GitHub example.
(crate type : cdylib, module feature and module attribute to main function)
Ive tried vendored and system's variants of Lua5.3.6 and LuaJIT2.1b3.
Gone trough mlua : 0.5.4 and 0.6.0-beta.3.
I also tried using `LUA_LINK=static` but no luck either.
When `require`'ing the library, it just reports
```
error loading module 'liblua_module_test' from file './liblua_module_test.so':
	./liblua_module_test.so: undefined symbol: luaopen_liblua_module_test
```
I am under Linux (5.12.8-1, Manjaro x64)

**Comment by khvzak** [comment]
This error means that likely your module filename does not match with the exported function name.
What is name of your module and what name you requiring on the Lua side?

Basically, if you `require("module_test")` in Lua then your library file should be named as `module_test.so` and in Rust exposed as:
```rust
#[mlua::lua_module]
fn module_test(lua: &Lua) -> LuaResult<LuaTable> {
   ...
}
```
