### ISSUE TITLE
[Question] Why `RegistryKey` does not implement `Hash`?

### ISSUE THREAD

**Issue by AcrylicShrimp** [khvzak/mlua#57]
Hello!
I want to store `RegistryKey` into a `HashMap` as a key, but I can't because it does not implement `Hash`. Is there any specific reason to do not?
Thank you.

**Comment by khvzak** [comment]
No particular reason, I can add `impl Hash for RegistryKey`.
Just bear in mind that `RegistryKey` does not implement `Clone` and after adding to a `HashMap` you can only iterate the map and not get values.
However you can always use `Arc/Rc` to get values I believe.

**Comment by AcrylicShrimp** [comment]
Thank you for the quick response! I ended it up by wrapping it with a Box and hashing its address.
