### ISSUE TITLE
`.eval_async()` under `tokio::spawn`

### ISSUE THREAD

**Issue by abesto** [khvzak/mlua#58]
`mlua` has been amazing in my little hobby project so far, thank you for your work! I come with a question, am running out of ideas.

I'm running `mlua` under `tokio`. I'd like to schedule a Lua coroutine _from inside a `tokio::spawn` call_ (that is, from inside a `tokio` task), and inspect the results of that Lua coroutine. I've failed to find a way of making this work. The core of the problem seems to be that `mlua::Result` (or possibly `mlua::Lua` even?) is `!Send`, even under the `send` feature.

I've built a minimal repro: https://gist.github.com/abesto/9dc5ba23e8b46da0f3d5b9db9f46ff53

In context, the relevant part of my real code is at https://github.com/abesto/roo/blob/82106df79736e4acf5d54c4450f1930d7bb10afe/src/server.rs#L79-L81. Any guidance would be appreciated. (I'm currently contemplating creating a new Lua interpreter for the handling of each request, but that feels very wrong)

FTR, the compile error looks like this: https://gist.github.com/abesto/128723dbd85d6e50e7745d9a5de71f24

**Comment by khvzak** [comment]
Could you try to use `tokio::task::spawn_local` instead of `tokio::spawn`?

**Comment by abesto** [comment]
Oh wow, thank you for the quick response!

> Update: you probably could also require to make mlua::Lua 'static, this can be done by calling into_static method.

This doesn't seem to make a difference. Rust still complains about `Result`, and also:

```
note: captured value is not `Send`
   --> src\server.rs:80:23
    |
80  |             eval_task(lua, eval_rx, notify_tx.clone()).await;
    |                       ^^^ has type `&mlua::Lua` which is not `Send`
```

I've double-checked my `features`:

```
mlua = { version = "0.5.4", features = ["lua54", "vendored", "serde", "send", "async"] 
```

> Could you try to use tokio::task::spawn_local instead of tokio::spawn?

This, on the other hand, *does* work! It does mean that most of the app needs to run on a single thread, but to be honest I'm not too concerned about that. I imagine it'll be possible to minimize the part that does. I've managed to actually implement the functionality I tried to when I hit this issue, so can happily say this is now resolved. Thank you for your help!

**Comment by khvzak** [comment]
You're getting error because `&mlua::Lua` type does not implement `Send`. This is because `mlua::Lua` is not `Sync` (but `Send` if `feature = "send"` enabled).
Unfortunately it's hard to make Lua `Sync` and provide true parallelism :(

I'm glad that your problem solved.

**Comment by abesto** [comment]
Ooh, `Sync` vs `Send`. I never properly learned Rust parallelism, missed that distinction. Thank you for unconfusing me on that :)
