### ISSUE TITLE
Can't save LuaFunction

### ISSUE THREAD

**Issue by rise0chen** [khvzak/mlua#62]
```rust
struct Uart<'lua> {
    on_message: LuaFunction<'lua>,
}
impl<'lua> LuaUserData for Uart<'lua> {}


    let exports = lua.create_table()?;
    lua.create_userdata(Uart {
        on_message: lua.create_function(|_, msg: String| Ok(()))?,
    });
```

```rust
    pub fn create_userdata<T>(&self, data: T) -> Result<AnyUserData>
    where
        T: 'static + MaybeSend + UserData,
    {
        unsafe { self.make_userdata(UserDataCell::new(data)) }
    }
```
I think, `create_userdata` just need `'lua`. Why require `'static`?

**Comment by khvzak** [comment]
`UserData` needs `'static` due to [`TypeId::of::<T>`](https://doc.rust-lang.org/std/any/struct.TypeId.html) requirements.
`TypeId` is used for generating and attaching shared metatable to `UserData`.

As an alternative, you could use `Scope::create_nonstatic_userdata`, it does not have `'static` requirements and as a tradeoff uses unique metatable per instance (which is less efficient).

**Comment by rise0chen** [comment]
```rust
let uart = lua.scope(|scope| {
    scope.create_nonstatic_userdata(Uart {
        on_message: lua.create_function(|_, msg: String| Ok(()))?,
    })
})?;
```
```rust
pub fn scope<'lua, 'scope, R, F>(&'lua self, f: F) -> Result<R>
where
    'lua: 'scope,
    R: 'static,
    F: FnOnce<(&Scope<'lua, 'scope>,), Output = Result<R>>,
```

Oh no, `Result<R>>` require `'static`.

**Comment by khvzak** [comment]
This is how Scope works - it drops scoped objects on function leave.
1) You could place logic inside Scope
2) Or alternatively store Lua objects in [Registry](https://www.lua.org/manual/5.3/manual.html#4.5) using [`Lua::create_registry_value`](https://docs.rs/mlua/0.6.1/mlua/struct.Lua.html#method.create_registry_value) and keep [RegistryKey](https://docs.rs/mlua/0.6.1/mlua/struct.RegistryKey.html) which is `'static`
You can retrieve values back using [`Lua::registry_value`](https://docs.rs/mlua/0.6.1/mlua/struct.Lua.html#method.registry_value)

**Comment by rise0chen** [comment]
thanks, it's perfect
