### ISSUE TITLE
Unable to require the module package that I built correctly

### ISSUE THREAD

**Issue by yancheng199287** [khvzak/mlua#63]
os: ubuntu18

rust version:
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.54.0-nightly (f64503eb5 2021-05-23)

1. cd mlua-master/examples/module

2. build module
`LUA_INC=/home/yancheng/lua/lua54-bin/include LUA_LIB=/home/yancheng/lua/lua54-bin LUA_LIB_NAME=lua54 cargo build
`
3.  require the lib
```
host-1:~/work/rust/mlua-master/target/debug$ ls
build  deps  examples  incremental  libmlua.d  libmlua.rlib  librust_module.d  librust_module.so
host-1:~/work/rust/mlua-master/target/debug$ lua54 -e 'print(require("librust_module").sum(2,3))'
lua54: error loading module 'librust_module' from file './librust_module.so':
        ./librust_module.so: undefined symbol: luaopen_librust_module
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: in ?
host-1:~/work/rust/mlua-master/target/debug$
```

how to resolve it?

**Comment by khvzak** [comment]
Seems this is the same as #54

Could you please try renaming your module file to `rust_module.so` and require `rust_module`.
This is how Lua load modules: https://www.lua.org/manual/5.4/manual.html#pdf-package.searchers
