### ISSUE TITLE
Any reason why the event field of lua_Debug is not exposed through the Debug struct?

### ISSUE THREAD

**Issue by menixator** [khvzak/mlua#67]
I noticed that with the interface that mlua provides, I cannot tell why the hook was called.

Skimming through mlua and lua source code it seems like the event property of  `lua_Debug` struct has an event field which might be what I'm looking for.

https://github.com/khvzak/mlua/blob/1d7f105585e4f961967ee8d8cbd8fbfbc4787281/src/ffi/lua.rs#L792

So my question is, is there any reason why that field is not exposed through the rust wrapper `Debug` ?

**Comment by khvzak** [comment]
No particular reason, mostly historically. I'll add "event" support to the debug interface in next release.

**Comment by khvzak** [comment]
Added with commit 9f02a9ca09f90082a9e0f8f2c52a331967db76a5
