### ISSUE TITLE
Overloading the constructor of UserData

### ISSUE THREAD

**Issue by hasenbanck** [khvzak/mlua#70]
Hi,

I'm currently trying to overload the constructor of some UserData:

When I do this, everything is fine:

```rust
    #[derive(Copy, Clone, Debug, Default)]
    pub struct Vec2 {
        pub x: f64,
        pub y: f64,
    }
    
    impl UserData for Vec2 {
        fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
            methods.add_meta_function(MetaMethod::Call, |_, ()| Ok(Vec2::default()));
        }
    }
```

```lua
    local v1 = Vec2()
```

But when I try to overload the constructor like this:
```rust
        fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
            methods.add_meta_function(MetaMethod::Call, |_, ()| Ok(Vec2::default()));
            methods.add_meta_function(
                MetaMethod::Call,
                |_, (_, (x, y)): (AnyUserData, (f64, f64))| Ok(Vec2 { x, y }),
            );
    }
````

Without changing the lua code, I get the following error:

```bash
stack traceback:
	[C]: in global 'Vec2'
	[string "main"]:2: in function 'Main'
	[string "?"]:1: in main chunk
error converting Lua nil to f64 (expected number or string coercible to number)
```

I have to change my lua code like this to make it run again and make both constructors work:
```lua
    local v1 = Vec2
    --- the second constructor also works.
    local v2 = Vec2(1.0, 1.0)
```

Is this the expected behavior? I would assume that I could call both constructors as a function call without leaving the "()" away when defining a second constructor with arguments.

Edit: The "working" code is not really calling a constructor but uses the global of the Vec2, so it's not really a fix.

**Comment by khvzak** [comment]
Unfortunately it's not possible in Lua to have two metamethods with the same name. The 2nd one replaces the 1st one in the example above.

What you could do is to handle situation when optional `x` and `y` are provided:
```
            methods.add_meta_function(
                MetaMethod::Call,
                |_, (_, x, y): (AnyUserData, Option<f64>, Option<f64>)| match (x, y) {
                    (Some(x), Some(y)) => Ok(Vec2 { x, y }),
                    _ => Ok(Vec2::default()),
                },
            );
```

This should cover both cases.

**Comment by hasenbanck** [comment]
Thank you for verifying that this is the expected behavior and for the tip with the optionals.
