### ISSUE TITLE
Symbol not found: _lua_settable

### ISSUE THREAD

**Issue by mrxiaozhuox** [khvzak/mlua#73]
I try to use mlua import a `so` file.

```
dlopen(/Users/liuzhuoer/Library/Application Support/interface/interface.so, 6): 
Symbol not found: _lua_settable
```
This `so` file are also build with `Rust + mlua`.

I try to use `Lua xxx.lua` run it and `require` it was success.

My Code:
```
unsafe {
    // unsafe mode
    let mut lua = Lua::unsafe_new();
    lua.load(&code).exec()?;
}

```

**Comment by khvzak** [comment]
You need to build your project with the following options
```
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
```
in `.cargo/config` to expose C symbols

**Comment by mrxiaozhuox** [comment]
> ```toml
> [target.x86_64-apple-darwin]
> rustflags = ["-C", "link-args=-rdynamic"]
> 
> [target.x86_64-unknown-linux-gnu]
> rustflags = ["-C", "link-args=-rdynamic"]
> ```

build `.so` file ? my command: `cargo rustc -- -C link-arg=-undefined -C link-arg=dynamic_lookup`

**Comment by khvzak** [comment]
Could you clarify please, where the following code used?
```
unsafe {
    // unsafe mode
    let mut lua = Lua::unsafe_new();
    lua.load(&code).exec()?;
}
```
If in application (not module, in order to expose Lua C symbol (needed to load modules), you have to build your application with `link-args=-rdynamic` linker option.

**Comment by mrxiaozhuox** [comment]
> Could you clarify please, where the following code used?
> 
> ```rust
> unsafe {
>     // unsafe mode
>     let mut lua = Lua::unsafe_new();
>     lua.load(&code).exec()?;
> }
> ```
> 
> If in application (not module), in order to expose Lua C symbol (needed to load modules), you have to build your application with `link-args=-rdynamic` linker option.

thanks, I add the cargo-config and its successful to build.

**Comment by khvzak** [comment]
Please reopen if the issue still exists
