### ISSUE TITLE
Static vendored linkage on Windows

### ISSUE THREAD

**Issue by HybridEidolon** [khvzak/mlua#8]
For the sake of developer convenience, I would like to be able to compiled a vendored lua or luajit lib under Windows as a static library. This spares the complexity of setting up the build environment to include the Lua library under Windows, which is the primary development OS for my project as it specifically supports a Windows-only application. However, it doesn't seem either of the source crates support building in this way on Windows.

What would be necessary to add static vendoring support to these crates?

Edit: for context, this is an app using the Lua VM directly, not a C extension module. It is not entirely clear from the documentation if this is already supported or not.

**Comment by khvzak** [comment]
Windows static vendored builds are supported and [tested in the CI](https://github.com/khvzak/mlua/blob/master/.github/workflows/main.yml#L10).

`lua-src` and `luajit-src` crates support Windows as well.

Are you getting any particular error when running `cargo build --release --features "lua53 vendored"` in Windows?

**Comment by HybridEidolon** [comment]
No, I am not. I was simply misunderstanding the documentation when it said that vendored mode was not supported on Windows. I'll go ahead and close this now.
