### ISSUE TITLE
When using serializable type containing u128 -> serialize error: u128 is not supported

### ISSUE THREAD

**Issue by chipsenkbeil** [khvzak/mlua#81]
I'm trying to figure this one out. I think this is because mlua's serde feature doesn't implement serialization for u128 or i128. To my knowledge, these support optional serialize/derserialize and default to reporting an error about not being supported as they:

1. Require Rust 1.26+
2. Require [serde 1.0.60+](https://github.com/serde-rs/serde/releases/tag/v1.0.60)

serde_json handled this by gatekeepering it behind a feature called `arbitrary_precision` and leveraging the macro `serde::serde_if_integer128`: https://github.com/serde-rs/json/blob/d279a78a23819c128bbab99ddc34ef3930ef20b1/src/value/ser.rs#L121

I only use this primitive type as it's the default for creation, modification, and access time fields from an sftp library. I'm assuming I can get by with u64 at the moment, but wanted to open an issue in case this was a change needed on mlua's side.

If you think this is not related to mlua, feel free to close 😄

**Comment by khvzak** [comment]
128bit integers indeed are not supported because Lua internally uses 64bit (optionally can be compiled to 32bit).
Although, you can wrap 128bit integers to a userdata struct (defining arithmetic operations if needed).

**Comment by khvzak** [comment]
Thanks, I'll add 128bit integers support

**Comment by chipsenkbeil** [comment]
@khvzak it's a good question. I've only seen `u128` used when it comes to `std::time::Duration::as_millis` and others where I'm getting the time since Unix epoch in milliseconds. I'm assuming this would be handy for getting the time in nanoseconds, but that seems niche.

The sftp library returns in milliseconds, I believe. The current time in seconds since unix epoch as of now is 1633365591. If we take that to milliseconds, that is 1633365591000.

```rust
1633365591000        // Epoch time in milliseconds
18446744073709551615 // Max u64
```

I think it's fine to truncate to u64 when serializing to lua and just have a disclaimer about that somewhere. If someone really wanted to work with u128/i128, they could write their own userdata and I imagine they'd have their own math library for that. This is just for data structures that are serde serializable/deserializable where I don't have control over changing the type from u128/i128 and don't want to write a wrapper just to convert one or two fields to u64/i64.
