### ISSUE TITLE
Unexpected seg faults and killed 9 when loading module built for aarch64-apple-darwin

### ISSUE THREAD

**Issue by chipsenkbeil** [khvzak/mlua#82]
I'm trying to diagnose this, but it seems like when I cross-build an `aarch64-apple-darwin` module from the Github MacOS 11.0 runner, which is `x86_64-apple-darwin`, the built module causes a seg fault when loaded on my M1 Mac.

Is there anything I can look into to figure out why this is? When I build it directly on my M1 Mac, it works just fine.

I've got automated github workflow that builds all of my assets including the Lua module for Windows, Linux, and both Intel and ARM macs, and didn't realize this was happening until I tried to download the module and load it.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/2481802/136610550-3a6d224f-3b39-450a-a0db-66ff2a4c32a4.png">

**Comment by chipsenkbeil** [comment]
That's actually what I was doing since they were binary compatible. I'm trying to load the lua51 module in luajit, although loading using lua 5.1.5 has the same problem.

**Comment by chipsenkbeil** [comment]
From `(cd distant-lua && cargo build)` on my M1 Mac.

```rust
/* this file was generated by glue.c; do not modify it by hand */
use std::os::raw::*;
/* luaconf.h */
pub const LUA_EXTRASPACE: c_int = 8;
pub const LUA_IDSIZE: c_int = 60;
pub type LUA_NUMBER = c_double;
pub type LUA_INTEGER = i64;
pub type LUA_UNSIGNED = u64;
/* lua.h */
pub const LUA_VERSION_NUM: c_int = 501;
pub const LUA_REGISTRYINDEX: c_int = -10000;
pub const LUA_ENVIRONINDEX: c_int = -10001;
pub const LUA_GLOBALSINDEX: c_int = -10002;
/* lauxlib.h */
/* lualib.h */
pub const LUA_COLIBNAME: &str = "coroutine";
pub const LUA_TABLIBNAME: &str = "table";
pub const LUA_IOLIBNAME: &str = "io";
pub const LUA_OSLIBNAME: &str = "os";
pub const LUA_STRLIBNAME: &str = "string";
pub const LUA_MATHLIBNAME: &str = "math";
pub const LUA_DBLIBNAME: &str = "debug";
pub const LUA_LOADLIBNAME: &str = "package";
```

**Comment by chipsenkbeil** [comment]
I managed to export `glue.rs` cross-built via the Github worker for a sample project and it looks like this:

```rust
/* This file was generated by build/main.rs; do not modify by hand */
use std::os::raw::*;
/* luaconf.h */
pub const LUA_EXTRASPACE: c_int = 64 / 8;
pub const LUA_IDSIZE: c_int = 60;
pub type LUA_NUMBER = c_double;
pub type LUA_INTEGER = i64;
pub type LUA_UNSIGNED = u64;
/* lua.h */
pub const LUA_VERSION_NUM: c_int = 501;
pub const LUA_REGISTRYINDEX: c_int = -1000000 - 1000;
pub const LUA_ENVIRONINDEX: c_int = -10001;
pub const LUA_GLOBALSINDEX: c_int = -10002;
/* lauxlib.h */
pub const LUAL_NUMSIZES: c_int = std::mem::size_of::<LUA_INTEGER>() as c_int * 16 + std::mem::size_of::<LUA_NUMBER>() as c_int;
/* lualib.h */

#[cfg(feature = "luajit")]
pub const LUA_BITLIBNAME: &str = "bit";
#[cfg(not(feature = "luajit"))]
pub const LUA_BITLIBNAME: &str = "bit32";

pub const LUA_COLIBNAME: &str = "coroutine";
pub const LUA_DBLIBNAME: &str = "debug";
pub const LUA_IOLIBNAME: &str = "io";
pub const LUA_LOADLIBNAME: &str = "package";
pub const LUA_MATHLIBNAME: &str = "math";
pub const LUA_OSLIBNAME: &str = "os";
pub const LUA_STRLIBNAME: &str = "string";
pub const LUA_TABLIBNAME: &str = "table";
pub const LUA_UTF8LIBNAME: &str = "utf8";

pub const LUA_JITLIBNAME: &str = "jit";
pub const LUA_FFILIBNAME: &str = "ffi";
```

**Comment by khvzak** [comment]
Sorry I pushed another fix after getting this error from CI

**Comment by chipsenkbeil** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/2481802/136623580-88047872-0ecc-4924-9000-96236f623d9f.png">

This is the error I see with my [test repo](https://github.com/chipsenkbeil/mlua-release-test) for 0.6.5 as well, so not sure if this is unrelated.

I'm also seeing errors trying to compile my separate test crate on x86_64 for MacOS and Linux now: https://github.com/chipsenkbeil/distant/runs/3842709684

**Comment by khvzak** [comment]
I see you added `module` feature in https://github.com/chipsenkbeil/distant/commit/a6393bae80a486567046a9e3eafa305bb05ff8f3 to `distant-lua-tests`. This is why you getting link error.

**Comment by chipsenkbeil** [comment]
@khvzak fixed the tests per your callout, but that still leaves the "file too short" error. My Internet has gone out at my house, so I'm using my phone. Earlier, before your latest commit, I had a friend airdrop me the library from their Intel mac to my M1 mac and got the seg fault; so, this isn't just tied to the Github action from what I can see.

And to recap, the test library I made was giving me the "file too short" error prior to your commit whereas my `distant-lua` project was giving a seg fault but was recognized by `lipo -info` as aarch64. Not sure how to pin this one down.

**Comment by khvzak** [comment]
> If you're feeling adventurous, I'd be happy to create a guest account on my M1 Mac Mini and let you ssh into it to test things.

Thanks, it would be helpful! I cannot find any public CI thats offers m1 :( AWS also does have arm macs. Could you write to me email zxteam[at]protonmail.com

it’s quite unexpected to get segfault when cross-compiling to aarach64. Modules does not have any C code linked.

**Comment by chipsenkbeil** [comment]
@khvzak sent you an email.

As for the tier2, I'm aware :D For me, as long as I can get it working in some way - aka building natively on M1 - then I'm okay. This just stops me from being able to automatically build and release the Lua module for M1 Macs. This does seem to be related to mlua in some way as the cli binary cross-built from x86_64 to aarch64 works just fine when I download it.

**Comment by chipsenkbeil** [comment]
@khvzak thanks for your help here! I tried pointing directly to the latest git version and this time it worked! So I must have had Cargo.lock getting in the way or something else going on. Anyway, once we get a new release out for the fix, we can close this task. :)
