### ISSUE TITLE
Using x86_64-unknown-linux-musl as a target for a module

### ISSUE THREAD

**Issue by chipsenkbeil** [khvzak/mlua#85]
This is just an open question and I think the answer is no. Is it possible in some way to build a Lua module with musl as the target? If you try to build a `cdylib`, you get the immediate notification that the musl target doesn't support that crate type.

You **can** use a `staticlib` crate type and it builds fine, but to my knowledge you cannot import `*.a` or `*.lib` (windows) using module `require(...)` in Lua. I've seen scattered mentioning of baking static libraries into programs that also embed lua like [Lua EPICS module](https://epics-lua.readthedocs.io/en/latest/adding-libraries.html#static-libraries), but no mention for Lua 5.1+ or luajit about using them.

With my lack of knowledge in the space, I'm assuming it doesn't make sense to link to a static library. The only reason this popped up for me is that some musl-based systems like Alpine linux don't have the needed libraries like ld-linux-x86-64.so  for Lua to be able to load the module when built with the gnu target. This isn't a dealbreaker for me, but is a limitation of my move to a Lua module for [distant.nvim](https://github.com/chipsenkbeil/distant.nvim).

**Comment by khvzak** [comment]
Hmm, it should be possible. You probably need to build it inside docker on alpine image.
Resulted library will be dynamically linked to a musl c runtime.
Or with cross compilation you need musl gcc cross-compiler. The error message you got probably means that you cannot produce musl dynamic library using glibc compiler (I can be wrong).

**Comment by chipsenkbeil** [comment]
Closing this out as I think I finally got my deployment working with the extra flags per your rec. This is also out of scope for mlua and is actually a rust/cargo challenge. :) Appreciate all of your help here even though this wasn't an mlua problem!

**Comment by afsec** [comment]
Hi. I tried all these solutions. But does not worked for me on my project https://gitlab.com/brickpack/brickpack 
I'm temporarily disabling musl target, sadly. Maybe someone could reopen this issue.
