### ISSUE TITLE
aarch64-apple-darwin release build of module crashes on one machine but not another

### ISSUE THREAD

**Issue by chipsenkbeil** [khvzak/mlua#89]
I thought I was finished with the crashes, but unfortunately it seems like the release build that I have being produced as a cross build from x86_64-apple-darwin to aarch64-apple-darwin is causing neovim (also built for aarch64) and luajit to crash immediately when loaded on my Mac Mini, but not on my Macbook Air. Both are the M1 variant, and the build does not come from either of them directly.

I curl the library from https://github.com/chipsenkbeil/distant/releases/tag/v0.15.0 onto both machines. Even trying to do something like `lipo -info path/to/distant_lua.so` causes a crash.

![image](https://user-images.githubusercontent.com/2481802/137643842-e81c3658-895d-412e-b129-d7aa16d51d80.png)

Is there something I can look into to figure out why this is the case?

The access I gave you, @khvzak, is still around in case you have time to investigate.

**Comment by chipsenkbeil** [comment]
In fact, if I download ANY of the modules binaries for any of the platforms (linux gnu, musl, mac intel, etc) tools like `lipo -info distant_lua.so` crash. I would have expected something about invalid exec format instead.

**Comment by chipsenkbeil** [comment]
One difference between my Mac Mini and Macbook Air is that my mini is running on Bug Sur 11.5.2 whereas my Air is running on Big Sur 11.6. Otherwise, I'm not sure why two Macs with an identical M1 processor would be having this kind of problem. Going to try to update my OS and see if there was some bug resolved.

**Comment by chipsenkbeil** [comment]
The update to Big Sur 11.6 seems to have fixed the issue. Either that or just a restart was needed for some other reason. I'm going to close this out.

**Comment by khvzak** [comment]
Thanks @chipsenkbeil !
Seems I need to wait for M2 and MacOS 11.7 before buying a new ARM mac 😄

**Comment by chipsenkbeil** [comment]
Lol, no kidding XD

**Comment by Kinchkun** [comment]
Hi,

this is an older one, but I had the same issues, that when building modules they randomly crashed until a restart of the machine.

I thinks the issues is this: https://developer.apple.com/documentation/security/updating_mac_software

mac os caches the code signature of the .so. For some reasons, when rebuilding and also `cp` the .so to the target location mac os does not update the code signature. 

When rebuilding I have to explicitly delete the .so beforehand.
