### ISSUE TITLE
Segfault in test_pcall_xpcall on Apple arm64

### ISSUE THREAD

**Issue by jmechnich** [khvzak/mlua#92]
While researching [this issue](https://github.com/sayanarijit/xplr/issues/384) I was checking if `mlua` works properly on arm64. Running `cargo test --features luajit,vendored` in a local copy of the current master branch works fine on my x86_64 linux machine.
On my MacBook I am getting a segmentation fault:

```
git clone git@github.com:khvzak/mlua.git
cd mlua
cargo test --features luajit,vendored
(...)
test test_lua_registry_ownership ... ok
error: test failed, to rerun pass '--test tests'

Caused by:
  process didn't exit successfully: `/Users/mechnich/Software/mlua/target/debug/deps/tests-9b55df5959891bb3` (signal: 11, SIGSEGV: invalid memory reference)
```
Running the executable in `rust-lldb` produces the following output: [debug.txt](https://github.com/khvzak/mlua/files/7427125/debug.txt)
The crash seems to happen in `test_pcall_xpcall`.

Let me know if I can assist in any way.

Environment: MacBook Air M1 2020, macOS 12.0.1, rust 1.56.0 installed via homebrew

Edit: I just found https://github.com/khvzak/mlua/issues/80 which could be related (at least to my original problem).

Edit 2: after reading (and hopefully understanding) https://github.com/khvzak/mlua/issues/80, I brew installed `luajit-openresty` and tried again with `cargo test --features luajit`. This produces the same segfault, so I am guessing it might be an issue in `luajit-openresty` (?)

**Comment by khvzak** [comment]
luajit-src `210.3.2+resty1085a4d` with the fix released
